The Project Gutenberg eBook of A Short System of English Grammar

This eBook is for the use of anyone anywhere in the United States and
most other parts of the world at no cost and with almost no restrictions
whatsoever. You may copy it, give it away or re-use it under the terms
of the Project Gutenberg License included with this eBook or online at
www.gutenberg.org. If you are not located in the United States, you will
have to check the laws of the country where you are located before using
this eBook.

Title: A Short System of English Grammar

Author: Henry Bate

Release date: October 22, 2008 [eBook #26991]

Language: English

Other information and formats: www.gutenberg.org/ebooks/26991

Credits: Produced by Chris Curnow, Lindy Walsh and the Online
Distributed Proofreading Team at http://www.pgdp.net

*** START OF THE PROJECT GUTENBERG EBOOK A SHORT SYSTEM OF ENGLISH
GRAMMAR ***

Produced by Chris Curnow, Lindy Walsh and the Online Distributed
Proofreading Team at http://www.pgdp.net

A

Short /System/

OF

English GRAMMAR.

For the use of the

BOARDING SCHOOL

In WORCESTER.

/By/ HENRY BATE /A. B./

/Worcester:/ Printed by R. LEWIS, Bookseller, in /High-Street/.

THE PREFACE.

/Usage and Custom are the Rules and Measures of every/ Language, /and
the Rules of/ GRAMMAR /have nothing more to do, than to teach it. The/
GRAMMAR /is to be fashioned from the particular/ Language, /it treats
of, and not the Language from the/ GRAMMAR. /For want of following this
regular Plan, our Modern/ GRAMMARIANS_ have introduced the_ GRAMMAR
Rules /of other/ Languages /into their own; as if all/ Language /was
founded on/ GRAMMAR, /and the Rules in one/ Language /would serve the
same End and Purpose in another./

The Latin, /for Instance, has only/ eight Parts of Speech, /and the
Writers of/ English GRAMMAR /have unthinkingly adopted the same Number;
whereas with the Article, which the/ Latin /has not, and which is of
great Service in a/ Language, /we have no less than nine. The/ Latin
/admits of/ Cases; /but as different/ Cases, /properly speaking, are
nothing more than the different Inflections and Terminations of Nouns/,
English Nouns /have no/ Cases. /It is not agreeable to the Principles
of/ GRAMMAR /to say that/--of a Rose--/is the Genitive Case of/--Rose,
/or/--to a Rose, /the Dative; for/ of /and/ to /are no Part of the Word/
Rose, /but only/ prefix Particles /or/ Prepositions, /which shew the
different Relation of the Word/ Rose. /So likewise when we say/
Alexander's Horse, /the Word/ Alexander's /is not the Genitive Case of/
Alexander; /for strictly speaking the/ 's /is no Part of the Word/
Alexander /but the final Letter of the Pronoun Possessive/ his, /and
without the/ Apostrophe /we shou'd read it thus;/ Alexander his Horse.
/If any of the/ Parts of Speech /have/ Cases, /the/ Pronouns /have, and
some of the/ Pronouns /may perhaps have/ two; /but for the Sake of
making every Thing as easy as I can to the Learner, I have taken the
Liberty of distinguishing such/ Pronouns /into/ Prefix /and/ Subsequent,
/and entirely laid aside/ Cases /as useless and unnecessary. The/ Latin
/has/ Genders, /the/ Adjective /in that Language always varying to
correspond with the/ Substantive; _but our_Adjectives /never vary, and
therefore the Distinction of/ Genders /has nothing to do with/ English
GRAMMAR, /but is idle, trifling, impertinent./

EXPERIENCE /shews, that this Sort of pedantick Ignorance and Folly, has
made that dark and obscure, which it was intended to elucidate, and
unhappily puzzled and perplexed a great many more, than it has ever
instructed. Every attempt to make/ English easy /must be fruitless, that
is not formed upon a different Plan, and such is the following/ short
System of English GRAMMAR.

A Short /System/ OF English GRAMMAR.

/Of/ GRAMMAR /and it's/ DIVISIONS.

Grammar is the Science of Letters or Language, and is the Art of
Speaking and Writing properly.

It's Divisions are four;

ORTHOGRAPHY ANALOGY PROSODY SYNTAX

/Of/ ORTHOGRAPHY.

Orthography comprehends /Writing/, and /Articulation/. /Articulation/
treats of Simple Sounds, which are made by the Organs of Speech, and by
which we communicate our Ideas and Sentiments to one another. /Writing/
represents the Living Speech, and makes as it were these Sounds and
Sentiments visible.

/Of/ PROSODY.

Prosody treats of Pronunciation with respect of /Accent/, /Time/, and
/Quantity/. But as the Science of Letters, Sounds, and Pronunciation is
instilled into the Minds of the English Youth very early in Life, and as
this GRAMMAR is not intended for the Use of /Foreigners/, but for them;
I shall not trifle away their Time, in teaching them, what they cannot
be supposed to be unacquainted with; but proceed to the third Part of
GRAMMAR called /Analogy/.

/Of/ ANALOGY.

Analogy is the mutual Relation, or Agreement of Words with one another,
and treats of all the /Parts of Speech/, which in English are /nine/.

/Article/ /Verb/ /Conjunction/ /Noun/ /Participle/ /Preposition/
/Pronoun/ /Adverb/ /Interjection/

/Of An/ ARTICLE.

An Article is a /Part of Speech/ put before /Nouns/ to ascertain and fix
their Vague Signification. There are three Articles, /a/, /an/, and
/the/. /A/ and /an/ are Indefinite Articles and applied to Persons or
Things indifferently; as /an Oyster/, /a Prince/. The Article /the/
distinguishes individually or particularly; as /the Oyster/, /the
Prince/.

/Of a/ NOUN.

A Noun is a /Part of Speech/ which expresses the Subject spoke of; as
/Ink/, /Paper/, /Witness./

A Noun is either /Substantive/, or /Adjective/.

A Noun /Substantive/ is the Name of a Thing considered simply in itself,
and without any Regard to it's Qualities; as /a Man/, /a Woman/, /a
Child/.

A Noun /Adjective/ is a Word added to the /Noun Substantive/, expressing
the Circumstance or Quality thereof; as /a good Man/, /an old Woman/, /a
young Child/.

/Of a/ PRONOUN.

A Pronoun is a /Part of Speech/ substituted in the Place of a /Noun/, to
avoid the frequent and disagreeable Repetition of the same Word; as /the
Bird/ is joyous, /he/ chirps, /he/ sings; which without the /Pronoun/
wou'd be thus; /the Bird/ is joyous, /the Bird/ chirps, /the Bird /
sings.

PRONOUNS PERSONAL.

/I/ /He/ /Myself/ /I myself/ /Me/ /Him/ /Yourself/ /You yourself/ /You/
/She/ /Thyself/ /Thou thyself/ /Thou/ /Her/ /Himself/ /He himself/
/Thee/ /One's self/ /Herself/ /She herself/

PRONOUNS RELATIVE.

/Who/, /whose/, /whom/, /what/, /which./

PRONOUNS DEMONSTRATIVE.

/This/, /that./

PRONOUNS POSSESSIVE.

/My/ /Ours/ /Your/ /Theirs/ /Mine/ /Thy/ /Yours/ /Her/ /Our/ /Thine/
/His/ /Hers/

/Of/ NUMBER.

Number expresses the Difference betwixt one Thing and many, and is
either /Singular/ or /Plural/.

When a Thing is considered as single, or a Multitude of Things
considered as united together, it is of the /Singular Number/; as /a
Man/, /a Troop/.

When several Things are considered as distinct from each other it is of
the /Plural Number/, as /Men/, /Soldiers/.

The /Plural/ is usually formed in /Noun Substantives/ by adding /s/ to
the /Singular/; as /Article Articles/, /Noun Nouns/.

But when the Pronunciation requires it, or when the /Singular/ ends in
/s/, /x/, /sh/, or /ch/, the /Plural/ is usually formed by adding the
Syllable /es/; as /Ass Asses/, /Fox Foxes/, /Sash Sashes/, /Church
Churches/.

When the /Singular/ ends in /f/ or /fe/, the /Plural/ is usually form'd
by changing the /f/ or /fe/ into /ves/; as /Wife Wives/, /Self Selves/.

Sometimes the /Plural/ is formed by adding the Syllable /en/; as /Ox
Oxen/; sometimes by changing the /Vowel/; as /Man Men/; and sometimes
the /Vowels and Consonants/; as /Penny Pence/, /Mouse Mice/, /Louse
Lice/.

Some of the /Pronouns/ form their /Plural/ very irregular; as /I We/,
/Me Us/, /Thou Ye/, /Thee You/, /He They/, /Him Them/, /She They/, /Her
Them/.

Some /Nouns/ have no /Singular Number/; as /Scissors/, the
/East-Indies/, the /West-Indies/.

Some have no /Plural/; the Names of Kingdoms for Instance; as /England/,
/Ireland/, /Portugal/.

Cities, Towns and Villages; as /Worcester/, /Kinver/, /Hagley/.

Seas, and Rivers; as the /Mediterranean/, /Severn/.

/Wheat/, /Barley/, /Gold/, /Silver/, /Pewter/, and a great many Words,
that cannot be reduced to any Rule want the /Plural Number/; as /Ale/,
/Beer/, /Bread/, /Butter/, /Honey/, /Milk/, /Hunger/, /Thirst/,
/Drunkenness/.

The Termination of some /Nouns/ is the same both in the /Singular/ and
/Plural/; as /a Sheep/, /a Swine/, a Flock of /Sheep/, a Herd of
/Swine/, &c.

/Of/ COMPARISON.

Comparison is the comparing the different Circumstances of Persons or
Things with each other, and serves to alter the Signification of a Word,
either by a gradual Increase, or a gradual Diminution; as /long longer
longest/, /short shorter shortest/.

ADJECTIVES, /Adverbs/, and /Substantives/, have three Degrees of
Comparison, the /Positive/, the /Comparative/, and the /Superlative/.

The /Positive/ lays down the Natural Signification simply and without
excess or Diminution; as /long/, /short/, /often/.

The /Comparative/ raises or lowers the /Positive/ in Signification, and
is formed of the /Positive/ by adding the Syllable /er/; as /long
longer/, /short shorter/, /often oftener/.

The /Superlative/ raises or lowers the Signification as much as
possible, and if formed of the /Positive/ by adding the Syllable /est/;
as /long longest/, /short shortest/, /often oftenest/.

Sometimes they are compared by the /Adverbs/ /very, infinitely/; and the
/Adjectives/ /more, most/; /less, least/; as /long, very long,
infinitely long/; /short, more short, most short/; /commonly, less
commonly, least commonly/.

These /Adjectives/ deviate from the general Rule, /good better best/,
/bad worse worst/, /little less least/, /much more most/.

SUBSTANTIVES are compared by the /Adjectives/ /more, most/, the Words
/than/, or /that/, always following; as a Dunce, /more/ a Dunce /than/ I
or me, the /most/ a Dunce /that/ ever I did see.

/Of a/ VERB.

A Verb is a /Part of Speech/, which serves to express, what we affirm
of, or attribute to any Subject, and is either /Active/ or /Passive/.

A Verb /Active/ is that which expresses an /Action/; as /I kick/, /I
see/.

A Verb /Passive/ is that which receives the /Action/ or expresses the
/Passion/; as /I am kick'd/, /I am seen/.

A Verb has two /Numbers/ the /Singular/ and the /Plural/; and three
/Persons/ in each /Number/; as /I am, thou art, he is/. /We are, ye are,
they are./

The same is to be observed in every /Mood/ and in every /Tense/ but in
the /Infinitive/, which has neither /Number/ nor Person.

/Of/ MOODS.

A mood is the Manner of /conjugating Verbs/ agreeably to the different
Actions or Affections to be expressed.

There are /four Moods/, the /Indicative/, the /Imperative/, the
/Conjunctive/, and the /Infinitive./

The /Indicative Mood/ expresseth the /Action/ or /Passion/ simply
directly and absolutely; as /I love, I have loved, I will love/.

The /Imperative/ commands or forbids; as /come/, /go/, /begone/.

The /Conjunctive/ expresses the /Action/ or /Passion/ conditionally and
is always joined with the /Indicative/, or the same /Mood/; as /I will
love you, if you wou'd love me/; /I wou'd dance, if you wou'd dance/.

The /Infinitive/ expresses the /Action/ or /Passion/ indeterminately
without any Regard to /Time/, /Place/, /Number/, or /Person/; as /to
love, to be loved/.

/Of the/ TENSES.

Tense is an Inflection of Verbs, whereby they are made to signify, and
distinguish the Circumstance of /Time/.

There are /five Tenses/, /the Present Tense/, /the Preterimperfect/,
/the Preterperfect/, /the Preterpluperfect/, and /the Future/.

1. The /Present Tense/ expresses the Time, that now is; as /I sup/.

2. The /Preterimperfect Tense/ denotes the historical Relation of a past
   Action, but yet not perfectly compleated, when joined to another
   Action that is perfectly compleated; as /when or while I supped he
   came in/.

3. The /Preterperfect Tense/ expresses the Time Past perfectly; as /I
   have supped/.

4. The /Preterpluperfect Tense/ expresses the Time Past doubly; as /I
   had supped/.

5. The /Future Tense/ expresses the Time to come; as /I shall sup, I
   will sup/.

/Of the/ CONJUGATION.

Conjugation is the Variation of Verbs through all their /Moods and
Tenses/; and the English Verbs are chiefly conjugated by /auxiliary
Signs/; as /to love/; or by /auxiliary Verbs/; as /I am loved, I have
loved/.

/Of the/ AUXILIARY SIGNS.

The /auxiliary Signs/ are Words that serve to express the Variations of
the /Verb/.

The /Imperative Mood/ has the /Signs/ /do, let/; as--/do thou love, let
him love/.

The /Infinitive Mood/ has the /Signs/ /to, about/; as /to love, about to
love/.

The other /Moods/ have the /auxiliary Signs/ following.

/Singular/

1st /Person/ { I do, did, must, may, { can, might, wou'd, cou'd, {
shou'd, shall, /or/ will.

2d /Person/ { Thou do'st, did'st, must, { may'st, can'st, might'st, {
wou'd'st, cou'd'st, shou'd'st, { shalt /or/ wilt.

3d /Person/ { He does, or do'th, did, must, { may, can, might, wou'd, {
cou'd, shou'd, shall, /or/ { will.

/Plural/

1st /Person/ { We do, did, must, may, { can, might, wou'd, cou'd, {
shou'd, shall, /or/ will.

2d /Person/ { Ye do, did, must, may, { can, might, wou'd, cou'd, {
shou'd, shall /or/ will.

3d /Person/ { They do, did, must, may, { can, might, wou'd, cou'd, {
shou'd, shall /or/ will.

/Of the/ AUXILIARY VERBS.

The /auxiliary Verbs/ are only two, /to Have/ and /to Be/; which cannot
be conjugated without the /auxiliary Signs/, and without the reciprocal
Assistance of each other.

/To HAVE./

INDICATIVE MOOD.

/Present Tense./

/Sing./ I have; thou hast; he hath, /or/ has. /Plur./ We have; ye have;
they have.

/Preterimperfect Tense./

/Sing./ I had; thou hadst; he had. /Plur./ We had; ye had; they had.

/Preterperfect Tense./

/Sing./ I have had; thou hast had; he hath, /or/ has had. /Plur./ We
have had; ye have had; they have had.

/Preterpluperfect Tense./

/Sing./ I had had; thou hadst had; he had had. /Plur./ We had had; ye
had had; they had had.

/Future Tense./

/Sing./ I shall, or will have; thou shalt, or wilt have; he shall, /or/
will have. /Plur./ We shall, /or/ will have; ye shall, /or/ will have;
they shall, /or/ will have.

IMPERATIVE MOOD.

/Present/ and /Future/.

/Sing./ Let me have; do thou have, /or/ have thou; let him have. /Plur./
Let us have; do ye have, /or/ have ye; let them have.

CONJUNCTIVE MOOD.

/Present Tense./

/Sing./ I may, /or/ can have; thou may'st, /or/ can'st have; he may,
/or/ can have.

/Plur./ We may, /or/ can have; ye may, or can have; they may, /or/ can
have.

/Preterimperfect Tense./

/Sing./ I must, might, wou'd, cou'd, /or/ shou'd have; thou must,
might'st, woud'st, coud'st, /or/ shoud'st have; he must, might, wou'd,
cou'd, /or/ shou'd have. /Plur./ We must, might, wou'd, cou'd, /or/
shou'd have; ye must, might, wou'd, cou'd, /or/ shou'd have; they must,
might, wou'd, cou'd, /or/ shou'd have.

/Preterperfect Tense./

/Sing./ I must, might, wou'd, cou'd, /or/ shou'd have had; thou must,
might'st, wou'd'st, cou'd'st, /or/ shou'd'st have had; he must, might,
wou'd, cou'd, /or/ shou'd have had. /Plur./ We must, might, wou'd,
cou'd, /or/ shou'd have had; ye must, might, wou'd, cou'd, /or/ shou'd
have had; they must, might, wou'd, cou'd, /or/ shou'd have had.

/Preterpluperfect Tense./

/Sing./ I must, might, wou'd, cou'd, /or/ shou'd had had; thou must,
might'st, wou'd'st, cou'd'st, /or/ shou'd'st had had; he must, might,
wou'd, cou'd, /or/ shou'd had had; /Plur./ We must, might, wou'd, cou'd,
/or/ shou'd had had; ye must, might, wou'd, cou'd, /or/ shou'd had had;
they must, might, wou'd, cou'd, /or/ shou'd had had.

/Future Tense./

/Sing./ I shall, /or/ will have had; thou shalt, /or/ wilt have had; he
shall, /or/ will have had; /Plur./ We shall, /or/ will have had; ye
shall, /or/ will have had; they shall, /or/ will have had.

INFINITIVE MOOD.

/Present/ ---- to have /Perfect/ ---- to have had /Future/ ---- about to
have.

PARTICIPLES.

/Present/ ---- having /Preterperfect/ ---- having had.

/To BE./

INDICATIVE MOOD.

/Present Tense./

/Sing./ I am; thou art; he is. /Plur./ We are; ye are; they are.

/Preterimperfect Tense./

/Sing./ I was; thou wast; he was; /Plur./ We were; ye were; they were.

/Preterperfect Tense./

/Sing./ I have been; thou hast been; he hath been. /Plur./ We have been;
ye have been; they have been.

/Preterpluperfect Tense./

/Sing./ I had been; thou hadst been; he had been. /Plur./ We had been;
ye had been; they had been.

/Future Tense./

/Sing./ I shall, /or/ will be; thou shalt, /or/ wilt be; he shall, /or/
will be. /Plur./ We shall, /or/ will be; ye shall, /or/ will be; they
shall, /or/ will be.

IMPERATIVE MOOD.

/Present/ and /Future/.

/Sing./ Let me be; do thou be, /or/ be thou; let him be. /Plur./ Let us
be; do ye be, /or/ be ye; let them be.

CONJUNCTIVE MOOD.

/Present Tense./

/Sing./ I may, /or/ can be; thou may'st, /or/ canst be; he may, /or/ can
be. /Plur./ We may, /or/ can be; ye may, /or/ can be; they may, /or/ can
be.

/Preterimperfect Tense./

/Sing./ I must, might, wou'd, cou'd, /or/ shou'd be; thou must,
might'st, wou'd'st, cou'd'st, /or/ shou'd'st be; he must, might, wou'd,
cou'd, /or/ shou'd be. /Plur./ We must, might, wou'd, cou'd, /or/ shou'd
be; ye must, might, wou'd, cou'd, /or/ shou'd be; they must, might,
wou'd, cou'd, /or/ shou'd be.

/Preterperfect Tense./

/Sing./ I must, might, wou'd, cou'd, /or/ shou'd have been; thou must,
might'st, wou'd'st, cou'd'st, /or/ shou'd'st have been; he must, might,
wou'd, cou'd, /or/ shou'd, have been. /Plur./ We must, might, wou'd,
cou'd, /or/ shou'd have been; ye must, might, wou'd, cou'd, /or/ shou'd
have been; they must, might, wou'd cou'd, /or/ shou'd have been.

/Preterpluperfect Tense./

/Sing./ I must, might, wou'd, cou'd, /or/ shou'd have had been; thou
must, might'st, wou'd'st, cou'd'st, /or/ shou'd'st, have had been; he
must, might, wou'd, cou'd, /or/ shou'd have had been. /Plur./ We must,
might, wou'd, cou'd, /or/ shou'd have had been; ye must, might, wou'd,
cou'd, /or/ shou'd have had been; they must, might, wou'd, cou'd, /or/
shou'd have had been.

/Future Tense./

/Sing./ I shall, /or/ will have been; thou shalt, /or/ wilt have been;
he shall /or/ will have been. /Plur./ We shall, /or/ will have been; ye
shall, /or/ will have been; they shall, /or/ will have been.

INFINITIVE MOOD.

/Present/ ---- to be /Preterperfect/ ---- to have been /Future/ ----
about to be.

PARTICIPLES.

/Present/ ---- being /Preterperfect/ ---- having been.

/Of/ REGULAR VERBS.

Regular /Verbs/ are those that are /conjugated/ by some established
Rules.

The /Termination/ of the /Infinitive Mood Present Tense, of the Verb
Active, in regular Verbs/, is always the same as the /first Person/ of
the /Indicative Mood Present Tense singular/; as /to love, I love/.

The /Termination/ of the /second Person Singular/ is formed out of the
/first/ by adding /st/ or /est/; as _I love, thou loves_t; /I read, thou
readest/.

The /Termination/ of the /third Person singular/ is formed out of the
/first/ by adding /th/ or /eth/; as /I love, he loveth, I read, he
readeth/; or only by adding /s/; as /he loves, he reads/.

The /Termination/ of the /first Person Preterimperfect Tense singular/,
is formed out of the /first Person Present Tense singular/ by adding the
Syllable /ed/; as /I love, I loved/.

The /Termination/ of the /Participle Present of the Verb Active/, is
always formed out of the /first Person Present/ by adding the Syllable
/ing/; as /I love/, /loving/.

The /Termination/ of the /Preterimperfect, the Preterperfect, and the
Preterpluperfect of the Indicative Mood; and the Preterperfect, the
Preterpluperfect and the Future of the Conjunctive, and the Participle
Passive/ is in regular Verbs the same; as /I loved, I have loved, I had
loved, I may have loved, I might have loved, I shall have loved, I am
loved/. And

The /Termination/ of every other /Tense, Number or Person/, is the same
with the /Infinitive/.

/Of a/ VERB ACTIVE.

A Verb /Active regular/ is conjugated by the /auxiliary Signs, the
auxiliary Verbs/, and the general Rules foregoing.

/To LOVE./

INDICATIVE MOOD.

/Present Tense./

/Sing./ I love, /or/ do love; thou lovest, /or/ dost love; he loveth,
/or/ loves, /or/ doth love. /Plur./ We love, /or/ do love; ye love, /or/
do love; they love, /or/ do love.

/Preterimperfect Tense./

/Sing./ I loved, /or/ did love; thou loved'st, /or/ did'st love; he
loved, /or/ did love. /Plur./ we loved, /or/ did love; ye loved, /or/
did love; they loved, /or/ did love.

/Preterperfect Tense./

/Sing./ I have loved; thou hast loved; he hath loved, /or/ has loved.
/Plur./ We have loved; ye have loved; they have loved.

/Preterpluperfect Tense./

/Sing./ I had loved; thou hadst loved; he had loved. /Plur./ We had
loved; ye had loved; they had loved.

/Future Tense./

/Sing./ I shall, /or/ will love; thou shalt, /or/ wilt love; he shall,
/or/ will love. /Plur./ We shall, /or/ will love; ye shall, /or/ will
love; they shall, /or/ will love.

IMPERATIVE MOOD.

/Present/ and /Future/.

/Sing./ Let me love; do thou love, /or/ love thou; let him love. /Plur./
Let us love; do ye love, /or/ love ye; let them love.

CONJUNCTIVE MOOD.

/Present Tense./

/Sing./ I may, /or/ can love; thou may'st, or can'st love; he may, /or/
can love. /Plur./ We may, /or/ can love; ye may, /or/ can love; they
may, /or/ can love.

/Preterimperfect Tense./

/Sing./ I must, might, wou'd, cou'd, /or/ shou'd love; thou must,
might'st, wou'd'st, cou'd'st, /or/ shou'd'st love; he must, might,
wou'd, cou'd, /or/ shou'd love. /Plur./ We must, might, wou'd, cou'd,
/or/ shou'd love; ye must, might, wou'd, cou'd, /or/ shou'd love; they
must, might, wou'd, cou'd, /or/ shou'd love.

/Preterperfect Tense./

/Sing./ I must, might, wou'd, cou'd, /or/ shou'd have loved; thou must,
might'st, wou'd'st, cou'd'st, /or/ shou'd'st have loved; he must, might,
wou'd, cou'd, /or/ shou'd have loved. /Plur./ We must, might, wou'd,
cou'd, /or/ shou'd have loved; ye must, might, wou'd, cou'd, /or/ shou'd
have loved; they must, might, wou'd, cou'd, /or/ shou'd have loved.

/Preterpluperfect Tense./

/Sing./ I must, might, wou'd, cou'd, /or/ shou'd have had loved; thou
must, might'st, wou'd'st, cou'd'st, /or/ shou'd'st have had loved; he
must, might, wou'd, cou'd, /or/ shou'd have had loved. /Plur./ We must,
might, wou'd, cou'd, /or/ shou'd have had loved; ye must, might, wou'd,
cou'd, /or/ shou'd have had loved; they must, might, wou'd, cou'd, /or/
shou'd have had loved.

/Future Tense./

/Sing./ I shall, /or/ will have loved; thou shalt, /or/ wilt have loved;
he shall, or will have loved. /Plur./ We shall, /or/ will have loved; ye
shall, /or/ will have loved; they shall, /or/ will have loved.

INFINITIVE MOOD.

/Present/ ---- to love /Preterperfect/ ---- to have loved /Future/ ----
about to love.

PARTICIPLES.

/Present/ ---- loving /Preterperfect/ ---- having loved.

/Of a/ VERB PASSIVE.

The /Verb Passive/ is nothing more than the /Participle Passive/ joined
to the /Auxiliary Verb to be/; as

INDICATIVE MOOD.

/Present Tense/ I am loved; /&c./ /Preterimperfect/ I was loved; /&c./
/Preterperfect/ I have been loved; /&c./ /Preterpluperfect/ I had been
loved; /&c./ /Future/ I shall or will be loved; /&c./

IMPERATIVE MOOD.

/Present/ and /Future/. Let me be loved /&c./

CONJUNCTIVE MOOD.

/Present Tense./

/Sing./ I may, /or/ can be loved; thou /&c./

/Preterimperfect Tense./

/Sing./ I must, might, wou'd, cou'd, /or/ shou'd be loved; thou /&c./

/Preterperfect Tense./

/Sing./ I must, might, wou'd, cou'd, /or/ shou'd have been loved; thou
/&c./

/Preterpluperfect Tense./

/Sing./ I must, might, wou'd, cou'd, /or/ shou'd have had been loved;
thou /&c/.

/Future Tense./

/Sing./ I shall, /or/ will have been loved; thou /&c./

INFINITIVE MOOD.

/Present/ ---- to be loved /Preterperfect/ ---- to have been loved
/Future/ ---- about to be loved.

PARTICIPLES.

/Present/ ---- being loved /Preterperfect/ ---- having been loved.

/Of a/ PARTICIPLE.

A Participle is a /Part of Speech/, which partaketh of a /Verb/ and a
/Noun/. When it has a Relation to Time it may be considered as a /Verb/;
but when it is joined to a /Substantive/ or admits of /Comparison/, it
may be considered as an /Adjective/.

When the /termination/ of the /Participle Passive/ is not formed by
adding the Syllable /ed/ to the /first Person/ of the /Indicative Mood
Present Tense Singular/; or when the /Termination/ of the /Participle
Passive/ differs from the /Termination of the Preter Tenses/, the /Verb/
becomes /irregular/; but in all other Respects is conjugated as the
regular Verb; as I abide, thou abidest, &c.

/Pres. Tense./ /Preter./ /Participle Passive./

#+begin_example
 Abide           Abode               Abode
 Bite            Bit                 Bitten
 Catch           Caught              Catched
 Do              Did                 Done
 Eat             Eat                 Eaten
 Fall            Fell                Fallen
 Get             Got                 Gotten
 Hold            Held                Holden
 Know            Knew                Known
 Lie             Lay                 Laid
 Make            Made                Made
 Rise            Rose                Risen
 Shine           Shone               Shined
 Tread           Trod                Trodden
 Weave           Wove                Woven
 _&c._           _&c._               _&c._
#+end_example

To these may be added the /Auxiliary Verbs/ ---- /To Have, and to Be/.

/Of an/ ADVERB.

An Adverb is a /Part of Speech/ joined to a /Verb/, a /Noun
Substantive/, an /Adjective/ or /Participle/, and sometimes to another
/Adverb/, to express the Manner or Circumstance of the Thing signified;
as /he speaks properly/, /an orderly Man/, /truly good/, /extreamly
loving/, /very devoutly/.

Adverbs are very numerous, and have Relation to

Time; as /now/, /lately/, /always/.

Place; as /here/, /there/, /no-where/.

Order; as /by Turns/, /abreast/, /orderly/.

Quantity; as /enough/, /more/, /entirely/.

Number; as /once/, /twice/, /thrice/.

Dobting; as /perhaps/, /may be/, /peradventure/.

Asking; as /why?/ /whence?/ /wherefore?/.

Affirmation; as /yes/, /indeed/, /certainly/.

Negation; as /no/, /never/, /not at all/.

Comparison; as /more/, /less/, /likewise/.

Quality; as /justly/, /prudently/, /indifferently/.

/Of a/ CONJUNCTION.

A Conjunction is /a Part of Speech/, which serves to connect and join
the several Parts of a Discourse together, and is of various Kinds.

Copulative; /as and/, /also/, /moreover/.

Disjunctive; /as or/, /neither/, /whether/.

Adversative; /as but/, /yet/, /notwithstanding/.

Conditional; /as if/, /unless/, /provided/.

Casual; /as for/, /because/, /forasmuch/.

Conclusive; /as then/, /so that/, /therefore/.

/Of a/ PREPOSITION.

A Preposition is /a Part of Speech/, that serves to express the
particular Relation and Circumstance of some other /Part of Speech/, and
is either used in /Apposition/, as /in Heaven/; or in /Composition/, as
/Invisible/.

PREPOSITIONS /used in/ APPOSITION.

Above between of about betwixt on after beyond over against by through
among for throughout amongst from towards at in under before into unto
behind near upon beneath near to with below nigh within beside nigh to
without.

PREPOSITIONS /used in/ COMPOSITION.

A-base ap-point ab-use as-certain abs-tract at-taint ac-commodate
be-friend ad-apt circum-ambient af-fix co-adjutor after-noon com-pound
amphi-theatre com-plot ante-date con-strain anti-christ contra-diction
an-archy counter-balance. de-camp op-pression Dis-appoint over-reach
dif-fusive out-landish di-minish per-form e-mission post-master em-brace
pre-eminence en-close preter-natural es-say pro-long ex-terminate
re-gain extra-ordinary retro-grade for-bear sub-join fore-see super-fine
im-perfect trans-migration in-glorious un-worthy inter-view
under-written intro-duction up-right ob-noxious with-draw off-spring
/&c./, /&c./, /&c./

/Of an/ INTERJECTION.

An Interjection /is a Part of Speech/, that serves to express some
sudden Motion or Passion of the Mind, transported with the Sensation of
Pleasure or Pain.

Of Pleasure; as, /O brave!/ /O Heavens! O Joy!/

Of Pain; as /Alas! O my God! O Lord!/

INTERJECTIONS /of a/ lower Order.

Of Caution; as, /hold! take Care!/

Of Admiration; as, /see! look! behold!/

Of Aversion; as, /fie! away you Fool!/

Of Silence; as, /be still! Silence!/

/Of/ SYNTAX.

Syntax is the Manner of constructing one Word with another prescribed by
the /Rules of/ GRAMMAR.

RULE 1st.

The Article /a/ is usually placed before a Word that begins with a
/Consonant/, the Article /an/ before a Word that begins with a /Vowel/,
and either /a/ or /an/ before a Word that begins with an /h/; and the
Article /the/, before a Word that begins either with a /Vowel/ or a
/Consonant/; as, /a Christian/, /an Infidel/, /a Heathen/, or /an
Heathen/; /the Christian/, /the Infidel/, /the Heathen/.

RULE 2d.

A Noun /Substantive/ is usually placed after its /Noun Adjective/; as
the /Second Chapter/, a /great Man/. But sometimes for the Sake of
greater Distinction the /Adjective/ is placed after, with the Article
/the/ before it, as /George the Second/, /Peter the Great/. In /Poetry/
the /Adjective/ is placed either before or after its /Substantive/
indifferently, as the Versification requires it.

RULE 3d.

All /Nouns and Pronouns/ are of the /third Person/ except /I and we/,
which are of the /first Person/, and /Thou, you and ye/, which are of
the /Second Person/; and except the /Relative Pronouns/ which are always
of the /same Person/ with the /Personal Pronoun/ to which they relate;
as /I love, thou lovest, he loveth; I who love, Thou who lovest, he who
loveth/.

RULE 4th.

The /prefix Pronouns/, /I, we, thou, you, ye, he, she, they, who/, are
usually placed before the /Verb/; and the /Subsequent Pronouns/, /me,
us, thee, him, her, them, whom/, are usually placed after; as /I love
the Dog, the Dog loves me/. But when a /Question/ is asked, or when the
/Verb/ is of the /Imperative Mood/, or in short Sentences, the /prefix
Pronouns/ are usually placed after; as /lovest thou me? love thou
thyself, said he, said they/.

RULE 5th.

When a Question is asked, and the /Verb/ has an /Auxiliary Sign/, or an
/Auxiliary Verb/, the /governing Noun/ or /Pronoun/ is placed
immediately after such /Auxiliary/; as /does the Sun shine? has he
washed his Hands?/ And when the /Verb/ has two or more /Auxiliaries/,
the /Noun or Pronoun/ is placed after the first; as /have I been taught?
Cou'd the Truth have been known?/

RULE 6th.

The /Verb/ agrees with its /governing Noun/, /Pronoun Personal/, or
/Pronoun Relative/, in /Number/ and /Person/; as /the Birds sing/, /thou
lovest/, /he who loveth/.

RULE 7th.

A NOUN of /Multitude/ may have a /Verb/ either /Singular/ or /Plural/;
as /the People is mad/, or /the People are mad/.

But if a /Substantive/ of the same Signification follows, that is not a
/Noun of Multitude/, then the /Verb/ is always Plural; as we do not say
/the People is a mad Man/, but /the People are mad Men/.

RULE 8th.

Two or more /Nouns/ or /Pronouns Singular/, will have a /Verb Plural/;
as /the Dog and Cat are very loving/. But when two or more /Substantives
Singular/ signify the same /Thing/ or /Person/, or when the
/Preposition/ OF intervenes, the /Verb/ is always /Singular/; as /the
River Severn is Navigable./ /William the Conqueror was a great Man./
/This System of Grammar is compendious/.

RULE 9th.

The /subsequent Pronouns/ are usually placed after /Prepositions and
Interjections/; as /of me, to us, for thee, with her, from them, against
whom, O me!/

/Of the/ POINTS /or/ PAUSES.

The /Points/ or /Pauses/ have a Sort of musical Proportion.

The /Period/ is marked thus (.)----Its /Time/ is equal to two /Colons/
and is never placed but at the End of a Sentence, the Sense of which is
perfect and compleat; as /By me Kings reign, and Princes decree
Justice./

The /Colon/ is marked thus (:) ---- Its /Time/ is equal to two
/Semicolons/, and is placed where the Sense seems to be perfect and
compleat; but to which notwithstanding something may still be added; as
/give Instruction to a wise Man, and he will be yet wiser: Teach a just
Man and he will increase in Learning/.

The /Semicolon/ is marked thus (;) ---- its /Time/ is equal to two
/Commas/, and is placed where the Sense is less compleat than the
/Colon/, and more compleat than the /Comma/; as /a wise Man's Heart is
at his right Hand; but a Fool's Heart is at his left/.

The /Comma/ is marked thus (,) ---- It is the last and least /Pause/ or
/Time/ that is made use of, and serves to distinguish the simple Numbers
of a /Period/; as /arise, my Friend, and come away/.

/Of the other NOTES or CHARACTERS./

A Note of /Interrogation/ (?) is used when a Question is asked; as /who
comes there?/

A Note of /Admiration/ (!) is used after /Interjections/ or /short
Sentences/ to express our Wonder and Surprize; as /O!/ /O LORD!/

A Parenthesis (/rarely made use of by a good Writer/) is used to inclose
one Sentence within another.

The /Paragraph/ is marked thus (¶) and denotes the beginning of a new
Discourse.

An (') /Apostrophe/ is used when some Part of a Word is left out; as
/Alexander's Horse/, for /Alexander his Horse/.

A /Hyphen/ (-) is used to join together two Words, as /Foot-stool/,
/&c./ and is used also when part of a Word is written in one Line, and
part in another.

The /Caret/ is marked thus, (^) to shew where the Words in any Sentence
that are left out, shou'd come in; as

#+begin_example
       is
#+end_example

/the Lady ^ beautiful./

The /Subdivision/, or part of a Chapter is marked usually thus, Sec..

The /Index/ points to some remarkable Passage thus, Index finger,
pointing to the right].

A /Quotation/ is a double /Comma/ reverse and set against some Lines on
the left side of a /Page/, to shew that they are quoted from another
/Author/, thus, “.

The /Notes/ that refer to the /Margin/ are an /Asterisk/ made thus, *,
an /Obelisk/ thus, [Dagger symbol], also thus, ||.

Besides these there are /literal Characters/, /numeral Characters/, and
/Abbreviations/, the Knowledge of which is not so easily to be acquired
by GRAMMAR /Rules/, as by diligent Observation and Experience.

/The/ END.

End of Project Gutenberg's A Short System of English Grammar, by Henry
Bate

*** END OF THE PROJECT GUTENBERG EBOOK A SHORT SYSTEM OF ENGLISH GRAMMAR
***

Updated editions will replace the previous one---the old editions will
be renamed.

Creating the works from print editions not protected by U.S. copyright
law means that no one owns a United States copyright in these works, so
the Foundation (and you!) can copy and distribute it in the United
States without permission and without paying copyright royalties.
Special rules, set forth in the General Terms of Use part of this
license, apply to copying and distributing Project Gutenberg™ electronic
works to protect the PROJECT GUTENBERG™ concept and trademark. Project
Gutenberg is a registered trademark, and may not be used if you charge
for an eBook, except by following the terms of the trademark license,
including paying royalties for use of the Project Gutenberg trademark.
If you do not charge anything for copies of this eBook, complying with
the trademark license is very easy. You may use this eBook for nearly
any purpose such as creation of derivative works, reports, performances
and research. Project Gutenberg eBooks may be modified and printed and
given away---you may do practically ANYTHING in the United States with
eBooks not protected by U.S. copyright law. Redistribution is subject to
the trademark license, especially commercial redistribution.

START: FULL LICENSE

THE FULL PROJECT GUTENBERG™ LICENSE

PLEASE READ THIS BEFORE YOU DISTRIBUTE OR USE THIS WORK

To protect the Project Gutenberg™ mission of promoting the free
distribution of electronic works, by using or distributing this work (or
any other work associated in any way with the phrase "Project
Gutenberg"), you agree to comply with all the terms of the Full Project
Gutenberg License available with this file or online at
www.gutenberg.org/license.

Section 1. General Terms of Use and Redistributing Project Gutenberg
electronic works

1.A. By reading or using any part of this Project Gutenberg electronic
work, you indicate that you have read, understand, agree to and accept
all the terms of this license and intellectual property
(trademark/copyright) agreement. If you do not agree to abide by all the
terms of this agreement, you must cease using and return or destroy all
copies of Project Gutenberg electronic works in your possession. If you
paid a fee for obtaining a copy of or access to a Project Gutenberg
electronic work and you do not agree to be bound by the terms of this
agreement, you may obtain a refund from the person or entity to whom you
paid the fee as set forth in paragraph 1.E.8.

1.B. "Project Gutenberg" is a registered trademark. It may only be used
on or associated in any way with an electronic work by people who agree
to be bound by the terms of this agreement. There are a few things that
you can do with most Project Gutenberg electronic works even without
complying with the full terms of this agreement. See paragraph 1.C
below. There are a lot of things you can do with Project Gutenberg
electronic works if you follow the terms of this agreement and help
preserve free future access to Project Gutenberg electronic works. See
paragraph 1.E below.

1.C. The Project Gutenberg Literary Archive Foundation ("the Foundation"
or PGLAF), owns a compilation copyright in the collection of Project
Gutenberg electronic works. Nearly all the individual works in the
collection are in the public domain in the United States. If an
individual work is unprotected by copyright law in the United States and
you are located in the United States, we do not claim a right to prevent
you from copying, distributing, performing, displaying or creating
derivative works based on the work as long as all references to Project
Gutenberg are removed. Of course, we hope that you will support the
Project Gutenberg mission of promoting free access to electronic works
by freely sharing Project Gutenberg works in compliance with the terms
of this agreement for keeping the Project Gutenberg name associated with
the work. You can easily comply with the terms of this agreement by
keeping this work in the same format with its attached full Project
Gutenberg License when you share it without charge with others.

1.D. The copyright laws of the place where you are located also govern
what you can do with this work. Copyright laws in most countries are in
a constant state of change. If you are outside the United States, check
the laws of your country in addition to the terms of this agreement
before downloading, copying, displaying, performing, distributing or
creating derivative works based on this work or any other Project
Gutenberg work. The Foundation makes no representations concerning the
copyright status of any work in any country other than the United
States.

1.E. Unless you have removed all references to Project Gutenberg:

1.E.1. The following sentence, with active links to, or other immediate
access to, the full Project Gutenberg License must appear prominently
whenever any copy of a Project Gutenberg work (any work on which the
phrase "Project Gutenberg" appears, or with which the phrase "Project
Gutenberg" is associated) is accessed, displayed, performed, viewed,
copied or distributed:

#+begin_example
This eBook is for the use of anyone anywhere in the United States and most
other parts of the world at no cost and with almost no restrictions
whatsoever. You may copy it, give it away or re-use it under the terms
of the Project Gutenberg™ License included with this eBook or online
at www.gutenberg.org. If you
are not located in the United States, you will have to check the laws
of the country where you are located before using this eBook.
#+end_example

1.E.2. If an individual Project Gutenberg electronic work is derived
from texts not protected by U.S. copyright law (does not contain a
notice indicating that it is posted with permission of the copyright
holder), the work can be copied and distributed to anyone in the United
States without paying any fees or charges. If you are redistributing or
providing access to a work with the phrase "Project Gutenberg"
associated with or appearing on the work, you must comply either with
the requirements of paragraphs 1.E.1 through 1.E.7 or obtain permission
for the use of the work and the Project Gutenberg trademark as set forth
in paragraphs 1.E.8 or 1.E.9.

1.E.3. If an individual Project Gutenberg electronic work is posted with
the permission of the copyright holder, your use and distribution must
comply with both paragraphs 1.E.1 through 1.E.7 and any additional terms
imposed by the copyright holder. Additional terms will be linked to the
Project Gutenberg License for all works posted with the permission of
the copyright holder found at the beginning of this work.

1.E.4. Do not unlink or detach or remove the full Project Gutenberg
License terms from this work, or any files containing a part of this
work or any other work associated with Project Gutenberg.

1.E.5. Do not copy, display, perform, distribute or redistribute this
electronic work, or any part of this electronic work, without
prominently displaying the sentence set forth in paragraph 1.E.1 with
active links or immediate access to the full terms of the Project
Gutenberg License.

1.E.6. You may convert to and distribute this work in any binary,
compressed, marked up, nonproprietary or proprietary form, including any
word processing or hypertext form. However, if you provide access to or
distribute copies of a Project Gutenberg work in a format other than
"Plain Vanilla ASCII" or other format used in the official version
posted on the official Project Gutenberg website (www.gutenberg.org),
you must, at no additional cost, fee or expense to the user, provide a
copy, a means of exporting a copy, or a means of obtaining a copy upon
request, of the work in its original "Plain Vanilla ASCII" or other
form. Any alternate format must include the full Project Gutenberg
License as specified in paragraph 1.E.1.

1.E.7. Do not charge a fee for access to, viewing, displaying,
performing, copying or distributing any Project Gutenberg works unless
you comply with paragraph 1.E.8 or 1.E.9.

1.E.8. You may charge a reasonable fee for copies of or providing access
to or distributing Project Gutenberg electronic works provided that:

#+begin_example
• You pay a royalty fee of 20% of the gross profits you derive from
    the use of Project Gutenberg works calculated using the method
    you already use to calculate your applicable taxes. The fee is owed
    to the owner of the Project Gutenberg trademark, but he has
    agreed to donate royalties under this paragraph to the Project
    Gutenberg Literary Archive Foundation. Royalty payments must be paid
    within 60 days following each date on which you prepare (or are
    legally required to prepare) your periodic tax returns. Royalty
    payments should be clearly marked as such and sent to the Project
    Gutenberg Literary Archive Foundation at the address specified in
    Section 4, “Information about donations to the Project Gutenberg
    Literary Archive Foundation.”

• You provide a full refund of any money paid by a user who notifies
    you in writing (or by e-mail) within 30 days of receipt that s/he
    does not agree to the terms of the full Project Gutenberg™
    License. You must require such a user to return or destroy all
    copies of the works possessed in a physical medium and discontinue
    all use of and all access to other copies of Project Gutenberg™
    works.

• You provide, in accordance with paragraph 1.F.3, a full refund of
    any money paid for a work or a replacement copy, if a defect in the
    electronic work is discovered and reported to you within 90 days of
    receipt of the work.

• You comply with all other terms of this agreement for free
    distribution of Project Gutenberg™ works.
#+end_example

1.E.9. If you wish to charge a fee or distribute a Project Gutenberg™
electronic work or group of works on different terms than are set forth
in this agreement, you must obtain permission in writing from the
Project Gutenberg Literary Archive Foundation, the manager of the
Project Gutenberg™ trademark. Contact the Foundation as set forth in
Section 3 below.

1.F.

1.F.1. Project Gutenberg volunteers and employees expend considerable
effort to identify, do copyright research on, transcribe and proofread
works not protected by U.S. copyright law in creating the Project
Gutenberg™ collection. Despite these efforts, Project Gutenberg™
electronic works, and the medium on which they may be stored, may
contain "Defects," such as, but not limited to, incomplete, inaccurate
or corrupt data, transcription errors, a copyright or other intellectual
property infringement, a defective or damaged disk or other medium, a
computer virus, or computer codes that damage or cannot be read by your
equipment.

1.F.2. LIMITED WARRANTY, DISCLAIMER OF DAMAGES - Except for the "Right
of Replacement or Refund" described in paragraph 1.F.3, the Project
Gutenberg Literary Archive Foundation, the owner of the Project
Gutenberg™ trademark, and any other party distributing a Project
Gutenberg™ electronic work under this agreement, disclaim all liability
to you for damages, costs and expenses, including legal fees. YOU AGREE
THAT YOU HAVE NO REMEDIES FOR NEGLIGENCE, STRICT LIABILITY, BREACH OF
WARRANTY OR BREACH OF CONTRACT EXCEPT THOSE PROVIDED IN PARAGRAPH 1.F.3.
YOU AGREE THAT THE FOUNDATION, THE TRADEMARK OWNER, AND ANY DISTRIBUTOR
UNDER THIS AGREEMENT WILL NOT BE LIABLE TO YOU FOR ACTUAL, DIRECT,
INDIRECT, CONSEQUENTIAL, PUNITIVE OR INCIDENTAL DAMAGES EVEN IF YOU GIVE
NOTICE OF THE POSSIBILITY OF SUCH DAMAGE.

1.F.3. LIMITED RIGHT OF REPLACEMENT OR REFUND - If you discover a defect
in this electronic work within 90 days of receiving it, you can receive
a refund of the money (if any) you paid for it by sending a written
explanation to the person you received the work from. If you received
the work on a physical medium, you must return the medium with your
written explanation. The person or entity that provided you with the
defective work may elect to provide a replacement copy in lieu of a
refund. If you received the work electronically, the person or entity
providing it to you may choose to give you a second opportunity to
receive the work electronically in lieu of a refund. If the second copy
is also defective, you may demand a refund in writing without further
opportunities to fix the problem.

1.F.4. Except for the limited right of replacement or refund set forth
in paragraph 1.F.3, this work is provided to you 'AS-IS', WITH NO OTHER
WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
WARRANTIES OF MERCHANTABILITY OR FITNESS FOR ANY PURPOSE.

1.F.5. Some states do not allow disclaimers of certain implied
warranties or the exclusion or limitation of certain types of damages.
If any disclaimer or limitation set forth in this agreement violates the
law of the state applicable to this agreement, the agreement shall be
interpreted to make the maximum disclaimer or limitation permitted by
the applicable state law. The invalidity or unenforceability of any
provision of this agreement shall not void the remaining provisions.

1.F.6. INDEMNITY - You agree to indemnify and hold the Foundation, the
trademark owner, any agent or employee of the Foundation, anyone
providing copies of Project Gutenberg™ electronic works in accordance
with this agreement, and any volunteers associated with the production,
promotion and distribution of Project Gutenberg™ electronic works,
harmless from all liability, costs and expenses, including legal fees,
that arise directly or indirectly from any of the following which you do
or cause to occur: (a) distribution of this or any Project Gutenberg
work, (b) alteration, modification, or additions or deletions to any
Project Gutenberg work, and (c) any Defect you cause.

Section 2. Information about the Mission of Project Gutenberg

Project Gutenberg is synonymous with the free distribution of electronic
works in formats readable by the widest variety of computers including
obsolete, old, middle-aged and new computers. It exists because of the
efforts of hundreds of volunteers and donations from people in all walks
of life.

Volunteers and financial support to provide volunteers with the
assistance they need are critical to reaching Project Gutenberg's goals
and ensuring that the Project Gutenberg collection will remain freely
available for generations to come. In 2001, the Project Gutenberg
Literary Archive Foundation was created to provide a secure and
permanent future for Project Gutenberg and future generations. To learn
more about the Project Gutenberg Literary Archive Foundation and how
your efforts and donations can help, see Sections 3 and 4 and the
Foundation information page at www.gutenberg.org.

Section 3. Information about the Project Gutenberg Literary Archive
Foundation

The Project Gutenberg Literary Archive Foundation is a non-profit
501(c)(3) educational corporation organized under the laws of the state
of Mississippi and granted tax exempt status by the Internal Revenue
Service. The Foundation's EIN or federal tax identification number is
64-6221541. Contributions to the Project Gutenberg Literary Archive
Foundation are tax deductible to the full extent permitted by U.S.
federal laws and your state's laws.

The Foundation's business office is located at 41 Watchung Plaza #516,
Montclair NJ 07042, USA, +1 (862) 621-9288. Email contact links and up
to date contact information can be found at the Foundation's website and
official page at www.gutenberg.org/contact

Section 4. Information about Donations to the Project Gutenberg Literary
Archive Foundation

Project Gutenberg™ depends upon and cannot survive without widespread
public support and donations to carry out its mission of increasing the
number of public domain and licensed works that can be freely
distributed in machine-readable form accessible by the widest array of
equipment including outdated equipment. Many small donations ($1 to
$5,000) are particularly important to maintaining tax exempt status with
the IRS.

The Foundation is committed to complying with the laws regulating
charities and charitable donations in all 50 states of the United
States. Compliance requirements are not uniform and it takes a
considerable effort, much paperwork and many fees to meet and keep up
with these requirements. We do not solicit donations in locations where
we have not received written confirmation of compliance. To SEND
DONATIONS or determine the status of compliance for any particular state
visit www.gutenberg.org/donate.

While we cannot and do not solicit contributions from states where we
have not met the solicitation requirements, we know of no prohibition
against accepting unsolicited donations from donors in such states who
approach us with offers to donate.

International donations are gratefully accepted, but we cannot make any
statements concerning tax treatment of donations received from outside
the United States. U.S. laws alone swamp our small staff.

Please check the Project Gutenberg web pages for current donation
methods and addresses. Donations are accepted in a number of other ways
including checks, online payments and credit card donations. To donate,
please visit: www.gutenberg.org/donate.

Section 5. General Information About Project Gutenberg electronic works

Professor Michael S. Hart was the originator of the Project Gutenberg
concept of a library of electronic works that could be freely shared
with anyone. For forty years, he produced and distributed Project
Gutenberg eBooks with only a loose network of volunteer support.

Project Gutenberg eBooks are often created from several printed
editions, all of which are confirmed as not protected by copyright in
the U.S. unless a copyright notice is included. Thus, we do not
necessarily keep eBooks in compliance with any particular paper edition.

Most people start at our website which has the main PG search facility:
www.gutenberg.org.

This website includes information about Project Gutenberg, including how
to make donations to the Project Gutenberg Literary Archive Foundation,
how to help produce our new eBooks, and how to subscribe to our email
newsletter to hear about new eBooks.
