Google

This is a digital copy of a book that was preserved for generations on
library shelves before it was carefully scanned by Google as part of a
project

to make the world's books discoverable online.

It has survived long enough for the copyright to expire and the book to
enter the public domain. A public domain book is one that was never
subject

to copyright or whose legal copyright term has expired. Whether a book
is in the public domain may vary country to country. Public domain books

are our gateways to the past, representing a wealth of history, culture
and knowledge that's often difficult to discover.

Marks, notations and other maiginalia present in the original volume
will appear in this file - a reminder of this book's long journey from
the

publisher to a library and finally to you.

Usage guidelines

Google is proud to partner with libraries to digitize public domain
materials and make them widely accessible. Public domain books belong to
the public and we are merely their custodians. Nevertheless, this work
is expensive, so in order to keep providing tliis resource, we liave
taken steps to prevent abuse by commercial parties, including placing
technical restrictions on automated querying. We also ask that you:

- Make non-commercial use of the files We designed Google Book Search
  for use by individuals, and we request that you use these files for
  personal, non-commercial purposes.

- Refrain fivm automated querying Do not send automated queries of any
  sort to Google's system: If you are conducting research on machine
  translation, optical character recognition or other areas where access
  to a large amount of text is helpful, please contact us. We encourage
  the use of public domain materials for these purposes and may be able
  to help.

- Maintain attributionTht GoogXt "watermark" you see on each file is
  essential for in forming people about this project and helping them
  find additional materials through Google Book Search. Please do not
  remove it.

- Keep it legal Whatever your use, remember that you are responsible for
  ensuring that what you are doing is legal. Do not assume that just
  because we believe a book is in the public domain for users in the
  United States, that the work is also in the public domain for users in
  other countries. Whether a book is still in copyright varies from
  country to country, and we can't offer guidance on whether any
  specific use of any specific book is allowed. Please do not assume
  that a book's appearance in Google Book Search means it can be used in
  any manner anywhere in the world. Copyright infringement liabili^ can
  be quite severe.

About Google Book Search

Google's mission is to organize the world's information and to make it
universally accessible and useful. Google Book Search helps readers
discover the world's books while helping authors and publishers reach
new audiences. You can search through the full text of this book on the
web

at |http: //books .google .com/I

imiip

600083300K

/ /

 

THE

ELEMENTS OF GRAMMAR TAUGHT IN ENGLISH;

WITH QUESTIONS.

BY

THE REV. EDWARD THRING, M.A. 

FELLOW OF KIN^^{jToOLLBOB}ilfAMBBlDOE.

y

CTamitil^st : MACMILLAN & Co. 

enHon : GEO. BELL; ^intturgfl : EDMONSTON & DOUGLAS; BvUin : HODGES &
SMITH; OIssgotD : JAS. MACLEHOSE.

1861. [@1861] 

J^z, a. ^/.

PREFACE.

THIS little Work is strictly intended for teachers and learners. The
effort has heen to lay jdown the hroad, beaten, every-day path,
carefully avoiding digressions into the bye- ways and eccen- tricities
of language. For my object was not to make a complete Grammar, or a
History of Language, which is useless for learners, but to teach Grammar
up to a certain point, steadily keeping in mind the class of persons for
whom the work is intended. If saiy one will take the trouble to follow
in order the course marked out for him, he will certainly know in time
the main principles and practice of Grammar ; the matter being reduced
to a mere question of time, and not of intelligence. And this is no
visionary prospect : this Work took its rise from question- ings in
National Schools, and the whole of the first part is merely the writing
out in order the answers to questions which have been used already with
success. There can be tvo ^qvsJc»» “^{oa} *^a.

iv PREFACE.

our Classical Schools also the average attainments would be much
greater, if the lower classes were grounded on English Grammar, and
taught to compare Latin and Greek with English, to decide in all
discrepancies which method of speech is most natural, that is, most in
accordance with the original object of communicating thought, and also
to explain, when the natural arrange- ment is not followed, how the gain
in deamess or emphasis of that arrangement would be more than
counterbalanced by the loss in some other way. There is no subject which
does not become interesting when thus hinged on to common life and
common practice. At all events, if this little Book shall enable any to
test their ground, and give an intelligent account of their work^ my
object is gained^ and I gladly leave to others the more ambitious walks
of Philology. The path of the beginner is thorny enough ; to clear a
part of that will be no mean satisfaction to any one who sympathises
with those who have but little time, and desire to make the best use of
it.

ELEMENTS OF GBAMMAE, IN ENGLISH,

THE SENTENCE.

Subject and Speech-claiMe, or Predicaie*

No sentence can be Tvithout a Subject, and a Predicate or Speech-clause
concerning the Subject.

(}) All language arises from the same necessity of human nature, being a
method of making known what passes in the mind. Therefore the
impressions to be iaade known will mould that which is outwardly to
represent them.

And the common laws of language will be determined by the necessities
which arise directly there is any attempt to make known what passes in
the mind.

All languages therefore will have common ^ points of agreement, by
whatever names these

may be called. .(*) The first of these is a set of outward tokens
whether spoken or written; that is, words.

0) [@0] Why do you talk?

3) [@3] How do you make hnowu notwaft \iv Vx^^{ax}“^

2 SUBJECT AND SPEECH-CLAUSB.

8) [@8] But words must be arranged so as to hare a

connected meaning. (^) That is, words must be arranged in Sentences. A
sentence being, words arranged so as to hare

a meaning, (ft) That is, eyeiy Sentence tells something. (^) But before
anything can be told, it is neces*

sary to mention that toneeming which the

Speech* is to be. CO Having done this, the speech concerning it na*

turally comes next. (s) Every sentence therefore must contain at the

least two things. (0) Ist. That which is mentioned, 2ndly. The speech
concerning it* * That which is mentioned' is called ^ The 8ub^

ject/ (10) The Speech concerning the Subject is called ^ The

Speech-clause or Predicaief

(^) WiU any words taken at random he sfu^i&ntf iS) What is this
arrangement called f (*) How can words convey meaning f (^) What must be
done before anything can be toldf (^) WiU that alone make a sentence f
(s) How m>any things then must there be in a sentencef (») What two
things f (10) Sy what special names are they known f

- The word 'Speech' in this work is used as equal to
- thai which la spoken or said' in any senteaoa.

)

SUBJECT AND SPEECH-CLAUSE. 3

11) [@11] There cannot therefore be less than two words

12) in a sentence ; because nothing can be men- tioned in less than one
    word, and no speech can take place concerning it in less than one

(IS) word. For instance, ' Man walks,' is as short a Sentence as can be
framed. The Subject ^Jlfan/ being one word, and the Speech-clause or
Predicate * walks/ being one word.

(1^) N.B. The question, ' Who or what is men* tionedf will always return
the Subject as its answer.

(1^ And, * What is said o/ths Subject f will return the Speech-clause or
Predicate.

11) [@11] What then is the smallest number qf words that

can form a sentence f (W) Wh2/f

(IS) Cfive me such a sentence f Why is that a sentence? What is the
Subject? What the speech-clause or Predicate f Why is man the Subject?
Why is walks the Speech-clause or Predicate ? (1^) What question wiU
always ;0kd out the Subject? (15) What question wUl always find out the
Speeeh* clause or Predicate? Ash a question which shall force me to
answer

the Subject, Ask a question which shall force me to answer the
Predicate*

NOUN AND VERB. Man walks.

No senteDce can be Tvithout a Noun or Bomething representing a Noun as
its Subject.

No sentence can be without a Verb in its Predicate or Speech-clause.

10) [@10] It is eyident that no mention can be made of anything unless
    it is named. In Grammar, every thing that is named in one Q^) word
    is called a Noun, The word * nomen/ that is, nounf in Latin, meaning
    Name, Nouns, or things named in one word, form a distinct Glass of
    words. Every distinct Class of words is called a Part of Speech.

0®) The Noun therefore, or Name-form, is a Part of Speech, and every
noun can stand as the Subject of a Sentence.

(1^) And no Sentence can be without a Noun, or something representing a
noun, as its Sub- ject.

(1*) .Com a thing be itientioned vnthout naming it f 0^) V ^ thing is
named in one word, what part of

speech must th4xt word he f (18) WTiat part of a Sentence can every
nov/n he f

Why, ^c. f (1®) If a Sentence consists of only two words, what part of
speech must one he t

NOUN AND VERB. 5

(SO) But something more than a Subject is wanted

for a Sentence, there must be a Speech-dause^

or Predicate. That is, something must be

said of the Subject. (31) K this is done by one word, that word is
called

a Verb. Verbs, therefor^ are words which

tell or speak of something. (») Verbs form a distinct Glass. The Verb
there-

fore, or Speech-word, is a Part of Speech. (28) In the simplest form of
Sentence, therefore^

the Subject is a Noun, and the Speech-clause^

or Predicate, a Verb. (M) And**” by definition the Speech-clause must

speak of the Subject. (^) This then is the simplest form of Subject, one
(16) Noun, *Mans' and the simplest form of

Speech-clause, one Verb, ' walks/

90) [@90] What does a sentence want more than a Subjeeif What is the
    Speech-clause or Predicate of this

sentence f Why is it the Speech-clause or Predicate f

91) [@91] What is that word cdUedf

(«) What part of speech then is the word^waUa*f (S3) What parts of
speech then ea least does every

sentence require f (24) Why f (26) What part of speech muH ihe Subject
always he^

or at least represent f (26) WTiat part of speech will always he in the
Speech^

clause or Predicate f

- See p. 2, que&Uon 10. V-^'&

I»

NUMBER. Man walkif mem vealk,

Nonns can show by their form differeiuM ot Number, so can Verbs. The
Verb then fore must agree with its Sal^ect Noim i Number.

The Plural Number of most Nouns is ftnrme from the Singular by adding s^
as, Singuh « Horse,' Plural * Horses/

1) The Noun then is a Name^ and as a simp

(*) name will only name one. But it will I

necessary often to name two or more tlunj

of the same kind together. It will clear!

be conyenient to express them all by oi

wordy if possible. Can then the form of tl

Noun bo altered so as to mark this distinctic

of one, or more than one, without the additic

of any other word to it?

First then of the noun ' Man* The /arm <

(>) this word may be altered to /men./ And tl

alteration of form does arise from a desire i

alter the sense. The word /man/ namii

man as One; the word 'men' naming moi

than one.

1) What then is even/ noun f

0) [@0] We fret use a name to mark what f (*) In the eentence 'man
   walks/ can the form ofH noun alter f

NUMBER. 7

(^) The difference therefore conveyed by this change ot form is a
difference of Number. ^MwrC denoting One; ^ mm^ denoting more than one.
ThA Noun, or Namerform, is said to he in the Singular or Plural Number,
according as it

(*) takes one or other of these forms. That is, a nov/n in the Singular
Nwmher shows by its form that it is naming a single one; but in the
Plural Number, that it is naming a Plu- rality, or more than one,

(«) Now by definition the Speech, clause, or Predi- cate, speaks of the
Subject ; as then the noun by its form shows difference of Number, it is
convenient that the Verb, or Speech-word, which speaks of it should be
able to show the same. There are thei^efore differences of Number eac
pressed by the form of the Verb, That is, a

4) [@4] WJiat does 'man' mean f What does 'men' meanf

What is the difference conveyed by this change f

5) [@5] What is meant by a notm being in the Singular

Number f In the Plural f What names then does a noun receive according

to the numbers it names f (®) What has the Speech-clause or Predicate to
do

with the Svibjectf Does the word ' walks ' point out anxj nuwfcwl

8 KUlfBBR.

7) [@7] verb has a Singular cmd PlurcU Number ; sAotv- ing by its/brm
   whether it epeahe ofane or mor$ than one.

It is manifest therefore that in any apparent sentence^ if the forms of
the Noon and Verb do not agree in showing the same numbers,

8) [@8] there is no real sentence, as the Speech-clause, or Predicate,
   is false: for by definition the Speech-clause must speak of the
   Subject. Whereas, if the form of the Noun denotes one, and the form
   of the yerb more than one, or ijice versa, the Speech-clause, or
   Predicate, does not speak of the Subject; and there is no sentence.

9) The Verb then, or Speech-word, muet agree with

its Subject in Number, N.B. The word, or words, which name the Subject
are generally called the Nominatire

11) [@11] (or naming) case. In this work they will merely be called the
    Subject-form, or, the

C^) Can we alter it so as to point out momy f

Hien a verb has a Singular and Plural Number f And a noun has a Singular
and Plural Number f

8) [@8] What does a sentence consist off

WTuxt part of the sentence is the nown * men* f What part of the
sentence is the verb * walks*?

9) [@9] Have you anyfauU to find with * men walks ' f Why?

10) What then is the rule about verb and nounf

11) What is the word catted which names the Subject f

MUMBBR. 9

Subject; for reasons ^hich will appear fur- ther on.

12) [@12] Also, the Plural Number of most nouns is formed from the
    Singular by adding s, as Sing. * Horse ;* Plur. * Horses/

13) But in the Yerb the addition of s always marks the Singular form.
    Thus * man walks/ * men walk ;' though the absence ofs does not
    always indicate that the yerb is Plural.

PERSON.

Hum walkestf i^c. 

Nouns each represent some Person. Verbs show differences of Person by
their form. The Verb therefore must agree with its Sub- ject-noun in
Person as well as Number.

(0 The Sentence then at present stands thus,

- mem walks,* or, * men walk,' (?) Now the word ' marC names any man,
  and the

Terb speaks of it. But it is clear that it is (3) necessary to be able
to speak to some one.

12) [@12] How is the Plural number of most nouns formedf

13) How many numbers has a verb f And a noun f

14) In the sentence 'man walks,* what person do you

speak of as walking f (*) Can you name yourself? Can you speak to a
person f

10 PERSON.

and also ofyowndf; and the rerb manifestly may express these distmctions
by its fonn alone ; and it does actually do so.

(^) For I write, * man walkeatJ If that is not cor- rect, the yerb must
conyey by its form some

(^) notion besides the notion of Number ; since

0) [@0] as £eu: as number goes it is correct. ^M<m! one ; * walkest/
   one. The difference is a dif- ference of person. ' Man^* denoting any
   per*

17) [@17] son q/* whom; 't{^{2}^/ denoting a particular person to whom,
    you are speaking ; commonly called the second Person. The yerb also
    shows by its form whether its speech is of the speaker himself, or
    of any other person whateyer. Thus there are found

I

Thou

He or man

19) [@19] all capable of standing as Subjects; and the

4) [@4] Is 'man walkest^ correct f

5) What number is * man ' f What number is * walkest' f Then the numbers
   are right f

(«) What is there wrong f

17) [@17] What then does the change of form tn thA ver6 express ^ CV
    C^nyou speak o/yowrsdf a$ tx^ilfeing f >^^{'}/ is this called f

PERSON. 11

yerb which speaks concerning them, also ca* pable of showing this
distinction by ita/orm. Thus,

I walk.

Thou walkest.

He walks or walketh.

1) There are then three different forms for the

9) [@9] Singular Number of a Verb. And according

0<>) to the form it takes, the yerb is said to be in

the 1st, 2nd, or 3rd Person. That is, the yerb

denotes by its ybrm one speaking

q/* himself to another of another.

Kow as it is required to be able to speak 0/ oneself with others^ to a
second person %mth (11) others, and, q/* two or more others togethery
the yerb might show all these distinctions by its forvny in its Plural
Number, or at least must be able to express them without contradiction.

0) [@0] Ccm you point owt that a person you speak to is walking f What
   is this called f 0^) Coff^ you speak of any other person as waJMng f

What is this called? (11) Can you speak qf these same persons with
others f

How many numbers can a verb be ml 0^)JSbw many times do j/ou tacwtlowi
tV* “^^^^ ^{“} foin^ through the Prea^ml tev^se)

12 PERSON.

The verb then proceeds as follows :

Singular. Plural.

2) [@2] I walk. We walk.

Thou walkest. You, or ye walk.

He walketh, or walks. They walk.

The yerb expressing two differences of Number, (13) and three
differences of Person in each Num- ber; in all, six distinctions of
sense. In some languages, all these distinctions are shown by (^0
distinct /&rm«. In English, the Plural has but one form for its three
Persons. It is manifest that every noun spoken of by another is in the
3rd Person ; since it is not the speaker, nor a person spoken to. (1*)
It is manifest that the Verb, or Speech-word, must agree with that of
which it is to speak in Number and Person. Corel. No word, or words, can
possibly stand as the Subject, which the Verb, or Speech- word, by its
form shows it does not speak of. Also, whenever words show by their form
special distinctions, these/orms cannot be in- terchanged or disregarded
in joining words together, that is» in a Sentence.

(i*) Do all these denote number f

WhcU do they denote f ^14) Does the form of the verb change for every
Person in each nvmber f fFjku are the changes in EnglisKI O^J TFi^t rule
arises out of t/iese /ocU ?

{

ARTICLB. 13

THE ARTICLE.

a man walks, the man walk$.

There are two Articles^ /^/ or /^n,' and * The: The Definite Article '
The' Umits the sense of the noun to some one known. The Indefinite
Article /A/ only Umits it to anyone of the class named.

In the sentence /man walkSf it will be seen that the sense conyeyed by
the subject / m^an/

1) is yery wide; as it means nothing less than *m>a/nkind/ or all men
   taken as one race

2) or class. But we generally want to speak of indiyidualsy not of a
   whole class. That is, wo want to limit the person or thing spoken of
   to one of a class.

3) Now this is done most markedly/ by limiting it

to some one knovun, less markedly, to any one of

the class, (^) This limitation is made in English by putting

a word before the noun limited. This word

is called an Article. An Article therefore is a word joined to the noun

to limit it*

0) [@0] What is the meaning ojf'man'f (^) Do we generally vnsh to spealc
   io •uwA^{xj'} (^) How can we limit the sense?
1) What is the word wh\6h limits colUA*^

14 ARTICLE.

(<) There are two Articles. The word * The* eaUed the definite or
limiting article. The word *A^

0) [@0] called the indefinite or uvdimiting article^ as it is, if
   compared with * The/ Thus,

man walks. The class. 7^ man walks. One marked out of the class. A man
walks. Any one of the class.

- The'fiadng the limit to the particular one, *A' extending the limit to
  any one qfthe class^

{

THE VERB. TRANSITIVE AND INTRAN- SITIVE.

Man^ loves ajriend. Man walks.

Verbs are divided into Transitive and In- transitive. In Transitive
Verbs the sense passes across from the verb to some noun. In
Intransitive Verbs the sense is completed in the verb itself, as, 'Man
loves a friend/ Transitive.' Man walks/ Intransitive.

17) [@17] In the Sentence ' man walks! the Speech-clause, or Predicate,
    is one word. And it is obvious

(«) What is the definite article f

Why is it so called f (6) What is the indefinite article f

Why is it so called f

Write * man walks/ and /man hws a friend,/ Are th^ both sentences, and
vSKy ? >^^Aa df^renoe in the Sul^ect or Predw»to1

THSYBKB. TRANSITIVE AMD IKTRAMSXTIYB. 15

2) [@2] that the sense of that word is complete in itselfy as the action
   spoken of is a perfect pro- cessy namely, walking, finished by the
   agent, and does not pass on to any other thing. But it is necessary
   that it should be possible to

3) speak of actions not thus complete in them* selves, but where the
   agent acts on, or in relation to, something. The sense passing, as it
   were^ beyond, and out of the rerb otcross to some farther point, as,
   /Man loves a/riend/ If this is compared with the sentence ' ma/n
   walks/ it will be seen that the Speech-clause or Predicate alone is
   altered, the first Speech- clause being complete in one word, the
   verb of the second Speech-clause not being thus complete in itself.
   As, 'Mem hves./ The

4) question immediately arises, what? And the sense is incomplete till
   that is added, for in-

(^) stance, ' afrimd* This, or the Uke addition, fills up the Toid, and
makes the second Speech- clause as complete as the first. This distinc-
tion then in verbs of incompleteness, or com-

2) [@2] What is the Speech-clause or Predicate of the first sentence f
   Is anything wa/nted besides the verbf Why not f (/) Is the second
   Speech-clause or Predicate thus com/

plete in one wordf (*) What more is wanted f (0 What then is the
digerenxA bet'weeu i^ ^{J«}^

16 THB VERB. TRANSITIVE AND INTRANSITITS.

pletenessy diyides tbem into two great classes,

which are called, the one, Trcmsitive (or passing

• across) yerbs, as the verb, * loves,' where the

(®) sense must pcus across to the object of love,

7) [@7] for instance, 'a friend,* and is not completed

(^) till that is added. The other, Intrcmsitive (or

not passing across) verbs, as the verb * walks,*

where the sense requires no such addition.

Transitive verbs, therefore, are verbs whose sense

passes out of the verb itself across to something

beyond; the action being performed by the agent

on or toward something else.

Intransitive verbs are verbs whose sense is shut up

and complete in the verb itself, the action being

stated to be finished by the agent himself

CASE. Man loves a friend.

Words are said to be in a * case,^ when they show by their form
dependence on a word which governs them. In English there are two cases
properly so called, the Possessive Case and the Dependent Case.

8) [@8] If th£ sense of a verb is not complete, what must

happen? Q) What are such verbs called f CO If^f are verbs called which
require no such ad” dttton f

CASE. 17

In the sentence ^num loves a friend/ there is found first the Name-form^
or Noun, or Snb- 0) j^^ standing by itself, and then hj itself a
Speech-clause or Predicate, like a fiiU yessel, made up of two things, a
verb which by itself is empty, and a noun which by itself is spilt and
lost. There is an intimate relation be*

3) [@3] tween the yerb and noun, which exists whether the noun shows it
   by its form or not, a de* pendence of the noun which might be shown
   hyform always, and is so in some languages. Now whenever the Notm ia
   thus dependent, it ia

4) said to he in a Case. That is, whenever any word or words depend on
   another word, the sense of which is incomplete without them, that
   word

5) or those words are said to he in a* case/ and the

6) word requiring the addition is said to govern that case.

It is clear that all languages require to express much the same
dependent relations, but all do not show them by the form of the word.
The English language does not It seems the (0) clearest plan to confine
the name * Com* pri- marily to formal Cases, that is, to Cases marked

(}) What does a Transitive verh require f

2) [@2] When the notm stands thus, what is said ofitf

3) What is this dependence called f

0) [@0] WhatisaCasef

(^) What is meant hy govemvag a Coafc^ (^) How shall we limit tTie ncwae
Coae w B-w^{V.}'^

18 CASE.

by change of form; but where the game ybrm, without change, is used in
fixed combinations to represent relations which other languages
represent by a formal change, as for instance, such a combination as,
/to a friend/ it is not objectionable to call such combinations, '
Cases,' and name them as, in those languages, the formal case is named.
Erery noun, without change, can stand as the Subject of a Sentence.
Hence this hidepen- dent word is, in this work, called the Subject Form.
Dependence, that is, Case, being pro- perly shown by a deviation from
this Form. C^) In English there are two formal cases, The Possessive
Case and Dependent Case,* as, PoS' sessive Case, Friend's, His.
Dependent Case, Friend, Him.

8) [@8] In nouns, the Possessive case is formed from

the Subject form by the addition of (*«) (s with

(®) the apostrophe). The dependent case is dis-

tinguished from the subject only by its place

in the sentence.

In Pronouns, as will be seen better farther on,

both cases differ from the Subject form. Examples of the two cases : man
loves a friend, man loves a friend's counsel.

16) [@16] How many cases are there f (V ^ow is the Possessive Case
    formed ? (^^ ^{F}iat marks the J?ependent Case f

CASB. 19

To be parsed, or given account of, as follows :

- Friend* The Dependent case, Singular Num- ber, from the Subject form *
  friend,' governed by the Transitive verb * loveaJ

- Frimds,' The Possessive case, Singular Num- ber, from the Subject form
  'friend,' governed by the noun * counsel.*

Examples of other dependent relations which some languages express
ybrma%, are 'Liberality to a friend.'

- The stars in heaven.' 'Poems h/ Southey/

- Emigrants yrom Ireland.'

Combinations which may be thus parsed :

*To a/riend/ Friend, Dependent case governed by to denoting receptive
object; the combined expression representing the Receptive or Da- tive
Case.

'From Ireland/ in like manner, may be said to represent an Ablative
case. Note, Ablative means * taking away,'

/By Southe^j also may be called an Instru- mental case; and /In heaven/
a Local Case, if it is considered desirable to extend the No-
menclature.

The Possessive case, in the Plural Number, is only marked by the
apostrophe (') after the «.

The Subject form is used m aAdx^{'}KOi^^^^{'t'}*

A noun then is complete, «Ji Va ^^ 1^{3}«^{>»}

example :

22 THS PREPOSITION OR CA8B-LINK.

The words 'To/ //rofii,' /f»/ ^towards/ are Pre- positions or
Case-linkSy linking the word ^/rimoP on to the word' liberality,' and
showing a par- ticular dependent relation thereby. Prepo- sitions or
Case-linkS} therefore, are an extension of the principle that gives rise
to /ormal cases : for Case-links denote, as separate words, a de*

(<) pendent relation of one word on another, whilst jTormal Cases denote
it hj change of form. Prepositions, or Case-links, are said to goyem the
dependent word after the word preceding

(^) ihem. They come between the goyeming and governed word, and denote
the relation of the one to the other.

THE ADJECTIVE. A good man loves a wise liberality.

Adjectives are joined to nouns to show the sort or quality of the noun,
as, * A good man.'

In English, Adjectives do not change their form to show either Number,
Person, Case, or Gender. Adjectives are said to agree with the noun to
which they are joined.

The Sentence at present stands thus, * Man loves liberality to a
friend,* And it has already been shown that any noun may be limited by

e*) What are Prepositions f

(^) How do they stand in a sentence f

THB ADJBCTIYB, 23

0) [@0] an Article, either to some partienlar one of a dasSy or to any
   one of a class. Still however the sense is very wide, no knowledge
   concern-*

2) [@2] ing the sort of class, or the sort of IndiTidual, is ^yen by
   these limitations. There is a fiir- iher need.

(<) A speaker often does want to show th$ tort of class, the sort of
individual. For instance^ in the sentence, 'A man loves liberality* this
is not strictly irae ; all men do not. The trae sense requires a
limitation to the sort of man; for instance,' A good man loves,* Again,
the good man does not love any liberality, that too most be qnalified;
for instance, a tuise UberaUty. These words which limit to the sort

(^) or quality are called Adjectives, that is, words

(s>) added,

Thdr principle of constraction is evident, namely, that their form, if
raried, must not be

0) [@0] ineonsiBtent with the formal peculiarities of the nouns they are
   added to.

17) [@17] In English the Adjective has no change of form.

1) What is the duly qfan Article f

2) Does it tell tM the sort or quality of ike noun f

(*) What need does not the Article supply f

f *) What limiting words supply it f

^5) What are Adjectives f

(®) To what are they added f

17) [@17] Do they change their form f

24 THE ADJBCTIVE.

<s) When joined to the noun thej are said to agree with the noun. Borne
langoages change the form of their Adjectires to correspond to erery
formal change of the nomis they agree with, whether of Number or Case.
The noun also can show sometimes whether that of which it is the
Name-form is male or female; in some instances by its form, as 'Actor/'
Actress.' That is, it can denote Qender. Ad- jectiyes, howerer, do not
change their form for this either in the English language.

When a noun is the name of a male, it is said to be of the Masculine
Gender, when it is the name of a female, it is said to be of the
Feminine Gender. Those things which are not spoken of as Male or Female,
are said to be of the Neuter Gender. The word Neuter meaning neither,
that is, neither Masculine nor Feminine.

An Adjective therefore shows the sort or qtuHity of the noun it agrees
with, and does not cha/ngt its form in the English language*

ADVERBS.

Oood men greatly love counsel.

Adverbs are joined to verbs principally, but also to adjectives and
other adverbs, to show

C^J fP2at u their being ctdded to the nouu calUdI

ADVERBS* 25

the sort or degree of the verb^ adjective, or adverb, as, * Greatly
loves.'

At present then there is a Subject qualified if need he, and a
Speech-clause or Predicate madb up of a verb with its case, the case
also qualified if need he ; as, ' Good men love wise counsel/ Here there
are additions made to the nouns but not to the verb. Yet as th^ main
difference between a noun and a verb often is, that a noun denotes by a
name that which is, whilst a verb states it as belonging to something; a
verb being but a noun stated of something, as noun, 'counsel;' verb, /to
counsel/ the noun stated ; it is clear that the same necessity which
requires the limitation of the noun extends to the verb also, and re/

3) [@3] quires that tTie sort or degree of that which is stated by the
   verb or Speech-word should be mentioned also. Thus, ' Good men love
   coun^ sel/ but in what degree, 'greatly/ love it* Thus

(0 there are words showing the sort or degree of

(^) that which is stated added to verbs, as there

are words showing the quality or sort of that

4) [@4] which is named added to the noun. These words are called
   Adverbs, Adverbs, therefore,

(0 Is the Verb ever qualified f

2) [@2] Why should it be f

(«) What are Adverbs?

(9 How ar^ they lilce Adjcctvie*'^

26 DBGRBB IN ADJECTIVES.

af8 words added to verbi to UmiU the aetion spoken of to its proper sort
or degree.

DEGREE IN ADJECTIVES.

Quiokf quicker, quickei$.

Tbe original foim of an Adjective is said to be in the Positive Degree,
as, great: when er is added, it is said to be in the Comparative Degree,
as being comparatively more, as, greater ; and when est is added, the
Adjective is said to be in the Superlative Degree, as being
superlatively, or beyond measure most, as, greatest. The adverbs more
and most are frequentlyadded to Adjectives to express these degrees, the
form of the Adjective remaining unchanged.

0) [@0] In Adjectiyes also the degree of quality as to more or less is
   often required to be expressed.

3) [@3] Adjectiyes sometimes express degree formally; as, qtfickf
   quicker, quickest. The Adjectiye is then said to be in the Positive,
   Comparative, or Superlative degree. The afi&xing * er' to the
   original form, generally marking tbe Com- parative degree, and the
   affixing * est' marking

17) [@17] Adjectives teU vs the quality, the same quality belongs to
    some things more, to others less, is this ever expressed?

(^) How is it expressed formally f

DSQRBB IN ADJECTITB8. 27

the Superlative degree. Sometimes, howeyer^ (>) Ady^bis are joined to
Adjeotiyes to expirem either these degreesi or the finer Bhadea of
dJBtinction ; as, quiokf more quick, mast fmckf quick, much quicker, /ar
quickest. Adverbs also are sometimes joined to Adverbs, as, /<ur more;
very m/uch. more, &c The Ad* verbs that most frequeitly express degree
ia Adjectives are, the word /mcre/ to express Comparative Degree; and
the word *most' to express Superlative Degree.

TENSE OR TIME-FORM.

loves loved The man { (wiU love counsel* or shall

A verb is said to be in a Tense ; first, when its form denotes the Time
of the action spoken of; and secondly, when other verbs, called
auxiliary verbs, are added to the principal verb to show Time.

One great class of verbs in English shows

li:

8) [@8] Is it ever expressed in any other wayf

Did we see anything like this with respect to cases f What analogy is
there between Prepositions and Adverbs f

28^ TBNSB OR TIME-FORM.

Past Time by adding d or ed to the form which shows Present Time. These
verbs are often called Regular Verbs, or the tense is called the Modem
form, as, * I love/ Present Tense ; * I loved/ Past Tense.

• Another great class shows Past Time by changing the central vowel or
vowels of the Present Tense. These verbs are often called Irregular
Verbs, or the tense is called the Ancient Form ; as, ^ I ride,' Present
Tense ;

- I rode,' Past Tense.

The auxiliary verbs which show Future Time are the verbs ShaU and Will.
Auxili- ary verbs of Present and Past Time are the tenses of the verbs
To he, Tq do, and To have.

(}) It is manifest that when anything is spoken of, it must be
represented as belonging to some

2) [@2] Time, either to Past, or Present, or Future Time, and language
   must show this somehow or other. Now Verbs are the speech-words

3) which speak of things. It is probable, there*

4) fore, that at least the broad distinctions of Time will be shown by
   the form of the Verb or speech-word, whilst adverbs of Time, or some
   other artifice, will be employed for the

(}) Can cmyihing he spoken of apart from Timef

2) [@2] What are the great divisions of Time f

3) What words speak of things f

(*) What is probable then concerning these words f

TSN8B OR TIUB-FORIL 29

1) less oommon wants. In English, Past and Present Time is shown
   formally ; and the Verb is said to be in the Past, or Present Tense,
   or Time-form, according as its form shows Past O or Present Time.
   (Tense means Time, from the Latin word for Time, Tempus.) One

0) [@0] great class of Verbs in English shows Past Time by adding /d/ or
   ^ed* to the Present Time-form; as. Present Tense, or Time-form, ' I
   lovef' Past Tense, ' I loved;' Present Tense,

- I call;' Past Tense, 'leaUedJ

Another great class shows Time by changing the central Vowels; as.
Present Tense, 'J ride^ Past Tense, * I rode.'

Thus in the sentence, /man loves counsel,' the Torb / loves' shows by
its Jbrm the Time of loying; that is, the verb ' lores ' is in a Tense,
the Present Tense.

And in the sentence, ' the man loved cotmsel,' the yerb * loved,' also
shows by its form the Time of loving; that is, the verb 4oved' is in a
Tense, the Past Tense.

With respect to Future Time, it is clear that our minds can imagine it;
but that, strictly speaking, there is no future Time. The ut- most that
is strictly correct, is a strong present certainty in the mind that an
event will here-

{^) Is this really/ the case f

(^) How is Past Time shown f

7) [@7] What is the meaning of Tense f

30 TBNSB OR TIME-FORM.

after take place. The Future therefore, in strict speech, is reduced to
& present mental impresBion, however strong, and has no posi* tire
existence, as the Past once had, and the Present has. Now, undoubtedly,
the most convenient method, is to treat Future Time as positive, and
denote it by a formal change (many languages do this) ; but the most
cor- rect, is to express it as the mental impression that it really is,
by the addition of other words, as in English.

The man shall or will go. (8) Futm'e Time^ in English, is expressed hy
the original form or root of the verb, tuith the .(®) addition of one of
two words, both of which denote the mental impression; the word* will,'
which denotes the speaker's conviction of the (10) will employed, and
the word 'shall,' which denotes his conviction of the obligation. Thus
we have a combination representing Future Time^ or a Future Tense, i
Shall or go, will

or “J ^ * Ml go. Expressions representing

your and my going at some future time.

8) [@8] How does the English language expressFutureTimef (») What is the
   sense of « will ' f O^yO/'shalVf

TBNSB OR TIMB-FORll. 31

it seems best to parse ; that is, give a gramiila- tical account of
these words separately, as follows :

- Shall/ Singular Number, first person, present tense, joined as an
  auxiliary or helping yerb to the word /go;' and /wUl/ in like manner.

- Go,' original form or root of verb * to go,' * I shall go,' &c.,
  combination representing Aiture tense.

Both these verbs, UTutlV and /tiAUf' as auxiliaries, express the present
conviction of 9 future event, with this difference of sense. In speaking
of yourself, your own /vnU* you are certain of;

11) [@11] the auxiliary expressing ' will' is therefore the (}^)
    strongest word. In speaking of any other but

yourself, the necessity or obligation from with- (18) out, not his
/tuill/ is what you are most cer- (14) tain of; therefore the auxiliary
expressing con/ viction of necessity or obligation is strongest. Thus,
'I wUl go,' expressing your decided will is stronger than, ' I shall
go,' merely ex^ pressing some obligation to do so. But 'you shall go,'
expressing the speaker^s conviction that the obligation is sufficient to
enforce the action is stronger than 'you vnU go,' which merely expresses
his notion of the /will/ of

(1^ In speaking ofyowrsdf^ which is strongest f

12) [@12] Whyf

13) Xn speaking 0/ another, which is strongest f Q^)Whyf

32 TEN8B OB TIME-FORM.

18) [@18] another of which he is no sure judge. K.B. The yerbs akdll,
    and wiU, wh^i auxiliaries^

19) never denote anything but Tense, A verb then M sand toheva a tenaei
    Jirvi, when iUform de' noUe the tMM of the aetMn. spoken of. And

(yO eeeoncUy, when other verbSf called auxUieny or

(^*) helping verbs, are added to ths original fbrm or root qfthe
principal verb, to show dietinetione of Time, the combined expreseion
may aJLeo be called a Tenee or Tim^/orm,

Before we proceed, let it be obsenred that all auxiliary or helping
yerbs are originally and 0^) properly separate yerbs by themselyes, with
their own separate yerbal sense, and are in constant use in this their
original and proper duty, as will be explained hereafter.

15) [@15] What is the first and most correct sense qf Tensef (i«) What
    is its secondary sense f

16) What are /shaU/ and 'wiU* called when they

form a Tensef

18) [@18] j)o they ever as auxiliaries denote anything be*

sides Timef (*•) What are ofuasiliary verbs properly f

THE PARTICIPLE. 33

THE PARTICIPLE. Loving, or hdmng loved, a/riend.

The verb has a form called a Participle.

There is a Participle of IVesent Time, and a Participle of Past Time.

The Present Participle is generally formed by adding /ing/ to the root
of the verb, as root, /To love;' Present Participle, / Loving/

The Past Participle is a combination of the auxiliary * halving/ with a
Participle formed from the root by adding d or ed, as, * Having lov^d,'
Past Participle of the verb * To love/

1) Verbs have a form which in sense differs from

2) an adjective only by the addition of the notion

3) of Time, Present or Past, and by the power of governing the same case
   as its verb. This form is called a Participle. Thus, ^A loving
   friend.*

4) « Loving/ is the Present Participle from -the verb ' to love ;'
   denoting, like an adjective, the quality or sort of friend, but
   moreover telling the Time, such as the present time. The present
   Participle can also govern the same case as its Verb. As, * His
   friend loving him much/ &c. ; where the word ' him,' is the de-

17) [@17] What is a Participle f (^) How does it differ fr(ym, a'a
    Adjectm^ («) Bow is it like a Verh^

34 THB PARTIOIPliB.

pendent case after the Present Puiiciple * loving^' and denotes the
object of lore. (4) There is also a Partioiple of Past Time, or Past
Participle ; as, * Tumng loved him/ The words * having loved^* are the
Past Participle of the verb ^to Ioyo/ This Participle is formed by
combining the auxiliary 'having/ with a Puiidple formed from the root by
adding /d' or /ed/ but not used out of com- bination with a Transitire
sense. Participlea, ther^ore, are Adjectives with the ad^ dition of the
notion of tms^ and a power of governing a ease. Participles are
generally (/) formed from the original form or root of the (•) verbf by
adding /ing' for Present Time, 'ed' or * d/ with an auasiUaryfor Past
Time.

TENSE OR TIME-FORM.

Combinations. ' I am loving/ ^e.

In treating of the Future Tense we found it

1) was made up of the root of the principal verb

and another yerb assisting as auxiliary to it.

(^) This same plan is followed for other distinc*

(*) How many Participles are there f

(*) How is the Present Participle generaUy formed f

(^) How is the Past f

COlTaw tms the Future Teme mode v^t CV^re other tenses supplied thus ?

TBMBB OR TIME-rORH. 35

Uom of Time, which Bome languages express /ormaUy. In the principal
verb, the root or

(') original form, the Present Puiiciple, and the yerbal form employed
in maldng up the Past Participle, are used in combination with aux-
iliary rerbs. The verbal form in sudi com- binations, governing a case
if its verb gorems

4) [@4] a case. The verbs comlnned with them as auxiliaries are,

I am ) Present Tense*

I was J JPast

I do ) Present .

I did J Past

I have 1 Present •

I had ) Past

And they are employed as follows :

3) [@3] Present Tense and representing Present.

I loYO ^ General Notion.

8) [@8] I am loving = Emphatic Present Time. I do love = Emphatic
   Present Aetion*

(<) Wha/t parts of ike «er6 are joined wUh aittxiliaries

to express Timef (4) WJuU atueiliaries are usedf (/) What is the force
of/am* and /have/ in these

cominnaiions f («) What is the force of'do'f C) What Present Tmsee ore
tkenre^ (^) How do ike^ diffw in senset

86 TENSE OR TIME-FORM.

Q^) Camfnnation representing Imperfect Tense.

I was loying. (y^y Past Tense and representing Past^

I loYed = General Notion.

I have loYed == Emphatic Past Time, or Perfect.

I did love ~ Emphatic Past Action.

I had loYod = Completed Action, or Pluperfect.

(&) In these Combinations, ' Am' and ' Have,* throw

emphasis on the Time; whilst ' Do,' and * Did,'

(<^) throw emphasis on the Action spoken of» In

giving On account therefore of a word in any

Tense, it WotM be well to mark the tense as it is

done in' the Table, according to these distinctions.

0) [@0] Thus in the combination, *I am loving/ ctfter

going thr&ugh the words separately, say, * Com-

bination of Emphatic Time, Present Tense.*

There are other combinations which might be included under the head of
Tenses, but which faSl su&ciently under the rules of ordinary
construction to need no separate notice. As, ' I haTe been writing,'
denoting continuance of Past Action. The Parsing of which, however, more
properly belongs to the verb /To be/ / I am going to write,' in like
manner rather belonging to the verb * To go* &c. 

9) [@9] How wouM you give an account of one of these combinations f O^)
   IF:^ai 18 the Imperfect Tense? OO^ame and eojplain the Fast Tenses,

TENSE OR TIME-FORM. 37

The auxiliary verb * I am/ and its TenseB, can he (2) joined to any
adjective or noun, vnth no proper

sense of its own, but only with the effect of Q) making such adjective
or noun stand as a proper

Speechrclause, or Predicate. Thus,

iis alive, equalling, he lires. %s great. is, &c. 

The Verb Substantiye (of Existence).

1) The verb 'I am,' and its tenses in its original

2) sense denotes ' eaiistence,' and is therefore called

3) the Verb Stibstantive, or Verb of * existence;*

4) and, when thus used, stamds by itself as the (/) Speech-clause or
   Predicate, As, / The world is,*

that is, * exists ;' ' Time was,* thai is, did ' exist.*

0) [@0] Can any Adjective or Noun stand as a Predicatef

3) [@3] How is this managed f

4) JVhat Part of Speech does the combined expreS'

sion represent f

(^) What is the original sense of the verb *tobe'f (2) What is that verb
then called f (8) Why f

4) [@4] How will you recognize the Verb Substantive in

a Sentence? (^) Is it right to call it auxilvxini w «uaV. a
«^{«}v5r^{.'} Why not f ,.

38 TBNSB OR TIME-FORM.

(/) The verba / have/ and * do, when not atueiliafy (7) are transitive,
and require a case, and are t^tias

eaaHXy distinguiehable. As, ^ I do my dvsty ;* * I

have the money*

THE CONJUNCTION.

A.ndy £fc,

CoDJunctions are words which join sentences, clauses of sentences, or
single words together, as^ * The horse and dog/

The simple sentence must at least consist of a noun and a verb. And
these or their substitutes are the ground-work of all sen- tences. And
by definition the noun names, whilst the verb speaks of that which is
named. The noun being a Name-word, and the verb a Speech-word. The noun
is capable of showing Number and Person ; the verb by its /arm denotes
both. It follows “therefore that in a sentence, as the verb speaks of
the noun, these Jbrms must not contradict each other. The noun,
moreover, may be limited by articles, qualified by ad- jectives; whilst
adjectives may in turn be

(fi) WTien the verbs 'have* or 'do' are not auociliary,

what are they f 0) How vjiU you distinguish between their two offices f

I

THE CONJUNCTION. 39

modified by adverbs. The yerb may be qualified by adyerbs, and moreover
denotes by form or otiiierwise a Time, it may also require a Case, and
the Case in turn may be limited and qualified by articles and
adjectives. So isx of the simple Sentence. But it is mani-

1) fest that we require in practice not only to be able to tell a single
   fact, but to tell a series of facts. Thus we may not only wish to
   say, ' Men love liberality,' but that ' they also love bravery, and
   hate cowardice.' This constantly recurring necessity gives rise to a
   set of words whose work is to act as bondwords, binding

2) together words or sentences. These words are called Conjunctions
   (that is, conjoiners, joiners-together). The most common of these

3) are the words * And* and ^But* * And* join-

4) iDg together like things, ' But' joining unlike. Whence ' But ' is
   sometimes called a disjunc* tive particle ; because, though it joins
   the word$ or sentenceSi it disjoint the notions and marks a diference
   between them. Other conjunctions are. Also, Either --- or,
   Neither-^-nor, Though, Although, That, Therefore, Thorn, $c. 

5) How can we connect a number of statements to*

getherf (*) What are the words called which join words or

sentences f (/) What are the two most common conjunctions f (/) How does
* but' diferfrom * and'f

40 THB CONJUNCTION.

The whole class of words denoting relations of Time or Place. Aa,o{
Time, Be/ore, A/ler- wards f UntUf Then, When, Since; and of Place,
There, Here, Where, Hence, Whence, ^c, are constantly used as
Conjunctions, and merely join two clauses together with respect to their
mutual relation in Time or Place. As, ' Before he came nothing
prospered/ The particle ^hefore/ joins the notion of prosperity with his
coming. ' Where he howed, there he fell/ The particles of Place join the
notion of his

0) [@0] bowing and faUing together. If the sense of the particle stops
   at the yerb and belongs to it alone, it is an adverb, but if it goes
   on to

{^) any farther point joining the two, it cannot be right to call it
anything but a Conjunc- tion. * Them* is strictly a conjunction, and
never cor- rectly goyems a case.

(^) Conjunctive forms often govern cases, and

8) [@8] must then be called Prepositions or Case-links. Conjfu/Mtions
   therefore are particles which hind together words and sentences. No
   Conjunction can govern a Case, though some words are used in one
   place as Conjunctions, in another as Prer

(^) Are cmy words conjunctions in one place and ad-

verbs in another f (^) How will you distinguish which they are f (7) Do
conjunctive Xo^rms ever govern cases f (®) What Parts of Speech are such
words then f

THE CONJUNCTION. 41

positions or Case-links, Care therefore mtut be taken to give them their
proper name in each instance, whether Conjwnction, Adverb, or Trer
position.

PRONOUNS.

7, Thou, Who, S^c. 

Pronouns are words which stand instead of nouns.

Pronouns are classed in the following divi- sions :

Personal Pronouns, I, Thou, He, JSJie, It.

Helative Pronouns, Who, Which, That.

Demonstratiye Pronouns, This, That.

Interrogative Pronouns, Who? Which? What?

Some pronouns have formal cases.

(0 Again, directly we begin to make many state- ments concerning the
same Subject, it is ex-

3) [@3] tremely awkward to repeat the subject or noun in every instance,
   though to leave it out would often cause complete uncertainty and

4) confusion. This necessity gives rise to a set

(}) Do we never wish to make more them one state^ ment concerning a
thing f

2) [@2] Do you repeat the nov/n eoery time f

3) Then you must have something insUad o/\tf 

42

PRONOtTNS.

0) [@0] of substitutes for nouns, or Pro-nouns, which stand in the place
   of the Subject, or point back to it. Those words which stand in the

(<) place of the name, whether Person, or Thing, which is the real
Subject, are called Personal

(<^) Pro-nouns, (diat is, For-names,) and haye formal Cases and Numbers.
The Personal Pronouns are:

Singular.

Subject Form I Possessive Case my, or mine Dependent Ccue me

Subject Form Thou Possessive Case thy, or thine Dependent Case thee

Subject Form He Possessive Case his D^Mndent Case him

Subject Form She Possessive Case her, or hers Dependent Case her

Subject Form It Possessive Case its Dependent Case it

Plnral.

We.

our, or ours.

us.

You, or Ye. your, or yours, you.

They.

their, or theirs.

them.

They.

their, or theirs.

them.

They.

their, or theirs.

them.

4) [@4] What is this Substitute called f (fi) What is a Personal Pronoun
   f {^) Has it eases f

PRONOUNS. 43

Who, WhicJh That.

(^) The forms Ours, Tours, Mine, Thine, &c., it is perhaps best to
consider as Possessive Cases, not howeyer joined with their goyeming
nouns, but capable of standing separate from them. As, ' The coat is
yours/ * He has both my hat and yours/ All the Possessiye cases of the
Personal Pronouns are by some considered Adjectiyes. Besides these
Personal Pronouns, there are

19) [@19] others which do not exactly stand in the place of nouns, but
    point or relate to them. For Personal Pronouns stand instead of, and

9) [@9] represent the actual noun, as an agent in the place of his
   principal; whereas, these merely relate to it as being of such and
   such a character. Hence they are called Relative Pronouns. The
   Relative Pronoun will be in

10) whatever case the noun it refers to would be in if repeated. The
    word to which they re- late is called the Antecedent, or
    before-going word. The Relative Pronouns are Who, Which, That, and
    What. * What,' has no for-

C^) What is the difference between its two Possessive casesf

8) [@8] What are Relative Pronouns f

9) How do they differ from Personal Pronouns f

10) What case wiU Relative Pronotms he in in any

instance f What is the word they remote to coXUd^oKvA. m^{'}^

44 PRONOUNS.

mal cases ; it is equiyalent to * That which/ * Who,' * WhkV and * ^{?}V
are thus declined, or changed formally.

Singular and PlnraL

Subject Form Who lofper-

Possessive Case whose, and of whom f

I sons.

Dependent Case whom

Svibject Form Which

Possessive Ccm whose, and of which

De^penS/mt Case which

Subject Form That 1 of things

Possessive Case of that ^

j things.

 ofthii j and pei

Dependent Case that J ^

- Which/ and * T%a^/ can also be joined to nouns like Adjectives.

Tliis, That, §c. 

11) [@11] Moreover, there are adjective Pronouns which

point out or demonstrate special things ; hence called Demonstrative, or
pointing-out Pro- nouns. These are,

12) [@12] « This/ demonstrating a near object.

- That,' demonstrating one farther off. These two words show Number by
  form, but have no change for Case. Thus :

11) [@11] What are Demonstrative Pronouns f

00 ^{f}^^^ w the difermce between Uhis' <md * that^f

FRONOUNS.

45

Singular. PlnraL

This These.

That Those.

The words 'Stich/ and 'Same,' may also be considered demonstratiye
Pronouns in many instances. * Such' is often used with other Adjectives
in a manner that might seem Adverbial, but it is better to consider it
Adjectival^ as, fsuch heavy weights/ Neither of these two words have any
formal change. 0^) Other Pronouns are Interrogative, or Question-
askers. These are :

[Who? General / He, or she, or some

00

Of Persons

Persons

or Things

question re- quiring as answer

Which? Parti- ^ cular, &c. 

noun for which he or she might stand.

Some one or some- thing selected from two or more.

It, &c»

What? General, &c. 

When the Noun is expressed, /What/, is used for 'Who;' as, *What man?
equivalent to 'Who? When the question requires a selec- tion, 'which' is
to be used.

13) [@13] What are Interrogative Pronowns f

Q^) Name them, and distingviah between th/ix^.

46 PRONOUNS.

The sense alone will determine to what class of Pronouns these forms
belong, as the same form can often stand with different powers ; as,

/Who did it?/ Interrogative Pronoun.

'He, who did it, is gone/ Belative Pronoun.

NwnMraU,

- HmMi and * WJience* are not unfrequently used as Pronouns; as, 'From
  henoe arises the custom,' &c. equivalent to, 'From this quarter.'
  'From whence come wars,' &c. ; that is, 'From what quarter?' All words
  of Number are, strictly speaking. Pronouns; as, One^ Two, Each, Many,
  &c. 

15) [@15] Numerals, or words of Number, are divided

16) into two Classes, called Cardinal, and Ordinal.

17) Cardinal Numerals, are those which name the

quantity; as, ChM, Two, Three, &c. 

18) [@18] Ordinal Numerals, are those which name the

place, or order of Numbers, with reference to each other; as, First,
Second, Third, &c. 

(I'*) What are Numerals f

(1*) How divided f

17) [@17] What are Cardinal Nwrnbers f

(“) What Ordinal f

OF MOOD. 47

OF MOOD.

The Indicative or Fact-mood, ^man walks'

The verb is said to be in a Mood, when it shews the manner in which
action or exist- ence is viewed.

The Moods are, the Indicative or Fact- mood, which states a thing as a
Positive Fact, asy ^ He goes.'

The Subjunctive Mood, which represents the notions of supposition,
uncertainty, or dependence, with respect to the thing spoken of, as *
Were he to go/

The Imperative, which Commands, as, ^ Go.'

The root or original form of the verb is also said to be in a Mood, the
Infinitive Mood, as, * To Go/

To return to the Verb. The verb is a speech- word ; and in speaking of
anything, as we have seen, Time must be implied, which gives rise to the
Tenses or Time-forms of the Verb. Moreover, we must be able to point out
not only the time, but the manner, or mode in which these things present
themselves to the view ; to show, for instance, whether a thing ig
viewed as actually doing, or done; or only viewed as possible, or as an
entirely imaginary

Wh^n we say^ * man walked do we state a certain fact, or imagine what
might he f

48 OF MOOD.

1) case, and so on. This showing the manner,

2) or mode, or mood, (for the words are the same) belongs naturally to
   the verb, for the Terb speaks of action or existence ; the man- ner
   therefore of action or existence would appear to fall into its
   province. Now, as this showing the point of view is an invariable ne-
   cessity, every language must express it some- how, whether formally
   or not. There must be moods ; that is, there must be some way of
   showing the view taken of action, especially as to its dependence or
   independence; that is, of showing whether a thing is viewed as an
   independent certain fact, or as dependent on some condition or other.
   Hitherto we have viewed every sentence as containing a simple
   statement of fact ; that is, speaking of something as actually doing,
   actually done, or actually to be done; as, /I walk,' /I walked,' or
   *I will walk.' And the verb shows this of

(») itself. This is called the Verb being in the Indicative or
Fact-mood. That is, the Verb throughout a set of Tenses indicates the
mode of action ; that it is an independent and cer- tain fact, though
there is no formal change here for Mood ; the original form of the Verb

{}} What part of the sentence shows this f

2) [@2] What is the showing the manner of action called f

3) When the verb states an independent /act, what is

that called f

OF MOOD« 49

being used throughout as adapted for the Speech- clause of a Sentence.
The Fact-mood therefore^ or Indicative^ speaks of a thing as a certain
independent fact.

1) In English there is but one Formal Mood, in

2) one Tense only, but the want is supplied when

necessary, by the use of auxiliary verbs.

These auxiliary verbs are, originally, separate.

verbs by themselves, with their own separate

verbal sense, which, to avoid confusion, it will

be important to mark clearly at first.

3) [@3] The verbs used as verbs of mood, are,

x.x ,^v « « { Shall --- never denoting mood,

(*)(') Present Ten^e) ^„iy t^nse.

(«) Past ... I shovdd,

, ^ „ f will --- ^never denoting mood,

(t)Pre»mt ...) ^,„iy tense. (•)

(fi) Past . . .  would.

4) [@4] Present • • • / ^^^^ --- never denoting mood.

5) Past ... I covXd, Present • • • i wwiiy» Past ... I might,

6) 7s there any formal mood in English f

-(2) How are the other moods shown f

3) [@3] What ar^ the auonliary verbs of mood f

(}) Do ^ shall/ 'will,' or * can,' ever denote moodf

5) [@5] What parts of those verbs dof

6) Are 'shall' and 'vnll' ever atuviliariesf What do they then denote f

Question on the original seiwe o/tfejeafe msw^.

50 OF MOOD*

The original and proper sense of these yerbs is as follows :

^Can* and * could' denote the povuer of their Subject. Thus, 'he can go/
equals, 'he is able to go ;* 'he could go/ equals, 'he was able/

/May/ and ^ might* denote permission. Thus, 'he may go,' equals, 'he is
permitted/ 'he might go, equals/ he was permitted/

As 'having the power/ and 'being permitted/ are nearly the same thing,
the former im- plying that there is no obstacle internal or external,
the latter, that there is no external obstacle, 'may' and 'can' only
differ in degree; 'can' being rather the stronger ex- pression. In many
instances they are inter- changeable, and where there is a distinction,
it rather arises from ' can ' implying power in the agent, ' may/
permission from without.

'Shall' and 'should' denote necessity, whether outward compulsion, or
the inward compul- sion of duty.

Thus: 'He shall go/ equals, 'He of necessity is to go.' 'He should go/
equals, 'He ought to go.'

' Will' and 'would' denote the will or prefer* ence of the Subject.

Thus: 'He will do it,' equals, 'Ho chooses, he is de- termined to do
it.' 'He would do it,' equals, 'He chose, he was determined to do it.'

OF MOOD. 51

'Would' sometimes expresses custom. As, 'When young he would ride
constantly/ equalling, 'He -was accustomed to/ &c. 

^ Would' sometimes expresses a wish. As, 'I would you heard it/

From this usage it has passed into a mere ex- clamation of wishing. As,

' Would the custom vanish with my life/ equal* ling, ' that, &c.'

Whenever these yerbs have these direct and positive meanings, they are
not auxiliary verbs, but stand by themselves in the Fact- mood or
Indicative.

The Infinitive, * To walk/ isc,

1) The original form or root of the verb itself, is
2) also said to be in a mood, though not with strict correctness, just
   as the Subject-form of the noun is called a Case, though not properly
   a Case. It is called the Infinitive mood, (thus, ' To walk/ * To
   love/ ' To hate/ are Infinitive Moods,) or the Mood which denotes the
   sense of the verb infinitivelt/, that is, without limita- tions of
   Time, Person, Number, &c., as it
3) merely denotes the sense itself apart from all

17) [@17] What do you mean by the root of the verb f

2) [@2] Is it properly a moodf

Why not f Because it teUs nothing of the manner in which the action is
viewed as taking place* («) What does it dof

52 OF MOOD.

0) [@0] conditions. The Case-link, or Preposition Ho/ is the token of
   the Infinitive Mood, and serves to link it on in the sentence, when
   necessary, to whatever word it is joined with. Thus the Infinitive
   Mood, as denoting a simple notion, is very closely akin to a noun,
   and frequently stands as a noun in a sentence, there being but little
   difference between the Infinitive or unlimited verbal notion by
   itself, and its kin-

(&) dred noun, between, for instance, * To see' and 'Sight/ excepting
that the Infinitive Ho see,' as its name shows, denotes the most
unlimited and general notion of seeing, and cannot, accord- ingly, be
used in speaking of an individual instance. Thus, '^ovr to see* is
wrong. Whereas, 'sight' is applicable to the indivi- dual, as /f/our
sight/ The expressions are interchangeable in many instances, but always
with this limitation, that directly a particular

<{0) is mentioned, the noun, not the infinitive, must be used. The
Infinitive is also con- stantly used after the auxiliary verbs, to ro-

{^) present modifications of Time and Mood. For it is obvious, that as
Formal changes would branch off from the root, any substitute for formal
changes would naturally be some

4) [@4] How is it used in the sentence f if) Does it ever represent a
   nounf (^) How does an Infinitive used as a noun differ from a common
   noun f

OF MOOD. 53

combination with the root; and auxiliaries merely represent separately
those yarieties of sense which formal changes would represent without
separation.

he Subjunctive. *IfI might run, I should/ ^e.

Agun, it is obyious that a very large class of our impressions do not
present themselres to the mind as facts, or certainties, but as possi-
bilities, probabilities, conditionals, suppositions, &c., all with one
common notion of more or less uncertainty and dependence. To make a
broad statement, it is necessary to be able not only to make known a
straightforward

) fact, but also the manner in which anything may be conceived as
possible by the mind, or yiewed with respect to conditions. Everything
not stated as a positive actual fact, must be considered as imcertain in
some way, and

#+begin_quote
) everything uncertain depends on something. Dependence then is the
great law of this class of relations, as Independence is of actual
facts.

#+end_quote

') And as the Fact-mood or Indicative indicates a fact, not depending,
but actual and certain; so there is a Mood to show dependence^ and the
verb is then said to be in ^q Subjoined

) What do we want to express besides facts f ') Every verb stating a
fact is in what moodf Every thing not stated as a fact must be viewed in
what light f

54 OF MOOD.

0) [@0] or Subjunctiye mood; because every thing dependent must be
   dependent on something, and 9ubjoined to it.

(^) These relations, however, of dependence and independence, that is,
of Subjunctiye and In- dicative mood, slide into one another very

(^) often so imperceptibly, that it is a matter of indiiference till
written, whether a thing is stated in its certain or uncertain aspect.
Thus, in the sentences,

f are ^ V mav he J

Follow wherever you i or f led ;

may be.

the words ^ are led,' state the being led as a certainty; the words *may
be led/ transfer the uncertainty of the place whither, to the action of
leading itself. In almost every instance, excepting a purely imaginary
case, it is possible to keep the notion of uncer- tainty and dependence
separate from the verb. In EngUsh especially, a vast number of
instances, which in other languages have every shade of dependence and
uncertainty O marked by the Subjunctive mood, are stated broadly as
facts taking place under given cir-

4) [@4] What mood is the verb then said to he in f

e*) What then is the broad difference between the In»

dicative and Svibju/nctive moods f ' (^) Is it always very clearly
marked f C^) What is a common practice in English f

OF MOOD. 55

cumstances, or at a given time, and are not Subjunctiye. Thus, * Jf they
are long at peace the young men go.' The first clause, * if,' &c., which
contains the condition, would in Latin be Subjunctive, with somewhat the
sense of, * If they nuiy chance to be.' In English, how- ever, the
notion of chance or uncertainty is kept separate from the verb, and the
thing spoken of is assumed to be a fact, and the verb stands in the
Fact-mood, not affected by the conditional particle. But this is a rule
(^) both in Latin and English, that when a coiu sequence mvariably
follows on given conditions^ hoik clauses will he Indicative, Thus, ' If
it thunders it lightens.'

On the same principle. When a consequence in (9) the particular instance
certainly follows on given conditions, both clauses may he Indicative,
Thus, * If he walks fast he will he tired,*

Following out this. It will he formd possihle to

10) [@10] put every thing exerting a purely imaginary

case as certainly happening ^ on given conditions

of tim£, or circu/mstances, with the verh in the

Indicative in hoth clauses.

That is the 1st clause which contains the Con-

19) [@19] When is a conditional sentence Indicative hoth in

English and Latin f (®) What follows from admitting this principle f ^^)
What sort of sentence alone does not come under

this classification f

56 OF MOOD.

11) [@11] dition, whether put last in the sentence or 0/) not. The term
    / first/ referring to the sense,

not to the arrangement of the words in the

sentence. By the first rule. No Theorem of Euclid could

be east correctly in a Subjunctive form. Nothing stated as an actual
fact will be Sub-

junctiye, whateyer the appearances may be.

Thus, * He may go* 'May,' the present tense

of the Fact-mood or Indicatiye, equivalent to,

' He is permitted ;' an actual flsust.

Every sentence containing a pure supposi- tion and its consequence, will
have both clauses Subjunctive with Past Tenses of the verb of mood in
both.

18) [@18] In every pure supposition*, which implies that the thing
    supposed is not to be, the clause of the supposed condition, and the
    clause of the consequence or thing following on that sup- position,
    will both be in the Subjunctive mood.

19) Both clauses employing Past tenses of the verbs of mood. Thus 1st
    clause, * If I might

20) What is the first clause in a sentence f

(“) Why so called f

18) [@18] In a pure supposition what mood is usedf

19) In what Tenses will the verbs of mood always he?

- The term 'Pure Supposition* is \iaed in this work to ^{S}ffy a
  anpposition the condition of “wVv\c\i Vnv^{W}* ^C!q».\ txanaot be.

OF MOOD. 57

ran' (but I may not) ; 2nd clause, * I should be in time/ To be parsed,
or giyen account of, as follows :

- Might run/ ' Run,' original form or infinitiye mood of the verb.

- Might,' Past Tense, &c. of the auxiliary verb

- may/ forming in combination with * run' a Subjunctive mood in the 1st
  clause of a sup- position.

Any supposition which contains no implied impossibility or denial in
itself, may have whichever clause it is wished to state most forcibly,
stated as a fact with the verb in the Indicative or Fact-mood.

In the preceding example the whole matter is treated as what, though
possible, is not to he, and the construction of that example is then the
strictly correct construction. P) But very often the supposition does
not imply (*) impossibility or denial of any sort, but merely more or
less uncertainty; and though that which is not to be, cannot correctly
be taken for grant- ed or correctly put in the Indicative, an uncer-
tainty is very often taken for granted, either (3) as certain under
given conditions, or in order

(}) Do aU 8uppo8iti(m8 imply impossibility or denial f («) What do thsy
often imply f (*) In mch instances^ is part of the «wp']^o«ttVwv «<iw
assumed to he certain^ Whyf

58 OF MOOD.

to add yividness and reality to the statement. Where then the
supposition merely implies uncertainty, part will not unfrequently be 0)
taken for granted, and consequently put in the Indicatiye mood. Thus, in
the 1st clause, /K I ran;' 2nd clause, /I should be in time/ 1st'
clause, *Jf here you housed him;' 2nd clause, 'Here he would have been.'
Both these first Clauses are positiye and equivalent

A XX f myrunmng to, state < « V • u- » I 'your housmg him'

as a fact, such

and such a consequence would follow. When- erer an Indicative is put in
either clause of

0) [@0] a Supposition, it implies that that clause is assumed as a fact.
   An Indicatiye, therefore,

(/) ought never to be used in a pure supposition the terms of which
imply that the supposed case is not to happen. It will happen, however,
much more frequently that the Consequence will be represented as certain
with its verb in the Indicative, follow- ing on an uncertain condition
in the 1st Clause, with its verb in the Subjunctive. As, 1st, / If it
should rain' (possible); 2nd, 'I will not go.' 1st, * If / should pay
your worship blows again' (possible) ; 2nd, * Perchance you will not
bear them patiently.'

4) [@4] IfsOf how is the verb affected? (*) What does an Indicative in
   the clause of a sup^ position imply? (V When is it not correct to use
   aw ludixiatiw f

OF MOOD* 59

Again, in a supposed case the sentence often appears to consist of but
one clause, the con- dition standing as the Subject, where the con-
dition is not improbable. Thus, 'It would make a man mad as a buck to be
so bought . and sold/ Here the condition is implied in the words * to
be,' &c., which are equiyalent to, grant a man was so bought, rather
implying that he is so. /I should kick being kicked,' is a somewhat
similar example, equivalent to, ' If I was kicked (no improbability) I
should kick.' Moreover, the conditional, or 1st Clause, is very often
not expressed but understood. As, ' / would not change this hue except
to steal your thoughts;' that is, 1st Clause, 'If I could.' 'Dead! he
would have clapped in an arrow at twelve score ;' that is, 1st Clause, '
If he had been required to do so/ ) Sometimes indeed it is not necessary
or con- venient to fill up these suppressed conditional clauses; it is
sufElcient to recollect that this sort of sentence implies a suppressed
condition, and to say concerning it, / would,' a Subjunctive

) Sometimes the sentence seems to he but one clause^

explain this. ) When ^uill the condition stand as the suitject f ) Is
the conditional clause a^uoaijft e>xi^{Te,«%«}^ ) Or the consequence ?
jDoes this signify ?

60 OF MOOD.

mood/ &o. in a Supposition, first clause un- derstood or suppressed.

4) [@4] Occasionally the second clause or consequence is understood ;
   as, ' If I were coyetous, how am I so poor ? The complete sentence
   would be, ' If I were covetous I should be rich, how then/ &c. 

5) A probable conjecture, if subjunctively expressed, will be generally
   expressed by present sub- junctires. But both clauses will seldom be

(0 in the Subjunctiye Mood; as, 'If thou keep promise (as I expect you
will) I shall end this strife.'

Of ^ May* ^c. m a 1»< Clause,

No Present Tense of a verb of Mood will be Subjunctive in the
Conditional or 1st Clause.

As whenever a pure Supposition is made, the Q) Past Tenses must be used,
and this is the only (^) instance which absolutely requires subjunctive

17) [@17] When the conjecture is very probable, wJiat tuiU

the consti*uction hef (2) Will both clauses often be subjvmctive f (8)
Why notf

17) [@17] What is the special mark of a pure supposition f If Present
    Tenses are used, what do we know ai ancef (^) WTiat is the only
    instance wlitcK must \astA SxJb^ Junctivea f

OF MOOD* 61

moods, it will much simplify matters when- eyer all doubtful cases can
be made to fall under one head. Now' in theory there is nothing to
hinder every Ist Clause of a con- ditional sentence, where the verb is
in the

(*) Present Tense, haying that yerb in the In- dicatiye or Fact-mood,
the Conditional particle

(/) being only equiyalent to / grant the /(zct,' In practice it will be
found that eyery Present Tense of an auxiliary yerb in such 1st Clauses
com be thus dealt with. Let this then be a rule.

(/) No Present Tense of an auoDiLiary verb will he Stibpmctive in a let
Clause Thus, /If I may go,* &c. ; * May go,* is equivalent to * am per-
mitted to go/ and /may/ is a regular verb in the Indicative or
Fact-mood.

The Dependent Clause, * I walk thai I ma.yl $c. 

Whenever auxiliary verbs of Mood occur in the dependent Clause they are
Subjunc- lives.

Hitherto we have treated of supposed cases and their modifications, in
which the sentence is divided more or less expressly into two separ-

8) [@8] What is the conditionalparticle oJUneqmvale/nt tof
9) WTien a thing is taken for granted, what mood

will the verb beinf (0 What is the rule unth respect to tl^ •prewsat.
Vsrc^afe of the auxiliaries in a firvt clauael

62 OF MOOD.

ate clauses, the 1st containing a condition tc^ be supposed or granted,
the 2nd contuning- the consequence resulting from it. Bat there is
another very large class of notions, to which, when expressed, the name
dependent is especially fixed, which differ from those above mentioned
in not being suppositions at all. Tlieir distinctiye character is
growing

(}) out, or branching off from some principle fact on which they depend.
Tlius, 'I walk that I may be healthy.* The being healthy is stated as
dependent on the walking. And from this leading notion, wheneyer a
clause in which there is a verb, in any way grows out of a preceding
statement, that clause is said to be dependent. Thus, *I think that you
may be in time.' The clause ' That,^ &c. is dependent. This is a rule:
Whenever aux-

2) [@2] iliary verbs of mood occur in the dependent

daueCi they represent the Stttjunetive; as, ^sur

perfiuous branches we lop away, that bearing

boughs may live* It is quite possible, how-

eyer, that after the same first clause and the

same conjunction, there should be a yerb in

the Fact-mood or Indicatiye. As, Ist clause,

T 1 -rw rN / XI- X he may come, Subj.

I know, D.C.  that . , ^ -n^ j.

( he IS come. Fact-mo

-mood.

(}) What is a Dependent clause f (2) When auxiliary verbs of mood occur
in such a clause, what is the rule 9

OF MOOD. 63

In some few instances, the verb ^ may ' in the dependent clause is
emphatic, and equivalent to Ms permitted/ it must^then be Indicatire. (0
The reason why dependent clauses, such as 'that he is come,' are not
Subjunctiye, and therefore do not require verbs of mood, will appear if
we consider that such clauses re- present a simple noun. Thus, ' he is
come,^ is equivalent to * his arrival/ Whereas, if we write 'that he
nuiy come/ this equals 'the possibility of his coming/ Now the notion of
mere 'possibility' is one of those very dis- tinctions which mark off
the Subjunctive from the Fact-mood. Whenever 'that' equals 'in order
that/ the dependent verb must be Subjunctive.

The SubjwncUve. * I should say *

The Subjunctiye Mood is used to express an pinion in a modest and
inoffensive manner.

From the notion of uncertainty and doubt being

a prevailing one in the Subjunctive mood, has

'0 arisen in most languages its use in giving an

opinion, as, ' I should say/ &c. Not that any

') How comes it, that after tJie same first clause and conjunction^
there can he either an Indicative or Subjunctive f

What mood do you use in gvomg an opinion f

64 OF MOOD.

^3) uncertiunty is necessarily implied, but it is felt to be too abrupt
to put out an opinion

19) [@19] positively at once ; as, ' I say/ Hence arose the use of the
    Subjunctive to soften the harshness of the direct statement. The
    Sub-

(0 junctive mood therefore is used to express an opinion in a modest and
inoffensive manner, as, 'It may be doubted whether Bacon did justice to
him.'

The Subjunctive Mood is used in prayers and wishes.

17) [@17] The Subjunctive Mood will be used in prayers and wishes, as, *
    For ever may my knees grow

{2) to the earth/ Properly speaking, every wish has a verb or
exclamation of wishing suppress-

3) [@3] ed ; thus, * I pray that for ever,' &c., would be the sentence
   completed ; and the verb of mood

6) [@6] is really in the dependent clause.

2) [@2] Is any tmcertainty really implied f

3) Why is not the Indicative usedf

0) [@0] What is the meaning of the Subjunctive in su^h sentences f

(}) How will prayers and wishes he expressed f

(*) Is the construction of the sentence generdUy com^

pUtef (8) When completed, what clause will the Subjunctive

beinf (^) And what will he the true explanation of the moodf

OF MOOD. 65

1) In every rerb the Present Tense Subjunctive

may h^ formally expressed by cutting off the afl&xes which mark Person
in the Fact-mood or Indicative. As, 'Kthou walkest/ Fact-mood.' K thou
walk, if he walk/ Subjunctive. As, 'There take thou that till thou bring
better news.' *If your will j?aw, I shall both find your lordship judge
and juror/ The old

2) [@2] Present Indicative of the verb *to be/ is used

3) sometimes as a Present Subjunctive to the (^) verb * I am/ though
   found in its original sense

occasionally, and ' I were/ &c. is always used (^) as the Past Tense
Subjunctive of the same verb. Thus, * II he were living I would try (6,
-T) him yet/

/0 were' is the proper Subjunctive of the de- fective verb /was/ The
rules then which decide whether a combi- nation is Subjunctive or not,
are these : 1st. No sentence will have either clause Subjvnc^

1) How is the Present Tense Subjunctive formally

expressed f

2) [@2] Has the verb */ am^ ever a formal Subjunctive

Present f (8) What is* I be* originally f (4) Is it ever used in its
original sense f (fi) Has * / am' a Past Tense Subjunctive f (®) What is
' I were ' originally f (7) Is it strictly used in its original sense f

66 OF MOOD.

tive wlien a consequence invariably follows on given conditions. As, *
If it thwnders, it lightens J

2nd. Nothing stated as a fact wUl he Subjwnc” tive, whatever the
appearances may he. As, * He may go* Fact-^mood,

Ist. Every sentence containing a pure supposition will have the clauses
of the condition and conse- quence hoth Suitjunctive, with past tenses
of the verh of mood in hoth. As,

- If the skin were parchment, and the hlows

you gave were ink, Your own handwriting would tell you what I think*

2nd. Any supposition which contains no implied impossihility or denial
in itself, m>ay have the conditional or Ist clause with the verh in the
Indicative or Fact-mood, the condition heing taken for granted, whilst
the consequence or 2nd clatuse may still he Subjunctive, As, * If here
you housed him, here he would have heen*

3rd. Often£r stiU the consequence will he stated as a fact, whilst the
Ist clause is Subjunctive, As, *If I shovM pay your worship hlows again,
perchance you will not hear them patiently,'

No present tense of a verh of mood will he Sub- junctive in the
conditional or Ist clause,

4th. Whenever auxiliary verbs of mood occur in the dependent clause,
they are Subjunctives. As, * Superfluous branches we lop away, that
hearing houghs may live*

OF MOOD* 67

Sth. The Subjunctive mood is used to esopress an opinion in a modest and
inofensive manner, ASf * I should «ay/ not, * I say!

6th. The Suibjimctive mood is used in wishes and prayers, * As, For ever
may my hnees grow to the earth.*

It is difficult sometimes to fix the mood of questions. This difficulty
may be got over by putting the clause in a direct manner with the
question last. Thus, 'How were they lost? They were lost. How? Would not
this do well ? This would do well, would it not ?'

Not unfrequently exclamatory expressions act as verbs, and have
dependent clauses. As, * Good heavei^ that nobles should such sto- machs
bear.' * Good heayens' is equal to, ' How I wonder,' or some such
phrase^

It must be borne in mind, that 'would,' when in the Indicative or
Fact-mood, is the Past Tense, and equivalent to ^wished! not to
'wishes,' excepting in the single expression, 'I would,' which has
become a Present by usage. Because in Subjunctive clauses, 'would'
4»nnot unfrequently be rendered as equivalent to 'wishes;* but this is
not allowed; as, 'He prays but faintly, and would be denied.' If 'would'
was a Present here, it would make sense as a regular verb in the
Indicative or Fact-mood ; but its being a Past Tense, which does not
make sense, marks it at once as Sub« junctive with a suppressed 1st
ClausOi The

68 OF MOOD.

real difficulty of this, and many similar in- stances, arises from the
fact, that in sense the yerb is not properly auxiliary at all, but the
Subjunctiye of its own yerb, and equiyalent to * would wish;* the
auxiliary sense of mood, and the non-auxiliary sense of the original
yerb, being confusedly blended together in the same word in the same
passage. In the absence of clearer marks and formal Moods, I trust these
will be sufficient to enable eyery one in doubtful instances, which are
numerous in all languages, to examine his ground, and giye a reason for
his opinion in any particular example.

SUBJUNOTIVB CONSTRUCTIONS.

The Supposition,

^But should she thus be stolen away from you, it would he much yexation
to your age.'

^Were you well served, you would he taught your duty.'

*I would not spare my brother in this case, if he should scorn me so
apparently.'

- If you were civil and knew courtesy, you would not do me so much
  ii\jury.'

*Khe would despise me, I would forgiye him.'

- If he should hreah his day, what should I gain f

- If / could add a lie unto a fault, I would deny \V 

SUBJUNCTIVE CONSTRUCTIONS. 69

*lfhe were living^ I would try him yet/ ^11 he were honester, he were
much goodlier/ 'I were but little happy, if I could eay how

much/

' If / zhofMi live a thousand years, I never should

forget it J

First Clause understood.

^I would you were half so honest, men's pray-r ers then (if you were)
wouM seek yott, not their fears/

'Now I dare not say I hare one friend alire, (if I were to say it) thou
would^st disprove it.'

(If served properly) 'He wotdd have chipped bread well/

' Welcome is banishment, (if I were to die) wel- come were my death/

'It would seem strange unto him (if it were done) when he waked/

' I would not change this hue (if I could), ex- cept to steal your
thoughts/

' Gold u)ere as good as twenty orators/ (If it were given).

' Grief would have tears/ (If it were gratified).

'I would I were thy bird, Sweet, so would I, yet (if you were) I should
kill thee with much cherishing.'

Second Clause understood.

' If / utere covetouSf (I should be rich) how am I so poor ?*

70 SUBJUNCTIVE CONSTRU0TIOM8*

^ And out of doubt you do me now more wrong than (you would do me) %f
you had made waste of all I haye/

' What (would be the risk) if it tempt you toward the floods my lord,
and there assume some other horrible form/

First Clause Indicative,

- If you had your eyes, you might fail of knowing me/

*lf I answer not^ you migT^ haply think Tongue-tied ambition yielded/

- If you did know to whom I gave the ring,

Tou would abate the strength of your displeasure/

- If you had known the yirtue of the ring,

Tou would not then haye parted with the ring/ 'If / had my mouth, I
would bite/ 'I should flout him, if he writ to me/ 'If your leisure
eervedy I would speak with you/ 'If I thought that, Fd forswear it/

- If you prized my fnyour, you toould not* &c.  ' Had I it written, I
  would tear the word.'

'An if a man did need a poison now, Here liyes a caitiff wretch would
seU it him/ 'If you but said it, 'twere as deep with me/

Second Clause Indicative.

' Should I have wished a thing, it had been this/ ' Though I should die,
I will not/ ' Were it further off, Fll pluck it down/ 'If I should pay
your worship blows again, Perchance you will not 6ear. them patiently/

SUBJUNCTIVE CONSTRUCTIONS. 71

^ Were the world mine, Demetrius being bated. The rest Fll gire to be to
you translated/ ^ Thou wrongst thyself, if thou shoulcPst strive to
choose.

^ An I might Uve to see thee married once I hcwe my wish/ ^ ril speak to
it, though hell itself should gape* ^ Thejwill «ay afterwards,
iftheysTumldgrow/Sic.

- Nor vnll it yield to Norway or the Pole A ranker rate, should it he
  sold in fee/

The Condition implied,

^ I should Uushy I know. To he overheard and taken napping so/

(If I was orerheard.) ^ /T'were pity they should lose their father^s
land.' /It were hetter you troubled him/

- Tojly the boar before the boar pursues. Were to incense the boar to
  follow us/

'I should kick heing kicked, and heing at that pass You would keep from
my heels, and beware of an ass/

- I would outstare the sternest eyes that look To tuin thee, lady.'

*And yet to he afraid of my deserving. Were hut a weak disabling of
myself,' ^ I would lose all to deliver you,'

^ But for your company, I wcyuld have heen a bed an hour ago/

Probable Condition <md consequence.

- If fortime serve me, ni requite this kindness.'

- If it prove so, I wfUl he gone the sooner/

73 SUBJUNCTIVE CONSTRUCTIONS*

'If the wind blow any way from shore, I will not harbour in this town
to-night/' If thou ke^ promise, I shall end this stri^/

- If your wUl pasSf IshaU both find your lordship judge and juror/ 'If
  she agree within her scope of choice Lies my consent/

/ru look to like, if looking liking mow; ^Or if he do, it needs must be
by stealth/ /ril cross it, though it blast me.* 'What if it tempt you
toward the flood, my lord. And there assume some other horrible form/

'If it live in your memory, Begin at this line/ 'For murder^ though it
have no tongue, wiU speak/

'If he but blench, I know my course/

Dependent Clauses,

' Pray hearen he prove so when you come to him/

'I wonder much Huxt you would put me to this shame and trouble/' Look
thou meet me ere the first cock crow/ 'And from each other look thou
lead them thus/

' O that clear honour Were purchased by the merit of the wearer/ ' Here
take thou that till thou bring better news/

- You swore to me That you would wear it till the hour of death/

SUBJUNCTIVE CONSTRUCTIONS. 73

^ And tell them there thy fixed foot shall grow Till thou have
audience.'

- O teach me how I should forget to think/ 'Let me stand here till thou
  remefmher it/

' Parting is such sweet sorrow. That I shall say good night till it he
morrowJ

- He said he would,'

- See thou deliver it to my lord and father/

OF MOOD.

The Imperative, * Walk liome*

1) There is one more relation requiring to be ex-

pressed, that of commanding actions. This

2) [@2] giyes rise to an Imperative or Commanding i}) Mood ; which
   howeyer, in English, only has a {4) second Singular and Second
   Plural; as>

Walk. 2nd Sing. Walk. 2nd Plu. A command to a third person or persons is
conTeyed in English by die formula, Let him, (ft) or them, do so and so.

The Moods, then, or changes and combinations of the rerb to denote the
manner in which an action is viewed as taking place, are as follows :

1) What other relation requires to he expressed f

2) Does the simple verh express it 9

3) Whoit is this mood called?

4) In what persons alone is it used f (*) How are other commands given f

74 OF MOOD»

The Fact-moodf or Indieative, which incRcaieB a fact as actual.

The Suhjunctivef whi(^ denotes siuppositionf unr certainty, and
dependence.

The Imperative^ which denotes commands.

Besides the original form or root of the^ Verbf which is also called a
Mood; namely f ^ Infini- tive Mood,

THE INTERJECTION.

M! Alael

(}) There is one other Part of Speech called an Interjection, or thing
thrown in; that is, an ex-

2) [@2] clamation of surprise, sorrow, joy, &c. thrown suddenly into a
   sentence; as. Ah, Alas. In* terjecti(His generally do not affect the
   con-

3) struction, but sometimes they act as Case-links

4) or Prepositions, and should then be called (Ji) Interjectional
   Case-links ; as, ' Ah me/ Some- times they haye clauses dependent on
   them ; as, ' that my prayers could such affection

5) move;' in which instances they act as Verbs.

6) What is an Interjection f

7) Does an Interjection affect the constt^xiction pro-

perly f

3) [@3] State any instance in which it does,

4) What is it then f

(fi) State another instance, (^) What is it then 9

THB COMPOUND SENTENCE* 75

THE COMPOUND SENTENCE.

Of marCa first disobedkncef $c.  Sing heavenlt/ muse who, i^c. 

We ha^e thus gone through all the Parts of Speech which, as single
words, represent what

(}) passes in the mind in simple Sentences. These Parts of Speech
represent every class of notion that can exist; therefore if, in any
instances, notions are not expressed bysingle words, what-

3) [@3] eyer the expressions may be, they do repre- sent some Part of
   Speech or other; just as a Pronoun does stand in the place of a Noun.
   Now, in examining words, we found only the more common relations
   represented /bnna%.* for Jbrmal changes depend, not on the neces-
   sity, but on ^e/reqttenct/ of the relation to be expressed ; just so
   with respect to the Parts of Speech themselves. Single words only ex-
   press the most frequent notions ; whilst facts

4) innumerable, things, qualities, &c. are expressed by combinations of
   words ; and these combi- nations are often complete sentences in
   them** selres. Thus it is possible for a Sentence to consist of many
   clauses, each clause represent-

0) [@0] Whca do Parts of Speech express f

3) [@3] If (my notion is expressed in more than one word

what will those words represent f (8) Is it possible for a sentence to
he made up of

little sentences f

76 THB COMPOUND 8BNTBNCB.

ing some Part of Speech, and each, as far as

(^) construction goes, a Sentence in itself. And

5) [@5] such a Compound Sentence cannot be con-

6) sidered as mastered till every such clause is

resolved into the Part of Speech it represents,

whether Noun, Substantive, Adjective, Adverb,

or, &c. and is stated as a Substantival, Adjeo-

tival. Verbal, Adverbial, or Interjectional

clause. Let us examine on this principle the

first ten lines of Milton's Paradise Lost.

Of Man's first disobedience and the fruit Of that forbidden tree, whose
mortal taste Brought death into the world and all our woe. With loss of
Eden, till one greater Man Bestore us and regain the blissful seat.
Sing, heavenly Muse, that on the secret top Of Oreb, or of Sinai, didst
inspire That Shepherd, who first taught the chosen seed, In the
beginning how the heavens and earth Bose out of Chaos.

4) [@4] What is such a sentence called f

5) What are its parts called?

What is a sentence called the parts of which are single words f (^) In a
compound sentence what must he done f Can there he any clause which does
not stand/or some part of speech f

THE COMPOUND SBNTBMOE.

77

S

I

Cu

“S

g

•i-i

.s

02

^

<

§•

02

15 2

^1

«<«

1

o .

4* kA

L * «8

'iJ to

S G '9 .5 .5 ^ -^ g

;s»^ J*^ ^ H^ ^ S-

78 OF VOICE.

OF VOICE. / am loved.

A verb is said to be in a Voice when it shews whether one acts or is
acted on. There are two Voices. These Voices are called the Active
Voice, and the Passive Voice, or Voice of Endurance.

There is no formal Passive Voice in English.

2) [@2] There is a necessity for expressing not only

what we do, but also what is done to others or

ourselves. In some languages, the Verb expresses both

these distinctions formally throughout all its (1) tenses and moods, and
is then said to be in (8) the Active voice, when it expresses acting on

others ; and to be in the Passive, or Enduring (0 voice, when it
expresses being acted on by (s) others. There is no formal Passive voice
in (^) English, though there is one Passive word, the

Passive Participle ; as, Loyed. This necessity

1) What is the meaning of Voice f

2) What necessity gives rise to it f

6) [@6] What voice is a verb said to he in when it speaks of ^ action
   on* f

4) [@4] What voice is a verb in when it denotes ' being

acted on hj' ?

5) [@5] What is the only Passive word in English ? {^) Is there a formal
   Passive voice in English f

. OF VOICE. 79

17) [@17] finds expression through auxiliary Verbs joined to the Passive
    Participle ; as, ' I am lored/ &c.  The words ought to be accounted
    for sepa* rately, and then it may be said, if required. Combination
    representing Present Tense, Pas- sire Yoice, 1st Person, Singular
    Number, of the yerb ' to love.' These combinations how- ever require
    no new rules, but follow al} the laws of the simple verbs.

MISCELLANEA.

Nouns,

Such names as denote any of the individuals that are contained in a
class of things, are called Vommon Nouns; as. Tree, Gate.

The names of persons and places are called ^oper names; as, London,
Henry.

An abstract noun, is the name of a quality/ or property; as, virtue^
conceived by the mind as ex- isting by itself.

The names of things that really do exist, a^, fTuin, are called Concrete
Nouns.

That.

The word ' That* is puzzling sometimes, as it does the work of three
distinct words.

(') How is the necessity for one supplied f

BO MI80BLLANBA.

iBt. It is a DemonstratiYe Pnmoun; a8» ^This elerk said yea, that other
nay/

2Qd. It is a Belatire Pronoun ; as, ' Why dost iliou wrong her that did
ne'er wrong thee ?'

3rd. It is a Gonjanction; as, 'I wonder much that you would put me to
this shame and trouble/

Participial Substantives.

'Thou hast been as one in suffering all that suf* fers nothing/

It is very necessary to observe carefully the Participial Substantives,
which in form differ in no respect from Participles ; and when of the
active form govern the cases of their respective verbs, but yet are used
exactly as nouns. 1st. They have Articles and Adjectives joined to them.

2nd. They stand as the subject of sentencesy or are governed by Verbs
and Prepositions or Case- links. They are like Participles therefore in
fomij and in sometimes governing a case.

But in every other respect Nouns, capable o being limited by articles,
qualified by Adjective/ standing as Subjects, and being governed by Verl
and Case-links or Prepositions; as, 'This suddc sending him aw&j must
seem deliberate/

' He grew into his seat ; And to most wondrous doing brought his horse.

Had --- Had, Were --- Were*

A very common way in English of express! supposed case which nearlt/
took place, but did n

MISCBLLANBA, 81

to represent it as actually a past thing; but for a pre- venting
circumstance also actually past, the Past Indicatire ^had* being used in
both clauses; as,

- Which had returned to the inheritance of Fortinbras had he been
  conqueror/

This gives great yiyidness and reality to the supposition. And in fact,
in English, this Lidicatire construction has become, to all intents and
purposes^ Subjunetiye in sense.

It is not uncommon to find the Subjunctire /were/ used in the 2hd Clause
of a Sentence, with the sense of * would be,' or * would have been ;'
as^

- If he were honester, he were much goodlier/

Ought,

The word * ought' is an example of the changes of sense brought about by
usage. * Ought,' is pro- perly the Perfect Tense of the rerb to owe,
with the sense, /wa8 dd)tor' It is now used as a present, with the sense
/is (morally) debtor;' * His duty is;' as, * The watch ought to offend
no man.' Notwith- standing this, in the expression, ^ He ought to hare
done it,' and the like, it retains its original past tense. Thus we have
the word ' ought' acting both as a Present and a Past Tense according to
the context.

The Present Passive,

It will be found on examination, that the com- bination which has been
called the Present Tense Passive, is only a Present Tense as far as
telling the present state of a completed action. But where

82 MISCELLANBJL

it is necessary to express the strictly present sense of the state of an
action going on, it gires us no assistance. To meet this difficulty, the
English lan- guage either employs the round-about combination of the
Participle of the auxiliary yerb ^to be^' with the Passife Participle;
as, 'The house is being ImUi an expression which, in reality, declares
that a ^axag is going on, and finished at the same time ; or else it
makes the Present Participle Actire serre in a Passire sense; as, 'The
house is building,' ^Qotn is selling,' 'Lodgings are letting/

Tables.

Nouns generally form their plural number by adding s and es to the form
of the singular number.

Most nouns ending in for fe change the f or fe into ves to form the
plural number; as, eai/f ccUves, &c. 

A few nouns take the termination en; as ox, oxeUf &o.

Nouns ending in y preceded by a consonant change the y into ies for the
plural ; as, dut^, duties*

Nouns are thus declined :

Singular. FloraL

Subject Form Friend Friends.

Possessive Case Friend's Friends*.

Dependent Case Friend Friends.

Subject Form Child Children.

Possessive Case Child's Children's.

Dependent Com Child Children.

lUSCELLANEA.

83

Singular, Plaral.

Subject Form Lady Ladies.

Possessive Case Lad/s Ladies'.

Dependent Cttse Lady Ladies.

Subject Form Calf GaWes.

Possessive Case Calf's Calves',

Dependent Case Calf Calyes.

Adjectiyes generally form their Comparative and Superlatiye degrees by
adding er and est to the original form; as, gmck. Com. quicker, Sup.
quickest.

The following adjectiyes are irregular in the formation of the
Comparatiye and Superlatiye.

Bad I

evil r worse worst.

ill J

farther

Far Fore

Good Hhid

In

Lato

Little

Many ) Much/

former

better hinder

inner

f later I latter

less more

farthest,

{foremost, first, best.

{hindmost, hindermost. f innermost, ( inmost.

{latest, last.

least, most.

84 UI8CELLANBA.

Out outer j outermost,

( utmost.

Up upper j uppermoBt,

I upmost.

Tables of the Pronouns are given at page 42.

TABLES OF VERBS USED AS AUXILIARIES.

Infinitive Mood (or Root). None.

Indicative Mood, or Fact-Mood.

Present Tense. Singular. Plural.

I may We may

Thou mayest You may

He may They may.

Past Tense. Singular. Plural.

I might We might

Thou mightest You might He might They might.

TABLBS OF VERBS USED AS AUXILIARIES. 85

Infinitive Mood (or Boot). None.

Indicative Mood, or Fact-Mood,

Present Tense. SiDgolar Floral.

I can We can

Thou canst You can

He can They can.

Pcist Tense. Singular. Floral.

I could We could

Thou couldest You could He could They could.

Infinitive Mood (or Root). None,

Indicative Mood, or Fact-Mood*

Present Tense. Singolar. Floral.

I shall We shall

Thou shalt You shall

He shall They shall.

Past Tense. Siogolar. Floral.

I should We should

Thou shouldest You should He should They should.

86 TABLBft OF VERBS USBD AS AVXlUAXIEtU

Intinitite Mood (ob Boot). To will.

IZYDIOAtXYE M0OD9 OE FaOT-MoOD.

Fre»ent Tenae,

Singular. PloraL

I will We wiU

Thou wiliest, or wilt You will

He willeth, or will They will.

Past Tense, Singular. PloraL

I would We would

Thou wouldeet You would

He would They would.

The forms * wiliest' and 'willeth' and the In- finitive mood are never
auxiliary.

Infuotive Mood (or Root).

*Tobe.'

Indioatiye M00D9 OK Fact-Mood.

Present Tense. Old Form,

Singular. Plural. Singular, PluraL

I am We are I be We be

Thou art You are Thou beest You bo

He is They are. He be They be*

Past Tenses.

General Notion. Singular. Plural.

I wM We were

Thou wast XovL^{ct}

He waa T\ic:j^{«t}«

TABLES OF VERBS USED AS AUXILIABIB8. 87

Emphatic Time, or Perfect, Singular. Plural.

I have been We hare been

Thou hast been Tou have been

He has been They have been.

Completed Action, or Pluperfect, Singular. PluraL

I had been We had been

Thou hadst been Tou had been

He had been They had been.

Fixture Tense. Singular. Plural.

I shall, or will be We shall, or will be

Thou shalt, or wilt be Tou shall, or will be He shall, or will be They
shall, or will be

SirBJUNCTiYE Mood.

Presmt Te7i$e, Singular Plural.

I be We be

Thou be Tou be

He be They be.

Dq>endent Present, Singular. PluraL

I may be We may be

Thou mayest )e Xoxi mv^ \i^

He may be 't\ic^ mv^{V}^-

88 TABLES OF YBRBS U8BD A9 AUXILIARIB8;

Past Tenses.

General Notion.

Singalar.

Floral.

I were

We were

Thou wert

You were

He were

They were.

Perfect.

Singular.

Floral.

I could be

We could be

Thou couldest be

You could be

He could be

They could be.

Other auxiliarieB, 'should/ 'would/ 'might.'

Plii^erfect, Singolar. Floral.

I could have been We could hare been

Thou couldest haye been You could have been He could hare been They
could hare been.

Other auxiliaries, 'should/ 'would/ 'might.*

Imtebatiye Mood.

Singolar. Floral.

Be Be.

Participles. Fresent. Fast.

Being Having been.

The Past Participle heeriy is seldom used out of combination.

TABLES OF VBRBS USED AS AUXILIARIBS. 89

iNFuaTivB Mood (or Boot). * To have.'

XZIDIGATIYE M00D9 OB FaOT-MoOD.

Present Tense, Singolan Plural.

I have We have

Thou hast You have

He has They hare.

Combination for Imperfect Tense, Siognlar. PlnraL

I was having We were having

Thou wast having You were having •

He was having They were having,

Pctst tenses.

General Notion. Singular. Plural.

I had We had

. Thou hadst You had

He had They had.

JSmphatie Past Time, or Perfect, Singular. Plural.

I have had We have had

Thou hast had You have had

He has had They have had.

Emphatic Past Action, Singular. PlnraL

I did have We did have

Thou didst have You did have

He did have They did hare.

90 TABLES OF VERBS USED AS AUXIUARIES;

Completed Action, or Pluperfect, SiDgolar. Plaral.

I had had We had hisul

Thou hadst had Tou had had

He had had They had had.

future Teme, Singular. Floral.

I shally or will have We shaH, or vnU have

Thou shalt, or unit have You shall, or toiU hare He shall, or unU have
The^ shall, or wiU have.

Subjunctive Mood,

Present Tenses. Singular. Plural.

I have We have

Thou have You have

He have They have.

Dependent Present. Singular. Plural.

I may have We may have

Thou may est have You may have

He may have They may have.

Imperjkct Tense, Singular. PJural,

I were having We were havhig

Tiiou wert having ' "You^{er}VwYa^ He were having"I^^l N?eT^\is?f«^.

TABLES OF VERBS USED AS AUXILIARIES. 91

Past Tenses.

Perfect. Singular. PlaraL

I could hare We could hare

Thou couldest hare Tou could have

He could have They could hare.

Other auxiliaries 'should/ 'would/ 'might.'

Pluperfect. Singular. Floral.

I could have had We could have had

Thou couldest have had You could have had

He could have had They could have had.

Auxiliaries as above.

Impebatiyb Mood. None.

Participles. Present. Past.

Having Having had.

The Past Participle had is never used out of combination with a
Transitive sense.

92 TABLE OF A RBOULAR TEBB.

TABLE OF A BEGULAB VERB.

ACnVB VOICE.

iHjfmiTivE Mood (ob Boot). * To lore.'

Irdioatite M00D9 OR Fact-Mood. Present Tenses,

General Notion. Singular. PlnraL

I love We love

Thou lovest You love

lie loves They love.

EmphaUc Time. Singular. Floral.

1 am loving We are loving

Emphatic Action. Singular. Plural.

I do love We do love

Thou dost love You do love He does love They do love.

Imperfect Tense. Singular. PluraL

I wsiB loving “VI ft 's^etft VsTflv^

&c. ^^»

TABLB OF A REGULAR TBRB.' 93

Pcut Tenses.

General Notion.

Singular. Plural.

I loved We loved

Thou lovedst You loved

He loved They loved.

Emphatic Time, or Perfect. Sing^ular. Plural.

I have loved We have loved

Emphatic Action. Singular, PlanU.

. I did love We did love.

Thou didst love Tou did love He did love They did love.

Completed Action, or Pluperfect, Singular. Plural.

I had loved We had loved

Futvre Tense, Singular. Plural.

shall, or will love We shall, or will love

Subjunctive Mood.

Present Tenses. Singular. Plural.

I love We love

Thou love XwslVss^

He love 1^a»l ^^^{'}

94 TABLE OF A RBGULA& TBR8.

Dependmt Prese/nt. Singalar. Plural.

I may lore We may lore

Im^per/ect Tense. Singfolar. Plural.

I were loYiDg We were loving

Thou wert loying You were loYing

He were loying They were loying.

Pcut Tenses,

Perfect, Singular. Plural.

I could loye We could lore

&c. &c. 

Other auxiliaries, * should/ 'would,* 'might.'

Pluperfect, Singtilar. Ploral.

I could have loyed We could have loyed

&c. &c. 

Auxiliaries as above.

LiFEBATiyE Mood.

Sing^nlar. Plural.

Love Love.

Pabtioifles.

Present , Loving. Past. . . Having loved.

The Past Participle * loved' \ft ne^cc w&^^ csvit of combiDAtion with a
TranBitivo Ewi%e»

TABLE OF A RXOULAR VBRB. 95

Passitb Voice.

Infimtive Mood, * To be loTed.'

Indicative Mood or Fact-Mood.

Present Tense. Singular. Plural.

I am loved We are loved

&c. &c. 

Imperfect Tense. Sing^ular. Plnral.

I was being loved We were being loved

&c. &c. 

Past Tenses,

General Notion. Singular. Plural.

I was loved We were loved

Emphatte Time or Perfect. Sing^ular. Plural.

I have been loved We have been loved

&c. &c. 

Completed Action, or Pluper/eet, Singular. Plural.

I had been loved NT ^ \i».>Q««0LVs^^{5}

i^ TABLE OF A REGULAR VBRm

Future Tense, Sing^nlar. Plural.

I shall or will be lored We shall or will be loved

Subjunctive Mood.

Present Tenses. Singular. PloraL

I be loved We be loved

Dependent Present, Singular. Plural.

I may be loved We may be loved

Imperfect Tense. Singular. Plural.

I were being loved We were being loved

Passive Voicje.

Past Tenses, General Notion.

Singular. Plural.

I were loved We were loved

&c. &c. 

Per/ect. Singular. Plural.

I could be loved We could be loved

&c. ^<i%

Other auxiliaries, * should,* * n^{ox}JA; * m^^

“^ABLB OF A RBGULilR TBRB. 97

Pluperfect, SiDgnlar. Plural.

i could have been loved We could have been loved &c. &c. 

Auxiliaries as above. Imperative Mood.

Sing^ular. PlaraL

Be loved Be loved.

Participles.

Present . . Being loved,

{loved and having been loved.

IRREGULAR VERBS.

The following is a list of those verbs which do not form their Past
Tense and Passive Participle by adding ^d* or * ed* to the root. Such
verbs are called Irregular.

Irregular Ve>bs which have their Past Tense and Passive Participle
alike.

Present.. Past- Pasdve Participle.

Abide abode abode

Behold beheld beheld”*^

• The Passive PaTtidp\e«)e\xo^«t? Sa x^aX. ^^^ /^ ''^^^^ except in the
sense of / bouad,^ * o\JSa^{|}*

98

IRRBOUIAB TBBBS.

Present.

Past.

PassiTe Partid^.

Bend

bent or bended

bent or bended

Bereave

bereft or bereaved

bereft or bereaved

Beseech

besought

besought

Bind

bound

bound

Bleed

bled

bled

Breed

bred

bred

Bring

brought

brought

Build

built or builded

built or builded

Buy

bought

bought

Catch

caught

caught

CUng

clung

clung

Clothe

clothed or clad

clothed or clad

Creep

crept

crept

Deal

dealt or dealed

dealt or dealed

Dig

dug or digged

dug or digged

Dwell

dwelt

dwelt

Feed

fed

fed

Feel

felt

felt

Fight

fought

fought or foughtc

Fmd

found

found

Flee

fled

fled

Fling

flung

flung

Gild

gilt or gilded

gilt or gilded

Gird

girt or girded

^rt or girded

Grind

ground

ground

Hang

hung or hanged

hung or hanged

Have

had

had

Hear

heard

heard

Heave

heaved or hove

"hewe^ or"Wi^u

Hold

held

\ie\eL
IRRBGUUL& VERBS.

Present.

Past.

Passive Participle.

Keep

kept

kept

Kneel

knelt or

kneeled

knelt or kneeled

Lay

laid

laid

Lead

led

led

Leave

left

left

Lend

lent

lent

Light

lighted i

jrlit

lighted or lit

Lose

lost

lost

Make

made

made

Mean

meant

meant

Meet

met

met

Pay

paid

paid

Bead

read

read

Bend

rent

rent

Say

said

said

Seek

sought

sought

Sell

sold

sold

Send

sent

sent

Shine

shone or shined

shone or shined

Shoe

shod

shod

Shoot

shot

shot

Sit

sat

sat

Sleep

slept

slept

Slide

slid

sUd

sunk

slunk

slunk

Speed

sped

sped

Spend

spent

spent

Spill

spilt or spilled

spilt or spilled

Stand

stood

%\X>Q^

Stidk

stuck

^IwOs.

100

IRRBOULAB VBRB8.

Present.

Past.

Passiye Participle.

Sting

Btung

stung

Strike

struck

Struck or stricken

String

strung

strung

Sweep

swept

swept

Swing

swung

swung

Teach

taught

taught

Tell

told

told

Think

thought

thought

Weep

wept

wept

Win

won

won

Wind

wound

wound

Work

wrought or

wrought or

worked

worked

Wring

wrung

wrung

Irregular

Yerhs that suffer no change for thelj

Past Tense, or Passive Participle*

Present.

Past.

Passive Participle.

Burst

burst

burst

Cast

cast

cast

Cost

cost

cost

Cut

cut

cut

Hit

hit

hit

Hurt

hurt

hurt

Knit

knit

knit*

Let

let

let

Put

put

put

Rid

rid

rid

Set

set

set

Shed

shed

iVie^

• AHo

regnVas.

IRRBQtlLAR TBRBS.

101

Present.

Past.

Passiye Partidple.

Shut

shut

shut

Slit

slit

slit

Split

spUt

split

Spread

spread

spread

Thrust

thrust

thrust

Most of the other Irregular Yerbs have their Present and Past Tense and
Perfect Participle all dissimilar.

Present.

Fast. Passive Participle.

Am

was

been

Arise

arose

arisen

Awake

awoke or awaked

awaked

Bear, to  

bring >

bore or bare

bom

forth J Bear, to 1

carry ) Beat

bore or bare beat

borne beaten

Become

became

become

Begin Bid

began bade or bid

begun bidden or bid

Bite

bit

bitten

Blow

blew

blown

Break

broke or brake

broken

Chide

chid

chidden or chid

Choose

chose

chosen

Cleave, to ) eiin^ to )

clave or cleaved

<^{e«}^^

^--- ^

102

IBRBOULAR VERBS.

Present*

Fast.

PassiTe Partioiple.

Cleave, <o ) , , -,. ,., } clove or cleft split J

cloven or cleft

Gome

came

come

Crow

crew or crowed

crowed

Dare

durst or dared

dared

Do

did

done

Draw

drew

drawn

Drink

drank

drunk

Drive

drove

driven

Eat

ate

eaten

FaU

feU

falleti

Fly

flew

flown

Forbear

forbore

forborne

Forget

forgot

forgotten or forgot

Forsake

forsook

forsaken

Freeze

fVoze

frozen

Freight

freighted

fraught

Get

got or gat ,

got or gotten

Give

gave

given

Go

went

gone

Grave

graved

graven or graved

Grow

grew

grown

Heave

heaved or hove

heaved or hoven

Hew

hewed

hewn or hewed

Hide

hid

hidden or hid

Know

knew

known

Xade

laded

laden

Lie

lay

lain

Load

loaded

loaden or loaded

Mow

mowed

mown or mowed

IRREGULAR TBRBS

103

Present*

Fast.

Passive Participle.

Quit

quit or quitted

quitted

Ride

rode

ridden

Ring

rang or rung

rung

Rise

rose

risen

Rire

rived

riven

Run

ran

run

Saw

8&wed

sawn or sawed

See

saw

seen

Seethe

seethed or sod

sodden

Shake

shook

shaken

Shape

shaped

shapen or shaped

Shaye

shaved

shaven or shaved

Shear

sheared or shore shorn or sheared

Show

showed

shown

Shrink

shrank or shrunk shrunk

Shrive

shrove

shriven

Sing

sang or sung

sung

Sink

sank or sunk

sunk

Slay

slew

slain

Sling

slang or slung

slung

Smite

smote

smitten

Sow

sowed

sown or sowed

Speak

spoke or spake

spoken

Spin

span or spun

spun

Spit

spat or spit

spit, spitted, orspitten

Spring

sprang or sprung sprung

Steal

stole

stolen

Stink

stank or stunk

stunk

Stride

strode or Btrid

BtTV^^^tl

Strive

Btroye

ntwetL

104

IRBBOCIiAR TBBBK

Present.

Part.

Paasiye Partieiiae.

Strow

Btrowed

strown or strewed

Swear

swore or sware

sworn

SweU

swelled

swollen or swelled

Swim

swam or swum

swum

Take

took

taken

Tear

tore or tare

torn

Thrire

throYe

thriv^i

Throw

threw

thrown

Tread

trod

trodden

Wear

wore

worn

Weave

wove

woven

Write

wrote or writ

written or writ

PREFIXES.

ENGLISH.

A, on; as, o-side.

Be, gire a transitive sense to verbs ; as, (e-stride.

En, (em, im), gives a transitive sense; as, en-able«

For, away, o/; as,/or-go.

Fore, before; as, ./ore-see.

Gain, against; as, ^ain-say.

Mis, error ; as, mis-take.

Out, beyond; as, ot«^live.

Over, above ; as, over-do.

Un, not ; as, t(n-able.

With, against ; as, luith-Btand,

LATIN.

A, ab,^rom; as, -a-vert, a5-8oIve. Ad, to ; as, advert, op-position.

Am, arov/nd; as, am-bient. Ante, before ; as, ante-cedent. Bis (Bi), in
two ; as, &i-sect. •Oircum, rotcTu^; as, circwm- volution.

Con, together; as, con-vert, c(m-volution, corn-pose. Contra, o^{atns};
as, con^ra-vert. De, down; as, de-^{cJW}^ d^{r}^^{sR}*

Dis, apart: as, di-vert, dK*-\w%».

106

PREFIXES.

E, Ex, out ; as, «-Tert, ^-Tolre, ea^-po8e.

Extra, heycmd; as, ortra-ordinary.

Id, tn, before a rerb, no^, before an adjectiye ; as,

tr-regular, tn-yert, tn-yolre, tm-pose.

Inter, between; as, tn^{er}yolre, tnter-pose.

Intro, within; as, m^ro-yert. Juxta, Ttear; as, Ob, in <A« way ; as,
06-yert, Per, through; as, jper-yert. Post, behind ; as. Pre, before;
as,

Prseter, &est(269 ; as, pre^er-natural. VvOi forwards ; as. Re, 6ac^;
as, r6-yert, re-yolre;

Retro, back; as, refro-spect. Se, opar^ ; as, «e-parate. Sine, without;
as, «ine-cure. Sub, under; as, aw6-yert, Subter, &«7i€a«A / as,
subter-fuge. Super, above ; as, super-fLixoua. Trans, across ; as,
Ultra, beyond; as, vZtra-montane.

^{Wfo}position. op-pose.

|x»<-pone. jpr^positioD,

|?ro-poBe. re-pose.

wp-pose.

<ran«-po8e.

GREEK.

A, (An), not ; as, an-archy.

Ampbi, of two, round; as, amp^t-biouSy

theatre.

Ana, throughout, back ; as, ana-logy, ana-strophe. Antl, against; as
anti-chri&tiati) a/at\r^^{c(}\i!&. -^POfJroms as, opo-state, apo-\o^,
a;po-^{'««}«

PRBFIXBS. 107

Cata, down ; as» eerto'logue, cafa-strophe.

Dia, thraughy between ; as, (ita-meter^ <2ia-logae.

Ec, o\xt of; as, cc-logue, ec-lipse.

Ed, iuy on; sSy eMipse, an-comiam.

Epi, upoUf /ollovjing on; as, ept-logue.

Hyper, over ; as, ^yper-critical.

Hypo, ttfkfor; as, Aypo-mftco?.

Meta, change; as, meto-thesis.

Para, a^^, eon/rary ^o; as, /xzra'-lysiB, |>ara*dox.

Peri, round ; as, |?6n-phery.

Syn, together^ with; as, ir^-patfay, ayMogism.

PRINCIPAL AFFIXES.

ENGLISH.

OfNowM, Ar, personal ; as, li-ar. Ard, Ao&t^; as, drunk-ar(^. Er,
personal; as, read-er. Ery, state ; as, slav-ery, Ing, action ; as,
bak-t9?^. Kin, diminutive ; as, lamb-A;tn. Ling, diminutive; as,
duck-^{in}. Let, diminutive ; as, stream-^. Ness, <^at0 ; as, good-ness.
Ship, state; as, friend-sMp.

108 PRINCIPAL AFFIXES.

f Ster, - ) ( Bong-ster.

I Stress,''^' / '  Boug-gtreas. Th, state ; as, dep-<A. Yer, perfovud;
as, law-yer.

Of Adjectives.

Ed, condition; as, wretch-e(2. En, made of; as, gold-^n.  Ful,yuK; as,
ie&r-ful. Ish, likeness ; as, child-isA. Less, privative ; as,
sIiaine-2eM. Y, a&un(2anoe ; as, hill-^.

LATIN.

Of Nouns, Personal.

An, Ian, as, sacrist-an, chapl-am, histor-ian. Ar, er, as, burs-ar,
monst-er. 1st, as, plural-is^, fatal-»^.

{Tor, sor, ) f execu-«or, spon-sor.

Trix, J 1 execu-^rta?.

Of Adjectives,

lal, as, inquisitor-ia?. lous, as, censor- ioud. Ous, as, monstr-oufl.

PRINCIPAL AFFIXES.

109

^ § S

3 -i 2 i fl 3 s ” ®

§

S3

I

00 S

o 9*

•£ 8 a --3

J?

S 3 ^

55 2^1

® o

sfl i ? ^

.f g -a I i I ^ § a a 3 J

ON LEARNING LANGUAGE.

In Btudying language, it is important to xo» member that words are but
the outinurd ezpressioii of what passes in the mind; and though the
things which the mind can busy itself about are innu- merable, the ways
in which it can deal with them and put them forth in speech are few and
limited. Language, in fact, may be compared to a wood with innumerable
trees, but one well-trodden broad path through it, which in ninety-nine
cases out ai a hundred will lead the traveller right ; there are also
bye-paths leading to particular spots, and the pathless wood with plenty
of scope for wandering and being lost. Suppose then a stranger, brought
into this wood, and desiring to pass through it. The only sensible
advice that could be given him would be, ''Keep to the mam road, beware
of the thickets, avoid entangling yourself in bye* paths, or short cuts,
till you are thoroughly aos* quainted with the general features and
bettring of the country/' Can any way then of teaching language be right
which is not analogous to this ? Ought not all the curiosities and
exceptions to be j>a8sed over unexplained, until the common every^ dajr
framework of ordmar^ &Qii£;iic^Q!&) the beaten path that is, be weU
Wowu'^ IX. V^{\i} Vlwaa

ON LBARNINO LANGUAOB. Ill

enough then to explun and point out the appa- rent deyiatlons and
inconsistencies. But this is the exact contrary of the method usually
pursued. The mind of the imhappy learner is stuffed with all mumer of
exceptions, long hefore he clearly knows what they are exceptions to;
and with idioms countless, long before he is aware what is the genen^
type from which they seem to depart. His bewildered brain is set
floating amongst num- bers of isolated cases, and unconnected facts;
there is only one omission, unfortunately rather an important <me, no
chart or compass is given him for his guidance.

Let erery teacher (who knows such things faimsdf) boldly resolve to
notice nothing till his pupils are thoroughly acquainted with the com-
mon principles oi all language. There will be less show for a time, but
more safety. Men with a certain reputation as scholars not unfre*
quently cannot give the principle of the simplest «tep in their
parrot-like knowledge. How often, for instance, it is said, he is a yerj
cleyer man himself, but he cannot teadi others. In plain English, he has
never been taught the principles of his knowledge, he has not thought
them out for iumself. The result is obtained by unceasing prac- tice,
and as that is incommunicable, oth^ti cannot benefit by it. Blind men
can fed their way along familiar paths, but are unable to give
directions to otiiers' sight.

Now the study of langHAigft xnas^ \3(^ Vs/^^{ts} ^^

112 ON LBARNINO LANGUAQB.

in two points of view ; first, what language itself is, which it has
been the endeavour of this little work to state simply ; and, secondly,
how we our- selyes should behave with respect to it. The one being as it
were the road to be travelled, the other directions for travelling on it
well. A few obsez^ vations on this second point will not be out of place
here. First, then, let no teacher or learner pass beyond a technical or
general term, 8uch as subject, &c. until it has become his own natural
way of expressing the thing signified by it It would be no more absurd
to have daily lessons about the Omithorynchus, those engaged in such
lessons being totally ignorant of the sort of animal meant, than it is
to use such terms as subfeti daily, with a similar ignorance. Yery often
a careful examination would detect some foolish after mistake, or even
habitual mental confusion, as having arisen from the practice of using
technieal and general terms without realizing their full pieaning. No
time is misspent which dears the general terms and first steps. Probably
few N»- tional School classes would thoroughly master those two Terms,
Subject and Predicate, without at least a month's careful training. To
give sudh training without being wearisome is in itself an art. My own
method was, when the short reading lesson was ended, to select an easy
sentence to be written down by one of the boys on the black board; then
the writing and s>)ft\VvTi^^%& ^{T}xvcaaodt bjr the claas ; ^fter that
tVvQ E^>^qX. ^^{cA}x^aSCvs*^

ON LBARNINO LANOUAGB. 113

of that Sentence were required, with the reasons for the answers ; then
we left it» and proceeded to build up the sentence on which we were
regularly engaged. Every lesson haying one special paint cut Ub main
object ; this one point with the summing up at intervals the chain of
argument, and reca- pitulating day by day the former links, being quite
sufficient to occupy the whole time, and as much as could be done with
profit to a Class; the first maxim of good schooling being, not to
sacrifice the good of the many to the quickness of a few.

Having cleared the Terms made use of, the next great ud in difficulties
will be to observe the principle on which the words of every Sentence
are arra/nged. Now in enery Sentence without fail this is certain, that
the words which will most clearly and Jbrdbly introduce to notice what
the speaker wishes to make known, wiU come first; and the rest follow,
according to its relative im- portance. It is probable, therefore, in
any sentence that the Subject stands first; because what the speech is
to be about must generally be mentioned first for clearness* sake ; and
without clearness no- thing can he forcible. Viewed separately, the Pre-
dicate, or what is intended to be said, is generally the principal
notion ; and therefore li force alone were the question, to put the
Predicate first would generally be the most forcible. But care must be
taken, lest the apparent gain in force of this arrangement be more than
co«itet>«^{KWi}$^ “^^ loss of clearness. Tins brmga om. VJoa N^N>ft ^^

114 ON LEARNING LANGUAGE.

F&rmal Cases. When a language has ForwaSi CaseSf it gams the power of
yarying the arrange- ment of a sentence almost mfinitely, without eoib-
fusion, according to the relatiye importance of tlM thoughts to be
expressed. Thus in the sentenoe^ ^ GsBsar killed Pompeius/ if the notion
required to be expressed most strongly was, that it wis Pompems who was
killed, a Latin boldly put it first :

Pompeium Csesar interfecii

Pompey Csesar killed ;

and no confusion ensues. In English this can seldom be, unless the
Predicate consists of the Verb of Existence, and an adjectire ; as *
Chreat U Dicma of the Ephmans ;' where any one can see the increase of
force resulting from the position of the Predicate. The English
language, however, has a plan for getting the Predicate first in some
instances. The words //;?,' and / There! at the beginning of sentences*
are often faiUe 9utject$t mere subterfuges for getting the Predicate
first in the arrangement. Tlius, 'It is a good thin^---

Subject.

to save a man/ equalling, 'To save &c. is.' * There

Subject.

is no hope --- that he will do it :' equalling, *jB% doing it is
hopeless,'

Therefore the words /It/ and / There, are as it were sign-posts,
pointing out that the Predicate fol* /ows unmediatelj, whilst the
Subject comes last. la EDgUah then, if the fixBt ^wotd V& It, ox Tl^^i,
ot

ON LBARNING LANOUAOB. 115

an adjeoiive with the rerb of Existence, the Predi- cate 18 generally
first in the arrangement, and the Babject last. It is obyious that when
Pronouns oecur, as they have formal cases, there is much more liberty of
arrangement, as no confusion can ensue. Any dependent noun, however, can
be put first as the Subject, by casting the sentence into a Passire
shape; as, 'Pompey was killed by Csesar.' This is a common way in
English of getting the emphatie word first.

Again, in examining a sentence, if there is any difficulty, whatever
conjecture on the point appears most probable, it can be tested in the
following manner. Let the learner, instead of the word or words which
are difficult, substitute others easier, which ceriairdi/ are, what he
conjectures the ex- pression he doubts about to be. Thus, in the sen-
tence, ' WiU he come fast f* say he thinks /fa8t/ an Adverb, but is in
doubt ; let him substitute an un« mistakeable Adverb; for instance, *
quickly (* if that which is substituted exactly fills the grammatical
place of the original expression, the conjecture is probably right ; if
it does not, it must be wrong.

Again, there is a difficult sentence to be mas- tered; how many let
their minds float about at random over it ; and unless they find it out
by some sudden flash, do nothing. Instead of this, let the learner seize
at once on some point he is certain, or nearly certain, about; say the
subject, or the priQcipie verb of the Predica;Q wAlx^^^^^{Rj}'st^^{s}

116 ON LBARNING LANGUAGE.

rest agrees with this, and makes sense. It is very seldom, indeed, that
both Subject and Predicate are difEksult to miravel in the same
sentence. At all erents, let him examine whether there is more than 09M
word that can be a Predicate, or more than cm word that can be a
Subject; let him decide as to which shall be his certainty; say the
subject is, then what verb can possibly form the Predicate? Is it
transitiye? If so, where is the case? Is the case qualified? and so on;
adding, by degrees, the rest till all coheres. This then is a rule. Let
all uncertainties be tried as to their agreement with some certainty. If
there is no certainty, let the most probable guess be assumed as certain
for the experiment.

Again, it is a great thing to know what the dif- ficulty really is, and
where. When this is found, let all words, or clauses, be put out of
sight for the time, excepting the word, or combination, that is
puzzling. This often clears the matter. As an assistance in doing this,
let it be borne in mind, that wheneyer a relatire occurs, it is certain
that the clause, in which the relatire is, is a complete sen- tence in
itself, as far as grammatical construction goes; and therefore will not
influence grammatically any other part of the sentence. In any
difficulty then, that clause may be set apart, and shut out from the
rest, and examined separately.

Very often the difficulty arises from some part of a sentence not being
before the eye, but under-

ON LEARNING LANOUAQB. 117

stood. Let every clause therefore, when this is the case, be written out
with its full complement of words. This often clears the matter.

Again, much ignorance arises from rules being allowed to lie about in
the mind as mere dry state- nents. This should never be permitted. Let
the learner always frame for Ivmxdf an actual speech or formula, the
easiest possible, which is an example of the rule, to try his doubtful
eases by. Thus, if the rule is ; Every pure supposition will have both
olauses Subjunctive with past tenses of the auxiliary verbs, or verb of
Existence, let him give it life by having a model supposition to refer
to ; as, ' i/* J were fooUshf I should learn the rules like a parrot* Or
if a question is asked on any point, let him at once make a sentence
which represents the required instance, and examine that ; this plan
will marvel- lously tend to the producing an answer. Thus, say the
question is asked. 'Explain the arrangement of a sentence which begins
with the word There* Let him at once write down such a sentence, and ex-
amine it ; and so on.

Let therefore all uncertainties be tested by some certainty, real or
assumed.

Let the difficulty be hunted out, and every thing else put aside till
that is cleared.

Let the suppressed words of a sentence, if needful, be filled in.

Let all rules have reality given them by being embodied in the form of
simple examples.

118 ON LEARNING LANGUAGE.

Never let Technical, or General Terms, be passed OTer until they are
completely understood.

Never let the mind float about at random ; but let it be fixed at once
on some one thing to start with.

These rules, regularly acted on, will carry the learner through most
labyrinths securely. {

)

 

APPENDIX.

ON MOOD.

The human mind has the power not only of recognizing single facts,
whether past, present, or future ; but also of seeing the connexion
between them and their relations to one another. And not only so, but it
is able to frame circumstances more or less imaginary, and to follow out
various con- ditions and the consequences arising from them. It is
manifest at once, that there is a broad and well- defined line between
every thing stated as an actual fact, and every thing merely imagined by
the mind, or viewed as subject to any condition whatever. This broad
distinction is the distinction which is repre* sented by the Fact-mood
or Indicative on the one band, and by the Subjunctive mood on the other.
And in theory it is plain enough. But directly we come to practice, we
find every shade of difference^ varying from absolute certainty to any
amount of uncertainty of time, place, or conditions.

It is important to bear in mind that, abstract- edly, it is an open
question how these changes ought to be expressed; whether the verb
should express them at all; and if so, in what degree, by corre-
sponding changes of form, or otherwise. And more- over, that in no
language would the verb, or any modification of the verb, deal with more
than a part

120 APPENDIX.

of these subtle shades of sense ; the rest would be ei- pressed by
various particles. Those yariationsywhiflh I the yerb or its
modifications do ezpressy are express- - ible in two ways. Some
languages exjMress them by ' changing the form of the verb. Some by
combiniiig auxiliary rerbs with it. Where the form is dbaDgedf the Mood
is obyious at once. Where auxiliary Terbl are used, unless they are
confined to this offios^ there will be much uncertainty whether, in any
in- stance, they represent mood or not. Two diffecenl tendencies
develope themselves from this. The tendency of a language with formal
moods will be to increase the modal power of the rerb, and to de- light
in making it express subtle modal distinotions. The tendency of a
language without formal moods will be in an exactly contrary spirit, to
simplify as much as possible the ambiguity of the modal com* binations,
by employing as few as possible^ and resorting more and more to
particles to expreM clearly those subtleties which the verb cannot e>-.
press without confusion. Where the moods tan formal, it is of course
easy to see what mood is used in any particular instance ; but by no
means equally easy, very often, to determine the precise force of the
mood ; and still more often the distinction, when perceptible, is so
slight, that it does not in the least affect the general sense, and
cannot be translated into another language without the most clumsy cir*
cumlocution. A language without formal moods will obviously neglect
these minute peculiarities, and Bet down all such instances under some
one

ON MOOD. 121

definite head. Not because they might not per- haps be classed
otherwise, neither denying that another language does legitimately class
them other- wise, but merely claiming the same right to follow out its
own tendency to simplify, which it concedes to other languages to follow
out theirs. For if in English, with no formal moods to guide us, we un-
dertake to make the verb in combination define the same subtle shades of
sense which other languages convey by form, there is no clue to the
labyrinth. Like the shield which was gold on one side, and silver on the
other, about which the comers from opposite sides fought to the death,
our moods will be doublefaced, and the best grammarians shall contradict
each other; one coming from the Latin side with his rule, another from
some other lan- guage with his rule, which, after all, if correct, only
serves to shew what the case may be, not what it necessarily is. Let us
then briefly examine the most doubtful cases of English moods on their
own intrinsic merits, bearing in mind, 1st, that the ques* tion we have
to deal with is, not whether they may be subjunctively expressed, but
whether, as far as practice goes, they must be ; and 2ndly, what is the
most convenient classification which solves the in- stances as they
occur without violating any univer- sal law. First then let us take the
conditional clause of a sentence containing a probable condition and }t8
consequence. Now the difficulty in English arises from the fact, that
the same words in the same sort of combination can stand either as
Indicatives or

W

122 APPBNDIX.

Subjunctiyes, the sense and the stnictiire of the sentence alone
detennming which they are in any instance. K they were always Indicatiye
or always Subjunctiye in certain positions, the oonftnion and difficulty
would be remored. In a pure supposition for instance, where the rerbs of
both clauses are always Past Tenses and Subjunctiresy or eren in any
modification of such a sentence^ as the sense and structure of the
sentence is pretty definite, the chances of error are much lessened ;
but where the condition and consequence are probable, and Past Tenses
are not used, and it is almost matter of in- difTerence whether
Subjunctires or Indicatiyes are used, unless some definite rule be
discoTered fbr doubtful cases, the matter is much more compli- cated.
Now in every instance, excepting a Pure Supposition, the condition can
be stated as certafai at a given time, a given place, or given circum-
stances ; that is, assume for certain so and so, the rest follows. ^If!
and the conditional particles in such instances merely introducing a
fiEtct to be granted, ^ven the time, place, or circumstances as, ' K he
goes, he will,' &c. ' If boys are ignoranf they will be noisy.' There is
no uncertainty i these, and the like instances, with regard to tl main
fact. ' He does go sometimes :' ' Boys are ign rant sometimes.' The
condition implies that t fact is true only under given circumstances. T
conditional uncertainty docs not touch the fi only the universality of
the fact. The facf asserted of some boys; the condition only deba

ON MOOD. 123

from all boys. It follows from this, that every con- ditional clause in
which the fact can be assumed to he true, giyeuy time» place, or
circumstances, may be cast in an Indicative form ; and, therefore, as a
pure Supposition always has past Tenses, that no present Tense, of a
verb of mood need be Subjunc- tive in a Conditional clause. Now there is
one present Tense of the verbs of mood which can be either Subjunctive
or Indicative; the word 'may/ It wUl then much simplify matters to state
as a rule^ that the present tense 'may,' in a Conditional clause, is
never Subjunctive; therefore, every pre- sent Tense in a Conditional
clause is Indicative, excepting the formal Subjunctive Presents of each
verb^ which the eye can detect at once.

In dependent clauses, on the other hand, the game sort of reasoning
leads to a contrary rule. To take for instance, dependence with respect
to time. All dependence on time must be cast in one of two forms. The
form must either be, at gome time or other {uncertain), or, at a fiaced
moment {cer” tain)» Thus :

he goes. Equalling a cer- tain moment which will

I ^U plague him till ^ . ^ ' „.

'^^ I he go. Equalung a tune

which may or may not

come.

The same holds good with respect to place; as,

•r J. 11 vxi- / ^^ leads. A certain place. I follow whither  . i j * _1
• i

i he may lead. An uncertain place.

124 APPENDIX.

And in dependence of circumstance ; as, ' He reads that he may be wise/

Now in all dependent clauses, excepting smae few instances where strong
emphasis is laid on the word 'may/ the word 'may' denotes the uncer-
tainty. In dependent clauses, therefore, it much simplifies matters to
lay down the positive rule, that verbs of mood, whether present or past,
are SubjunctiTe ; as, the exceptions are few and strongly marked. The
principle which I have endeavoured to follow out being this ; that every
language has a right to fix its own limits in doubtful instances, as may
be most convenient, when no universal law ii infringed by doing so. And
all that is meant by such rules is, that they solve correctly the
difficoltleB which occur, without intending to exclude, in some
instances, every other solutipn as impossible ot wrong.

MACMILLAN & CO.'s PUBLICATIONS.

The Elements of the Gospel Harmony, with

aa Appendix containing a Catena on Inspiration from the Ante-Nicene
Fathers. By the Bey. B. F. Westoott, Fel- low of Trinity College. Crown
Syo. doth, 6f . 6cf.

*' The production of a young Theologian of great prO' fnife.”--- T. K.
Abnold.

** The most remarhable and original part of the worhis a long and most
carejully executed exposition of the Ante-Nicene Doctrine of
Inspiration, dravm directly from the writi'Ms of the Fathers themselves
: and a very interesting account of some of the heretical Gospels and
the little-hnown Clementines,'* Thb Guardian.

The Elements of Apostolic Harmony: an

attempt to determine the separate purposes and mutual relations of the
Canonical Epistles, ^y the same Author. Preparing.

Cambridge Theological Papers. Comprising

those given at the Voluntary Theological and the Crosse Scholarship
Examinations. Edited with References and Indices. By the Bey. A. P.
Moob, M.A., of Trinity Col- lege, Cambridge, and Fellow of St
Augustine's College, Canterbury. sVo. bds, 7s, 6d.

This win he found a very usefkl help to reading for the Voluntary
Theological and for Ordination Examinations,

S. Justini Philosophi et Martyris Apologia

Prima. Edited, with a corrected Text, and Englisn Intro- duction and
Notes, by the Bey. W. Tbollopb, M.A., Pembroke CoUeg^, Cambridge. 8yo.
hd», 7s, Qd,

MACMILLAX & CO.'S PUBLICATIONS. Apologia Ecclesiao Anglicanae. Hnic Nova

Editioiii aocedit Epistola celeberrinm ad Yimm NolHlem D. Scipionem.
Patncium Venetnm, de ConofUo Tridentino consonpta. Anctore Joarhb
Jukllo, oUm Epiaoopo Sarii- buriensi. Foolscap 8vo. bdt, 4j. 6d.

An Apology of the Church of England, and

an Epistle to Seignior Sdpio oonoerning the CoonoU oC Trent, translated
from the original Latin, and illnBtrated with Notes, drawn chiefly from
the Author's ” Defence of the Apology.” By the Rev. A. T. Bubsbll,
B.C.L. f cap. 8yo. bd». 6»»

This Sdiiion of the Apology supplies what has Umg heat considered
desirable--- a series of explanalory and hisknietd Notes and an Index*

The Fitness of Holy Scripture for Unfolding

the Spiritual Life of Man : Christ the Desire of all Naitioiii; or the
Unconscious Prophecies of Heathendom. Being tin Hnlsean Lectures for the
years 1845 and 1846. By K. C Tbbnoh, M.A., Trinity College, Cambridge.
8yo. bda. 7«.6^

Aristophanes. A Commentaiy on the Worke

of Aristophanes. By W, G. Clabk, M.A., Fellow and

Assistant Tutor of Tnnity College, Cambridge. ^ --- --- ■'---

Demosthenes de Corona. The Greek Text

with English Explanatory Notes. By B. W. F. Drak< M.A., Fellow of King's
College, Cambridge* Crown 8?a chthf 6s,

” The GrammaJtieal difficulties of the TeM are weU mt- plained.”
Litsbabt Gazette.

Demosthenes. The Oration on the Crown.

Translated into English by the Bey. J. P. Nobbib, HJk..* Fellow of
Trinity College, Cambridge, and one of Her Majesty's Inspectors of
Schools. Crown 8vo. sevfed» 3s,

*' The best translation we remember to have seen,” Lira- BABT Gazette.

JuYKNAL : chiefly from the text of Jahn^ with English Notes. For the use
of Schools, by J. E. Matob, M. A., FeJJow of 8t John's College. Shortly,

MACMILLAN k GO'S PUBLICATIONS.

Plato's Republic ; a new Translation into En- glishy with an
IntrodQCtion and Notes. Bj Two Fbllows of Trinity College, Cambridge.
Preparing.

Theocritus. The Greek Text, with English

Notes, Critical and Explanatory, for the use of Colleges and Schools. By
the Rev. £. Pebownb, B. A . , Fellow of Corpus Christi College. Crown
8to. Preparing,

Cambridge Course of Elementary Natural Phi- losophy, for the tue of
CoUeqea ani Schools ; beins the I>emonstration of the Propositions in
Mechanics and Hydro- statics, in which those persons who are not
Candidates for Honors, are examined for the Degree of B.A. By J. C.
Snowball, M.A., Fellow of St John's College. Fourth Edition. To which
are added numerous Examples and Problems, with Hints for their Solution.
12mo. cloth, 68,

A Short and Easy Course of Algebra. Chiefly designed for the use of the
Junior Classes m Schools, with a numerous collection of Original Easy
Exercises. Bv the Ber. T. Lunb. B.D., late Fellow of St John's College.
l3mo. bds, St, 6d.

*His d^nitions are admirable for their nmplieity and efoameM.*---
Athbnjeum.

•//n order to ascertain how far the Author's perfomumee eomes up to his
design, we have paid particular attention to those ptaees where tM
learner is most likely to stumble upon euiknowledged difficulties.... In
all these we have much reason to admire the happy art of the Author in
making crookt^ things straight, and rough places smooth. The Student
must be hopelessly obtuse who does not, in foUowino the guidance of Jar
Luna, obtain inereeuing light and satisfaction in every Hip of his way;
and such, too, is the strictly scient\fic as wett as simpU nature of the
course pursued, that he who makes himss^master of vt, will have laid a
firm foundation for an extensive and Iqjfty superstructure of
mathematical acquire/ ment,**^-Tu.B Educatob.

MACMILLAN & CO/S PUBLICATIONS.

An Elementary Treatise on tj^{e}ifferentu and Integral Calculus. By 6.
W. HsMicni^^^A., Felto of St Jobn*8 College, Cambridge. Syo. Mf . 9f .

Elementary Mechanics, accompanied by m

merons Examples, solved Geometrically. By J. B. Phia M.A., Fellow and
Mathematical Lecturer of Clare Ht 8vo. bds, 10<. 6d.

An Elementary Treatise on the Different!

Calculus. By L Todhunteb, M.A., Fellow of St Job College. Aboid
Christmas,

This Work is intended ^or the use of Schools as wdl

for Students in the Universities, It vnu aim at teaching i

Student to understand the Principles of the Science j man

therefore be much more explanatory than any treatise on i

subject hitherto published «n Engltmd,

A Treatise on D3mamics. By W. P. “Wiiac

M.A., Fellow of St John's College, and Professor of MatI matics in
Queen's College, Belfast. 8vo. bds, 9#. Gcf.

Solutions of the Senate^House Problems fira

1848 to 1851. By N. M. Ferbebs, B.A., and J. Stui Jackson, B. A., Cains
College. Just ready.

The Principles of the Solution of the Sena

House ''Riders” exemplified in the Solution of those p posed in the
years 1848 to 1850. By F. J. Jameson, b. Cains College. In October,

The Elements of Grammar, taught in Englif

By the Rev. Edwabd Thbino, ]!ilA., Fellow of Kis College.

Cambridge Guide: including Historical a

Architectural ^iotices of the Public Buildings, and a <n else account of
the Customs and Ceremonies of the Unit Tcrsity. With a sketch of the
Places most worthy of remj in the County. A new Edition, with Engravings
anc Map, RojaJ 18mo. clot'ky 5«. ^.

yV

V

*■■

J
