#+manifold-source: ../manuals.org
#+manifold-lines: 76794-77057
#+manifold-stage: 02-body
#+manifold-date: 2026-09-15

* pulsar
** Sample configuration
Remember to read the doc string of each of these variables or functions.
#+begin_src emacs-lisp
(leaf pulsar
  :straight (pulsar
             :type git
             :host github
             :repo "protesilaos/pulsar"
             :fetch t)
  :bind
  ("C-x l" . pulsar-pulse-line)
  ("C-x L" . pulsar-highlight-permanently-dwim)
  :config
  (setq pulsar-delay 0.055
        pulsar-iterations 5
        pulsar-face 'pulsar-red
        pulsar-region-face 'pulsar-red
        pulsar-highlight-face 'pulsar-red)

  (pulsar-global-mode 1))
#+end_src

*** Use pulsar with next-error

By default, the =n= and =p= keys in Emacs' compilation buffers (e.g. the
results of a ~grep~ search) produce a highlight for the locus of the
given match.  Due to how the code is implemented, we cannot use Pulsar's
standard mechanism to trigger a pulse after the match is highlighted.
Instead, the user must add this to their configuration in lieu of a
Pulsar-level solution that "just works":

#+begin_src emacs-lisp
(add-hook 'next-error-hook #'pulsar-pulse-line)
#+end_src

*** Use pulsar in the minibuffer

Due to how the minibuffer works, the user cannot rely on the user
option ~pulse-pulse-functions~ to automatically pulse in that context.
Instead, the user must add a function to the ~minibuffer-setup-hook~:
it will trigger a pulse as soon as the minibuffer shows up:

#+begin_src emacs-lisp
(add-hook 'minibuffer-setup-hook #'pulsar-pulse-line)
#+end_src

The ~pulsar-pulse-line~ function will use the default Pulsar face, per
the user option ~pulsar-face~.

A convenience function can also be used ([[#h:6ca69953-1a89-4968-a46c-2fa5e57aca9b][Convenience functions]]).  The
idea is to apply a different color than the one applied by default.
For example:

+begin_src emacs-lisp
(add-hook 'minibuffer-setup-hook #'pulsar-pulse-line-blue)
+end_src

** Overview

This is a small Emacs package that automatically highlights the
current line after certain functions are invoked. It can also
highlight a line or region on demand. The idea is to make it easier to
find where the point is, what was affected, and also to bring
attention to something in a buffer.

When ~pulsar-mode~ is enabled in the current buffer, a pulsing
highlight effect will be produced after any command listed in the user
option ~pulsar-pulse-functions~. The ~pulsar-global-mode~ has the
same effect in all buffers ([[#h:87ba8ed7-251d-4e74-8eb9-964c51c26bfa][More ways to create automatic pulse effects]]).

** Style of a pulse effect
The pulse's duration is influenced by the user option ~pulsar-delay~.
The greater the value, the longer the highlight will stay on display.
The user option ~pulsar-iterations~ controls through how many steps
does the poduced pulse colour go through before it fades away.

#+vindex: pulsar-face
#+vindex: pulsar-generic
#+vindex: pulsar-red
#+vindex: pulsar-green
#+vindex: pulsar-yellow
#+vindex: pulsar-blue
#+vindex: pulsar-magenta
#+vindex: pulsar-cyan
All pulse effects are done with the user option ~pulsar-face~. Any
face with a background attribute can be used for this purpose. Pulsar
defines several such faces, namely, ~pulsar-generic~ (the default
value), ~pulsar-red~, ~pulsar-green~, ~pulsar-yellow~, ~pulsar-blue~,
~pulsar-magenta~, ~pulsar-cyan~.

** Temporary static highlights
[ Revised as part of {{{development-version}}}. The
  ~pulsar-highlight-temporarily~ supersedes ~pulsar-highlight-line~
  and ~pulsar-highlight-dwim~. ]

#+findex: pulsar-highlight-pulse
The command ~pulsar-highlight-pulse~ will produce a pulse effect on
demand. This is independent of ~pulsar-mode~ and all the conditions
for automatically creating a pulse.

#+findex: pulsar-highlight-temporarily
Unlike pulses which disappear after some time, it is possible to
create temporary static highlights that stay in place until another
command is performed. The ~pulsar-highlight-temporarily~ will produce
such a static highlight for the active region or current line.

#+vindex: pulsar-highlight-face
The user option ~pulsar-highlight-face~ controls which face is used
for static highlight (temporary or permanent). By default, it is the
same as the ~pulsar-face~, which is for pulse effects, but can be
assigned to a different face to help differentiate pulses from static
highlights ([[#h:90cc699b-7f4a-414d-ab4e-1ab553992a14][Style of a pulse effect]]).

** Permanent static highlights
:PROPERTIES:
:CUSTOM_ID: h:690dac43-338b-4320-a1fb-db6b919016be
:END:

[ All the permanent highlights are part of {{{development-version}}}. ]

#+findex: pulsar-highlight-permanently
The command ~pulsar-highlight-permanently~ adds a permanent static
highlight to the current line. The effect stays in place even after
the point moves. When the region is active, the highlight is applied
from the beginning to the end of the region. Otherwise the highlight
is applied to the current line.

#+findex: pulsar-highlight-permanently-remove
The command ~pulsar-highlight-permanently-remove~ removes permanent
static highlights from the active region or current line. This command
operates on the entire buffer when it is called with a universal
prefix argument (=C-u= by default).

#+findex: pulsar-highlight-permanently-dwim
The command ~pulsar-highlight-permanently-dwim~ adds a permanent
static highlight if there is none or removes it if there is one. It
operates on the currently active region or line at point.

Permanent static highlights are rendered with the face specified in
the user option ~pulsar-highlight-face~. It is the same used for their
temporary counterparts ([[#h:ae9d40d5-5f32-4bfe-ad75-ac6311b5b11f][Temporary static highlights]]).

** More ways to create automatic pulse effects
:PROPERTIES:
:CUSTOM_ID: h:87ba8ed7-251d-4e74-8eb9-964c51c26bfa
:END:

The ~pulsar-mode~ and ~pulsar-global-mode~ perform an automatic pulse
after a function in the ~pulsar-pulse-functions~ is called ([[#h:62d716b4-44f7-4078-85d2-29a7da8ca253][Overview]]).
They can do the same in more cases.

#+vindex: pulsar-pulse-region-functions
- Region-related changes :: Pulsar can also produce an effect over a
  specific region. This is useful to, for example, highlight the area
  covered by text that is pasted in the buffer. The user option
  ~pulsar-pulse-region-functions~ defines a list of functions that are
  region-aware in this regard. The default value covers copyring,
  pasting, and undoing/redoing.
#+vindex: pulsar-pulse-on-window-change
- Window-related changes :: The pulse effect can be created whenever
  there is a change to the window layout. This includes the selection,
  addition, deletion, orr resize of windows in a frame. Users can opt
  in to this feature by setting ~pulsar-pulse-on-window-change~ to a
  non-~nil~ value.

#+vindex: pulsar-region-face
The user option ~pulsar-region-face~ sets the face that is used for
region-related pulses. By default, it is the same as the ~pulsar-face~
([[#h:90cc699b-7f4a-414d-ab4e-1ab553992a14][Style of a pulse effect]]).

** Resolve function aliases
:PROPERTIES:
:CUSTOM_ID: h:48c96d7d-77f1-42ba-955c-11982747c7d4
:END:

By default, Pulsar does not try to resolve and act on a function's
aliases ([[#h:62d716b4-44f7-4078-85d2-29a7da8ca253][Overview]]). It only works with the exact symbols it is given.
If those aliases are not added to the ~pulsar-pulse-functions~ and/or
~pulsar-pulse-region-functions~, they will not produce a pulse effect
([[#h:87ba8ed7-251d-4e74-8eb9-964c51c26bfa][More ways to create automatic pulse effects]]).

#+vindex: pulsar-resolve-pulse-function-aliases
The user option ~pulsar-resolve-pulse-function-aliases~ can
be set to a non-~nil~ value to make Pulsar check for the aliases of
all the function symbols it is aware of and act on them accordingly.

** Omit hidden buffers
:PROPERTIES:
:CUSTOM_ID: h:b67b2ede-bbfc-4318-b395-3ee276434aa4
:END:

#+vindex: pulsar-inhibit-hidden-buffers
The user option ~pulsar-inhibit-hidden-buffers~ controls whether
Pulsar is active in hidden buffers. These are buffers that users
normally do not interact with and are not displayed in the interface
of the various buffer-switching commands. When this user option is set
to ~nil~, Pulsar will work in those buffers as well ([[#h:62d716b4-44f7-4078-85d2-29a7da8ca253][Overview]]).

** Convenience functions
:PROPERTIES:
:CUSTOM_ID: h:6ca69953-1a89-4968-a46c-2fa5e57aca9b
:END:

Depending on the user's workflow, there may be a need for differently
colored pulses.  These are meant to provide an ad-hoc deviation from the
standard style of the command ~pulsar-pulse-line~ (which is governed by
the user option ~pulsar-face~).  Pulsar thus provides the following for
the user's convenience:

#+findex: pulsar-pulse-line-red
- ~pulsar-pulse-line-red~

#+findex: pulsar-pulse-line-green
- ~pulsar-pulse-line-green~

#+findex: pulsar-pulse-line-yellow
- ~pulsar-pulse-line-yellow~

#+findex: pulsar-pulse-line-blue
- ~pulsar-pulse-line-blue~

#+findex: pulsar-pulse-line-magenta
- ~pulsar-pulse-line-magenta~

#+findex: pulsar-pulse-line-cyan
- ~pulsar-pulse-line-cyan~

These can be called with =M-x=, assigned to a hook and/or key binding,
or be incorporated in custom functions.

** Integration with other packages
:PROPERTIES:
:CUSTOM_ID: h:b884f2ac-82f3-48c0-bee5-6709d6647b1d
:END:
#+cindex: Helper functions for integration with other packages

Beside ~pulsar-pulse-line~, Pulsar defines a few functions that can be
added to hooks that are provided by other packages.

#+findex: pulsar-recenter-top
#+findex: pulsar-recenter-center
#+findex: pulsar-recenter-middle
There are two functions to recenter and then pulse the current line:
~pulsar-recenter-top~ and ~pulsar-recenter-center~ (alias
~pulsar-recenter-middle~).

#+findex: pulsar-reveal-entry
There also exists ~pulsar-reveal-entry~ which displays the hidden
contents of an Org or Outline heading.  It can be used in tandem with
the aforementioned recentering functions.

Example use-cases:

#+begin_src emacs-lisp
;; integration with the `consult' package:
(add-hook 'consult-after-jump-hook #'pulsar-recenter-top)
(add-hook 'consult-after-jump-hook #'pulsar-reveal-entry)

;; integration with the built-in `imenu':
(add-hook 'imenu-after-jump-hook #'pulsar-recenter-top)
(add-hook 'imenu-after-jump-hook #'pulsar-reveal-entry)
#+end_src
