#+manifold-source: ../manuals.org
#+manifold-lines: 1067-1433
#+manifold-stage: 09-archives
#+manifold-date: 2026-09-15

* Getting Help

Emacs provides a wide variety of help commands, all accessible through the prefix key C-h (or, equivalently, the function key F1). These help commands are described in the following sections. You can also type C-h C-h to view a list of help commands (help-for-help). You can scroll the list with SPC and DEL, then type the help command you want. To cancel, type C-g.

Many help commands display their information in a special help buffer. In this buffer, you can type SPC and DEL to scroll and type RET to follow hyperlinks. See Help Mode Commands.

By default, help commands display the help buffer in a separate window without selecting that window. The variable help-window-select controls this: its default value is nil; if it’s customized to the value t, the help window is unconditionally selected by help commands, and if its value is other, the help window is selected only if there are more than two windows on the selected frame.

Conversely, many commands in the ‘*Help*’ buffer will pop up a new window to display the results. For instance, clicking on the link to show the source code, or using the i command to display the manual entry, will (by default) pop up a new window. If help-window-keep-selected is changed to non-nil, the window displaying the ‘*Help*’ buffer will be reused instead.

If you are looking for a certain feature, but don’t know what it is called or where to look, we recommend three methods. First, try an apropos command, then try searching the manual index, then look in the FAQ and the package keywords, and finally try listing external packages.

C-h a topics RET
This searches for commands whose names match the argument topics. The argument can be a keyword, a list of keywords, or a regular expression (see Syntax of Regular Expressions). See Apropos.

C-h i d m emacs RET i topic RET
This searches for topic in the indices of the Emacs Info manual, displaying the first match found. Press , to see subsequent matches. You can use a regular expression as topic.

C-h i d m emacs RET s topic RET
Similar, but searches the text of the manual rather than the indices.

C-h C-f
This displays the Emacs FAQ, using Info.

C-h p
This displays the available Emacs packages based on keywords. See Keyword Search for Packages.

M-x list-packages
This displays a list of external packages. See Emacs Lisp Packages.

C-h or F1 mean “help” in various other contexts as well. For instance, you can type them after a prefix key to view a list of the keys that can follow the prefix key. (You can also use ? in this context. A few prefix keys don’t support C-h or ? in this way, because they define other meanings for those inputs, but they all support F1.)


*** Help Summary

Here is a summary of help commands for accessing the built-in documentation. Most of these are described in more detail in the following sections.

**** C-h a topics RET
Display a list of commands whose names match topics (apropos-command). See Apropos.

**** C-h b
Display all active key bindings; minor mode bindings first, then those of the major mode, then global bindings (describe-bindings). See Other Help Commands.

**** C-h C-q
Toggle display of a window showing popular commands and their key bindings. See Other Help Commands.

**** C-h c key
Show the name of the command that the key sequence key is bound to (describe-key-briefly). Here c stands for “character”. For more extensive information on key, use C-h k. See Documentation for a Key.

**** C-h d topics RET
Display the commands and variables whose documentation matches topics (apropos-documentation). See Apropos.

**** C-h e
Display the *Messages* buffer (view-echo-area-messages). See Other Help Commands.

**** C-h f function RET
Display documentation on the Lisp function named function (describe-function). Since commands are Lisp functions, this works for commands too, but you can also use C-h x. See Help by Command or Variable Name.

**** C-h h
Display the HELLO file, which shows examples of various character sets.

**** C-h i
Run Info, the GNU documentation browser (info). The Emacs manual is available in Info. See Other Help Commands.

**** C-h k key
Display the name and documentation of the command that key runs (describe-key). See Documentation for a Key.

**** C-h l
Display a description of your last 300 keystrokes (view-lossage). See Other Help Commands.

**** C-h m
Display documentation of the current major mode and minor modes (describe-mode). See Other Help Commands.

**** C-h n
Display news of recent Emacs changes (view-emacs-news). See Help Files.

**** C-h o symbol
Display documentation of the Lisp symbol named symbol (describe-symbol). This will show the documentation of all kinds of symbols: functions, variables, and faces. See Help by Command or Variable Name.

**** C-h p
Find packages by topic keyword (finder-by-keyword). See Keyword Search for Packages. This lists packages using a package menu buffer. See Emacs Lisp Packages.

**** C-h P package RET
Display documentation about the specified package (describe-package). See Keyword Search for Packages.

**** C-h r
Display the Emacs manual in Info (info-emacs-manual).

**** C-h s
Display the contents of the current syntax table (describe-syntax). See Other Help Commands. The syntax table says which characters are opening delimiters, which are parts of words, and so on. See Syntax Tables in The Emacs Lisp Reference Manual, for details.

**** C-h t
Enter the Emacs interactive tutorial (help-with-tutorial).

**** C-h v var RET
Display the documentation of the Lisp variable var (describe-variable). See Help by Command or Variable Name.

**** C-h w command RET
Show which keys run the command named command (where-is). See Documentation for a Key.

**** C-h x command RET
Display documentation on the named command (describe-command). See Help by Command or Variable Name.

**** C-h C coding RET
Describe the coding system coding (describe-coding-system). See Coding Systems.

**** C-h C RET
Describe the coding systems currently in use.

**** C-h F command RET
Enter Info and go to the node that documents the Emacs command command (Info-goto-emacs-command-node). See Help by Command or Variable Name.

**** C-h I method RET
Describe the input method method (describe-input-method). See Selecting an Input Method.

**** C-h K key
Enter Info and go to the node that documents the key sequence key (Info-goto-emacs-key-command-node). See Documentation for a Key.

**** C-h L language-env RET
Display information on the character sets, coding systems, and input methods used in language environment language-env (describe-language-environment). See Language Environments.

**** C-h S symbol RET
Display the Info documentation on symbol symbol according to the programming language you are editing (info-lookup-symbol). See Other Help Commands.

**** C-h .
Display the help message for a special text area, if point is in one (display-local-help). (These include, for example, links in *Help* buffers.) See Help on Active Text and Tooltips. If you invoke this command with a prefix argument, C-u C-h ., and point is on a button or a widget, this command will pop a new buffer that describes that button/widget.


*** Documentation for a Key

The help commands to get information about a key sequence are C-h c (describe-key-briefly) and C-h k (describe-key).

C-h c key displays in the echo area the name of the command that key is bound to. For example, C-h c C-f displays ‘forward-char’.

C-h k key is similar but gives more information: it displays a help buffer containing the command’s documentation string, which describes exactly what the command does.

C-h K key displays the section of the Emacs manual that describes the command corresponding to key.

C-h c, C-h k and C-h K work for any sort of key sequences, including function keys, menus, and mouse events (except that C-h c ignores mouse movement events). For instance, after C-h k you can select a menu item from the menu bar, to view the documentation string of the command it runs.

C-h w command RET lists the keys that are bound to command. It displays the list in the echo area. If it says the command is not on any key, that means you must use M-x to run it. C-h w runs the command where-is.

Some modes in Emacs use various buttons (see Buttons in The Emacs Lisp Reference Manual) and widgets (see Introduction in Emacs Widgets) that can be clicked to perform some action. To find out what function is ultimately invoked by these buttons, Emacs provides the button-describe and widget-describe commands, that should be run with point over the button.

*** Help by Command or Variable Name

C-h x command RET (describe-command) displays the documentation of the named command, in a window. For example,

C-h x auto-fill-mode RET
displays the documentation of auto-fill-mode. This is how you would get the documentation of a command that is not bound to any key (one which you would normally run using M-x).

C-h f function RET (describe-function) displays the documentation of Lisp function. This command is intended for Lisp functions that you use in a Lisp program. For example, if you have just written the expression (make-vector len) and want to check that you are using make-vector properly, type C-h f make-vector RET. Additionally, since all commands are Lisp functions, you can also use this command to view the documentation of any command.

If you type C-h f RET, it describes the function called by the innermost Lisp expression in the buffer around point, provided that function name is a valid, defined Lisp function. (That name appears as the default while you enter the argument.) For example, if point is located following the text ‘(make-vector (car x)’, the innermost list containing point is the one that starts with ‘(make-vector’, so C-h f RET describes the function make-vector.

C-h f is also useful just to verify that you spelled a function name correctly. If the minibuffer prompt for C-h f shows the function name from the buffer as the default, it means that name is defined as a Lisp function. Type C-g to cancel the C-h f command if you don’t really want to view the documentation.

If you request help for an autoloaded function whose autoload form (see Autoload in The Emacs Lisp Reference Manual) doesn’t provide a doc string, the *Help* buffer won’t have any doc string to display. In that case, if help-enable-symbol-autoload is non-nil, Emacs will try to load the file in which the function is defined to see whether there’s a doc string there.

You can get an overview of functions relevant for a particular topic by using the M-x shortdoc command. This will prompt you for an area of interest, e.g., string, and pop you to a buffer where many of the functions relevant for handling strings are listed.

C-h v (describe-variable) is like C-h f but describes Lisp variables instead of Lisp functions. Its default is the Lisp symbol around or before point, if that is the name of a defined Lisp variable. See Variables.

Help buffers that describe Emacs variables and functions normally have hyperlinks to the corresponding source code, if you have the source files installed (see Hyperlinking and Web Navigation Features).

To find a command’s documentation in a manual, use C-h F (Info-goto-emacs-command-node). This knows about various manuals, not just the Emacs manual, and finds the right one.

C-h o (describe-symbol) is like C-h f and C-h v, but it describes any symbol, be it a function, a variable, or a face. If the symbol has more than one definition, like it has both definition as a function and as a variable, this command will show the documentation of all of them, one after the other.

If the completions-detailed user option is non-nil, some commands provide details about the possible values when displaying completions. For instance, C-h o TAB will then include the first line of the doc string, and will also say whether each symbol is a function or a variable (and so on). Which details are included varies depending on the command used.


*** Apropos

The apropos commands answer questions like, “What are the commands for working with files?” More precisely, you specify your query as an apropos pattern, which is either a word, a list of words, or a regular expression.

Each of the following apropos commands reads an apropos pattern in the minibuffer, searches for items that match the pattern, and displays the results in a different window.

C-h a ¶
Search for commands (apropos-command). With a prefix argument, search for noninteractive functions too.

M-x apropos ¶
Search for functions and variables. Both interactive functions (commands) and noninteractive functions can be found by this.

M-x apropos-user-option ¶
Search for user-customizable variables. With a prefix argument, search for non-customizable variables too.

M-x apropos-variable ¶
Search for variables. With a prefix argument, search for customizable variables only.

M-x apropos-local-variable ¶
Search for buffer-local variables.

M-x apropos-value ¶
Search for variables whose values match the specified pattern. With a prefix argument, search also for functions with definitions matching the pattern, and Lisp symbols with properties matching the pattern.

M-x apropos-local-value ¶
Search for buffer-local variables whose values match the specified pattern.

C-h d ¶
Search for functions and variables whose documentation strings match the specified pattern (apropos-documentation).

The simplest kind of apropos pattern is one word. Anything containing that word matches the pattern. Thus, to find commands that work on files, type C-h a file RET. This displays a list of all command names that contain ‘file’, including copy-file, find-file, and so on. Each command name comes with a brief description and a list of keys you can currently invoke it with. In our example, it would say that you can invoke find-file by typing C-x C-f.

By default, the window showing the apropos buffer with the results of the query is not selected, but you can cause it to be selected by customizing the variable help-window-select to any non-nil value.

For more information about a function definition, variable or symbol property listed in an apropos buffer, you can click on it with mouse-1 or mouse-2, or move there and type RET.

When you specify more than one word in the apropos pattern, a name must contain at least two of the words in order to match. Thus, if you are looking for commands to kill a chunk of text before point, you could try C-h a kill back backward behind before RET. The real command name kill-backward will match that; if there were a command kill-text-before, it would also match, since it contains two of the specified words.

For even greater flexibility, you can specify a regular expression (see Syntax of Regular Expressions). An apropos pattern is interpreted as a regular expression if it contains any of the regular expression special characters, ‘^$*+?.\[’.

Following the conventions for naming Emacs commands, here are some words that you’ll find useful in apropos patterns. By using them in C-h a, you will also get a feel for the naming conventions.

char, line, word, sentence, paragraph, region, page, sexp, list, defun, rect, buffer, frame, window, face, file, dir, register, mode, beginning, end, forward, backward, next, previous, up, down, search, goto, kill, delete, mark, insert, yank, fill, indent, case, change, set, what, list, find, view, describe, default.

If the variable apropos-do-all is non-nil, most apropos commands behave as if they had been given a prefix argument. There is one exception: apropos-variable without a prefix argument will always search for all variables, no matter what the value of apropos-do-all is.

By default, all apropos commands except apropos-documentation list their results in alphabetical order. If the variable apropos-sort-by-scores is non-nil, these commands instead try to guess the relevance of each result, and display the most relevant ones first. The apropos-documentation command lists its results in order of relevance by default; to list them in alphabetical order, change the variable apropos-documentation-sort-by-scores to nil.


*** Help Mode Commands

Help buffers have Help mode as their major mode. Help mode provides the same commands as View mode (see View Mode); for instance, SPC scrolls forward, and DEL or S-SPC scrolls backward. It also provides a few special commands:

RET
Follow a cross reference at point (help-follow).

TAB
Move point forward to the next hyperlink (forward-button).

S-TAB
Move point back to the previous hyperlink (backward-button).

mouse-1
mouse-2
Follow a hyperlink that you click on.

n
p
Move forward and back between pages in the Help buffer.

C-c C-c
Show all documentation about the symbol at point (help-follow-symbol).

C-c C-f
r
Go forward in history of help commands (help-go-forward).

C-c C-b
l
Go back in history of help commands (help-go-back).

s
View the source of the current help topic (if any) (help-view-source).

i
Look up the current topic in the manual(s) (help-goto-info).

I
Look up the current topic in the Emacs Lisp manual (help-goto-lispref-info).

c
Customize the variable or the face (help-customize).

When a function name, variable name, or face name (see Text Faces) appears in the documentation in the help buffer, it is normally an underlined hyperlink. To view the associated documentation, move point there and type RET (help-follow), or click on the hyperlink with mouse-1 or mouse-2. Doing so replaces the contents of the help buffer; to retrace your steps, type C-c C-b or l (help-go-back). While retracing your steps, you can go forward by using C-c C-f or r (help-go-forward).

To move between hyperlinks in a help buffer, use TAB (forward-button) to move forward to the next hyperlink and S-TAB (backward-button) to move back to the previous hyperlink. These commands act cyclically; for instance, typing TAB at the last hyperlink moves back to the first hyperlink.

By default, many links in the help buffer are displayed surrounded by quote characters. If the help-clean-buttons user option is non-nil, these quote characters are removed from the buffer.

Help buffers produced by some Help commands (like C-h b, which shows a long list of key bindings) are divided into pages by the ‘^L’ character. In such buffers, the n (help-goto-next-page) command will take you to the next start of page, and the p (help-goto-previous-page) command will take you to the previous start of page. This way you can quickly navigate between the different kinds of documentation in a help buffer.

A help buffer can also contain hyperlinks to Info manuals, source code definitions, and URLs (web pages). The first two are opened in Emacs, and the third using a web browser via the browse-url command (see Following URLs).

To view all documentation about any symbol in the text, move point to the symbol and type C-c C-c (help-follow-symbol). This shows the documentation for all the meanings of the symbol—as a variable, as a function, and/or as a face.


*** Keyword Search for Packages

Most optional features in Emacs are grouped into packages. Emacs contains several hundred built-in packages, and more can be installed over the network (see Emacs Lisp Packages).

To make it easier to find packages related to a topic, most packages are associated with one or more keywords based on what they do. Type C-h p (finder-by-keyword) to bring up a list of package keywords, together with a description of what the keywords mean. To view a list of packages for a given keyword, type RET on that line; this displays the list of packages in a Package Menu buffer (see The Package Menu Buffer).

C-h P (describe-package) prompts for the name of a package (see Emacs Lisp Packages), and displays a help buffer describing the attributes of the package and the features that it implements. The buffer lists the keywords that relate to the package in the form of buttons. Click on a button with mouse-1 or mouse-2 to see the list of other packages related to that keyword.


*** Help for International Language Support

For information on a specific language environment (see Language Environments), type C-h L (describe-language-environment). This displays a help buffer describing the languages supported by the language environment, and listing the associated character sets, coding systems, and input methods, as well as some sample text for that language environment.

The command C-h h (view-hello-file) displays the file etc/HELLO, which demonstrates various character sets by showing how to say “hello” in many languages.

The command C-h I (describe-input-method) describes an input method—either a specified input method, or by default the input method currently in use. See Input Methods.

The command C-h C (describe-coding-system) describes coding systems—either a specified coding system, or the ones currently in use. See Coding Systems.


*** Other Help Commands

C-h i (info) runs the Info program, which browses structured documentation files. C-h 4 i (info-other-window) does the same, but shows the Info buffer in another window. The entire Emacs manual is available within Info, along with many other manuals for the GNU system. Type h after entering Info to run a tutorial on using Info.

With a numeric argument n, C-h i selects the Info buffer ‘*info*<n>’. This is useful if you want to browse multiple Info manuals simultaneously. If you specify just C-u as the prefix argument, C-h i prompts for the name of a documentation file, so you can browse a file which doesn’t have an entry in the top-level Info menu.

The help commands C-h F function RET and C-h K key, described above, enter Info and go straight to the documentation of function or key.

When editing a program, if you have an Info version of the manual for the programming language, you can use C-h S (info-lookup-symbol) to find an entry for a symbol (keyword, function or variable) in the proper manual. The details of how this command works depend on the major mode.

If something surprising happens, and you are not sure what you typed, use C-h l (view-lossage). C-h l displays your last input keystrokes and the commands they invoked. By default, Emacs stores the last 300 keystrokes; if you wish, you can change this number with the command lossage-size. If you see commands that you are not familiar with, you can use C-h k or C-h f to find out what they do.

To review recent echo area messages, use C-h e (view-echo-area-messages). This displays the buffer *Messages*, where those messages are kept.

Each Emacs major mode typically redefines a few keys and makes other changes in how editing works. C-h m (describe-mode) displays documentation on the current major mode, which normally describes the commands and features that are changed in this mode, and also its key bindings.

C-h b (describe-bindings) and C-h s (describe-syntax) show other information about the current environment within Emacs. C-h b displays a list of all the key bindings now in effect: first the local bindings of the current minor modes, then the local bindings defined by the current major mode, and finally the global bindings (see Customizing Key Bindings). C-h s displays the contents of the syntax table, with explanations of each character’s syntax (see Syntax Tables in The Emacs Lisp Reference Manual).

C-h C-q (help-quick-toggle) toggles on and off the display of a buffer showing the most popular Emacs commands and their respective key bindings (a.k.a. “cheat sheet”). The contents of that buffer are created by the command help-quick. Each key binding shown in this buffer is a button: click on it with mouse-1 or mouse-2 to show the documentation of the command bound to that key sequence.

You can get a list of subcommands for a particular prefix key by typing C-h, ?, or F1 (describe-prefix-bindings) after the prefix key. (There are a few prefix keys for which not all of these keys work—those that provide their own bindings for that key. One of these prefix keys is ESC, because ESC C-h and ESC ? are actually C-M-h (mark-defun) and M-? (xref-find-references), respectively. However, ESC F1 works fine.)

Finally, M-x describe-keymap prompts for the name of a keymap, with completion, and displays a listing of all key bindings in that keymap.


*** Help Files

Apart from the built-in documentation and manuals, Emacs contains several other files describing topics like copying conditions, release notes, instructions for debugging and reporting bugs, and so forth. You can use the following commands to view these files. Apart from C-h g, they all have the form C-h C-char.

**** C-h C-c
Display the rules under which you can copy and redistribute Emacs (describe-copying).

**** C-h C-d
Display help for debugging Emacs (view-emacs-debugging).

**** C-h C-e
Display information about where to get external packages (view-external-packages).

**** C-h C-f
Display the Emacs frequently-answered-questions list (view-emacs-FAQ).

**** C-h g
Visit the page with information about the GNU Project (describe-gnu-project).

**** C-h C-m
Display information about ordering printed copies of Emacs manuals (view-order-manuals).

**** C-h C-n
Display the news, which lists the new features in this version of Emacs (view-emacs-news).

**** C-h C-o
Display how to order or download the latest version of Emacs and other GNU software (describe-distribution).

**** C-h C-p
Display the list of known Emacs problems, sometimes with suggested workarounds (view-emacs-problems).

**** C-h C-t
Display the Emacs to-do list (view-emacs-todo).

**** C-h C-w
Display the full details on the complete absence of warranty for GNU Emacs (describe-no-warranty).


*** Help on Active Text and Tooltips

In Emacs, stretches of active text (text that does something special in response to mouse clicks or RET) often have associated help text. This includes hyperlinks in Emacs buffers, as well as parts of the mode line. On graphical displays, as well as some text terminals which support mouse tracking, moving the mouse over the active text displays the help text as a tooltip. See Tooltips.

On terminals that don’t support mouse-tracking, you can display the help text for active buffer text at point by typing C-h . (display-local-help). This shows the help text in the echo area. To display help text automatically whenever it is available at point, set the variable help-at-pt-display-when-idle to t.
